### PR TITLE
fix: Resolve scoreboard and button issues

### PR DESCRIPTION
**Pull request by faucomte97**
This change is [Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1369)

### CODE REVIEW

**Review by KamilPawel — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1369)* status: all files reviewed, 2 unresolved discussions (waiting on @faucomte97)

___
*[`Pipfile` line 16 at r2](https://reviewable.io/reviews/ocadotechnology/rapid-router/1369#-NBrFSp2Eh4Pj8hrd64Q:-NBrFSp2Eh4Pj8hrd64R:b9vmz7v) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/7d3a55878b956591100e2e976a4a26fe0c89de15/Pipfile#L16)):*
> ```TOML
> pytest = "==7.*"
> pytest-xdist = "*"
> pytest-order = "*"
> ```

Is that Mykhaylo change? :thinking: 
___
*[`game/templates/game/scoreboard.html` line 259 at r2](https://reviewable.io/reviews/ocadotechnology/rapid-router/1369#-NBrFoAu4CDb1oaJ1kK9:-NBrFoAu4CDb1oaJ1kKA:b-r40vsp) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/7d3a55878b956591100e2e976a4a26fe0c89de15/game/templates/game/scoreboard.html#L259)):*
> ```HTML
>             </table>
>         {% else %}
>             No data.
> ```

No data without any <></> tags?

**Review by faucomte97 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1369)* status: 6 of 7 files reviewed, 2 unresolved discussions (waiting on @KamilPawel)

___
*[`Pipfile` line 16 at r2](https://reviewable.io/reviews/ocadotechnology/rapid-router/1369#-NBrFSp2Eh4Pj8hrd64Q:-NBrGA5nAlW73Nf5JTIf:bvvtyom) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/7d3a55878b956591100e2e976a4a26fe0c89de15/Pipfile#L16)):*
<details><summary><i>Previously, KamilPawel wrote…</i></summary><blockquote>

Is that Mykhaylo change? :thinking: 
</blockquote></details>

He seemed to have added it to the ci.yml yeah, so I thought I'd move it and add it to the Pipfile instead along with the xdist one
___
*[`game/templates/game/scoreboard.html` line 259 at r2](https://reviewable.io/reviews/ocadotechnology/rapid-router/1369#-NBrFoAu4CDb1oaJ1kK9:-NBrGfKs0lllq5caISAH:b2231w5) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/7d3a55878b956591100e2e976a4a26fe0c89de15/game/templates/game/scoreboard.html#L259)):*
<details><summary><i>Previously, KamilPawel wrote…</i></summary><blockquote>

No data without any <></> tags?
</blockquote></details>

Good catch :stuck_out_tongue:

**Review by KamilPawel — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1369#-:-NBrHRgD6OtVR2YhfCQy:bnfp4nl)* status: 6 of 7 files reviewed, all discussions resolved (waiting on @KamilPawel)

**Review by KamilPawel — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1369#-:-NBrH_Lp1zDGZvr8eGfT:bnfp4nl)* status: 6 of 7 files reviewed, all discussions resolved (waiting on @KamilPawel)

**Review by KamilPawel — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1369)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @faucomte97)

**Pull request merged**
