### PR TITLE
fix: fix scoring for custom levels

### PR DESCRIPTION
**Pull request by evemartin**
This change is [Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1624)

### CODE REVIEW

**Comment by evemartin** [comment]
The edits to `game.html` are just for tabbing - I had originally made some other test-related changes to that file which I later got rid of but the formatting change is still there. I'm happy to get rid of it if you feel it makes the PR overly complicated but I have left it for now since it felt strange to untidy it on purpose!

**Review by faucomte97 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r1, 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1624)* status: all files reviewed, 2 unresolved discussions (waiting on @evemartin)

___
*[`game/tests/test_level_editor.py` line 401 at r3](https://reviewable.io/reviews/ocadotechnology/rapid-router/1624#-NyeRleRDmoX7Y67PSOQ:-NyeRleS91Ie11NwPvTU:b-hgbobo) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/cc43eb6c969b8ac2ccde7cbe5e56a5e2b2bc27f5/game/tests/test_level_editor.py#L401)):*
> ```Python
> 
>         self.login(email1, password1)
>         level = create_save_level_with_multiple_houses(teacher1)
> ```

(Read this comment after you've read my other one)

If you disable the algo score on creation, then you could add a check right after this line to assert that the algo score is in fact disabled :slightly_smiling_face: 
___
*[`game/views/level.py` line 41 at r3](https://reviewable.io/reviews/ocadotechnology/rapid-router/1624#-NyeQr-x1tyvlXQLZWy0:-NyeQr-x1tyvlXQLZWy1:b-6pdr0y) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/cc43eb6c969b8ac2ccde7cbe5e56a5e2b2bc27f5/game/views/level.py#L41)):*
> ```Python
> def play_custom_level(request, levelId, from_editor=False):
>     level = cached_custom_level(levelId)
>     level.disable_algorithm_score = True
> ```

While I understand that this specific line is the fix for the issue, I believe it should happen upon level creation / save to DB rather than when the level is loaded to be played - if that makes sense.
Essentially, what I'm saying is that the level's algorithm score should be disabled as soon as the level is created and saved to the DB.

Side question: how are you disabling the algorithm score without doing `level.save()`? :scream: :thinking:

**Review by evemartin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1624)* status: 5 of 9 files reviewed, 2 unresolved discussions (waiting on @faucomte97)

___
*[`game/tests/test_level_editor.py` line 401 at r3](https://reviewable.io/reviews/ocadotechnology/rapid-router/1624#-NyeRleRDmoX7Y67PSOQ:-Nyexifa3pWiSyWwXm_o:b-4o61iw) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/cc43eb6c969b8ac2ccde7cbe5e56a5e2b2bc27f5/game/tests/test_level_editor.py#L401)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

(Read this comment after you've read my other one)

If you disable the algo score on creation, then you could add a check right after this line to assert that the algo score is in fact disabled :slightly_smiling_face:
</blockquote></details>

Added :) I ended up using a mock since the data values don't end up getting returned as part of the response!
___
*[`game/views/level.py` line 41 at r3](https://reviewable.io/reviews/ocadotechnology/rapid-router/1624#-NyeQr-x1tyvlXQLZWy0:-Nyexz6hEj6t7K49mQ2N:b-7dajmy) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/cc43eb6c969b8ac2ccde7cbe5e56a5e2b2bc27f5/game/views/level.py#L41)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

While I understand that this specific line is the fix for the issue, I believe it should happen upon level creation / save to DB rather than when the level is loaded to be played - if that makes sense.
Essentially, what I'm saying is that the level's algorithm score should be disabled as soon as the level is created and saved to the DB.

Side question: how are you disabling the algorithm score without doing `level.save()`? :scream: :thinking:
</blockquote></details>

I agree that it makes more sense to save the level with `disabled_algorithm_score = True` in the database and have made the change to reflect that in my most recent push, but we also have to address the custom levels that were made before the change, since they won't necessarily be saved again, just loaded - will we need a migration for this?

I think that with the way I had it before the algorithm score was getting disabled just before the level got loaded, so when it loaded it would have this property - it just wouldn't save to the database :sweat_smile:

**Review by faucomte97 — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1624)* status: all files reviewed, 1 unresolved discussion (waiting on @evemartin)

___
*[`game/tests/test_level_editor.py` line 412 at r4](https://reviewable.io/reviews/ocadotechnology/rapid-router/1624#-NyfS1oA9859x96GgApR:-NyfS1oA9859x96GgApS:boeqpb) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/d824b92d6bf850dc9ae1f00d1c92518a2f74b230/game/tests/test_level_editor.py#L412)):*
> ```Python
> 
>         assert response.status_code == 200
>         assert disable_algorithm_score == True
> ```

no need to have `== True`

**Review by evemartin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1624)* status: 9 of 10 files reviewed, 1 unresolved discussion (waiting on @faucomte97)

___
*[`game/tests/test_level_editor.py` line 412 at r4](https://reviewable.io/reviews/ocadotechnology/rapid-router/1624#-NyfS1oA9859x96GgApR:-NyyH3_lDUaEG-WvBWRr:busawlc) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/d824b92d6bf850dc9ae1f00d1c92518a2f74b230/game/tests/test_level_editor.py#L412)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

no need to have `== True`
</blockquote></details>

Fixed :)

**Review by faucomte97 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1624#-:-Nyz3Nhh-8Rh98W7w2Dj:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @evemartin)

**Review by faucomte97 — APPROVED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1624)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @evemartin)

**Pull request merged**
