### PR TITLE
feat: add language dropdown

### PR DESCRIPTION
**Pull request by evemartin**
This change is [Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1606)

### CODE REVIEW

**Review by evemartin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1606)* status: all files reviewed, 10 unresolved discussions (waiting on @faucomte97)

___
*[`game/end_to_end_tests/game_page.py` line 25 at r3](https://reviewable.io/reviews/ocadotechnology/rapid-router/1606#-NweC9vv1v3mf7Lvy18P:-NweIkIL17U0XV-Ka1u4:b6jyrgl) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/d1afd628bc304972528d4f41c858121adf4ed8b3/game/end_to_end_tests/game_page.py#L25)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

You've got some whitespaces on this line, running Black should fix it.
</blockquote></details>

Fixed and will push with the other changes!
___
*[`game/end_to_end_tests/test_language_dropdown.py` line 11 at r3](https://reviewable.io/reviews/ocadotechnology/rapid-router/1606#-NweF8m032rvW5whxNPp:-NweIpG35YuFFSr4XBYh:b6jyrgl) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/d1afd628bc304972528d4f41c858121adf4ed8b3/game/end_to_end_tests/test_language_dropdown.py#L11)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

I don't think you need an f-string here
</blockquote></details>

Fixed and will push with the other changes!
___
*[`game/end_to_end_tests/test_language_dropdown.py` line 14 at r3](https://reviewable.io/reviews/ocadotechnology/rapid-router/1606#-NweFDZqDf977TiZ5Sxy:-NweIpi50_Ee7KeFYAMN:b6jyrgl) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/d1afd628bc304972528d4f41c858121adf4ed8b3/game/end_to_end_tests/test_language_dropdown.py#L14)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Add a new line after this line please. I think Black fixes that too
</blockquote></details>

Fixed and will push with the other changes!
___
*[`game/static/game/css/game_screen.css` line 437 at r3](https://reviewable.io/reviews/ocadotechnology/rapid-router/1606#-NweFd9eANhMRuNCwVX9:-NweMxUUAwtCN_jxbPB2:bxg6pxk) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/d1afd628bc304972528d4f41c858121adf4ed8b3/game/static/game/css/game_screen.css#L437)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Dropdown looks good to me but double-check with Laura if you haven't already to see what she thinks.
</blockquote></details>

I'll send her a screen recording to confirm!
___
*[`game/static/game/js/blocklyControl.js` line 56 at r3](https://reviewable.io/reviews/ocadotechnology/rapid-router/1606#-NweGaIh83dtdNIL5aG8:-NweLigo6JblwbciyPLs:bp44g8g) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/d1afd628bc304972528d4f41c858121adf4ed8b3/game/static/game/js/blocklyControl.js#L56)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Do you need this function here? I know you call it later but I wonder if we can just have it in the other file (check my other comment).
</blockquote></details>

I've moved it to the other file and it seems to work still! So I'll go with your suggested change :))
___
*[`game/static/game/js/game.js` line 1397 at r3](https://reviewable.io/reviews/ocadotechnology/rapid-router/1606#-NweGiy7D8_ois1-tjVb:-NweMv8UBP4k2E3qj0uI:bu6zfrf) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/d1afd628bc304972528d4f41c858121adf4ed8b3/game/static/game/js/game.js#L1397)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Here - maybe replace this with the core code for the function, move it up in the file and call `gameUpdateBlockLanguage` at the start of the `setup` function as well.
</blockquote></details>

Same as other comment!
___
*[`game/static/game/js/game.js` line 1406 at r3](https://reviewable.io/reviews/ocadotechnology/rapid-router/1606#-NweGu6v8paVPsfqmkGU:-NweIwaw1-TzXwYuOCIG:b6jyrgl) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/d1afd628bc304972528d4f41c858121adf4ed8b3/game/static/game/js/game.js#L1406)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

You have an extra white line here.
</blockquote></details>

Fixed and will push with the other changes!
___
*[`game/static/game/js/blockly/msg/js/fr.js` line 439 at r3](https://reviewable.io/reviews/ocadotechnology/rapid-router/1606#-NweFvaOCNLW00y0pX7M:-NweIx_o2rdYOZwbHfcQ:b-95o59) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/d1afd628bc304972528d4f41c858121adf4ed8b3/game/static/game/js/blockly/msg/js/fr.js#L439)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

:sob:
</blockquote></details>

I'm so sorry :sob: 
___
*[`game/templates/game/game.html` line 163 at r3](https://reviewable.io/reviews/ocadotechnology/rapid-router/1606#-NweGBMj6G4XGqkGdWi6:-NweJUu07IbTBWfv71YU:b6jyrgl) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/d1afd628bc304972528d4f41c858121adf4ed8b3/game/templates/game/game.html#L163)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

I'm assuming we don't want the dropdown to show on Python-only levels, so we probably need an additional check here.
</blockquote></details>

Fixed and will push with the other changes!
___
*[`game/views/language_code_conversions.py` line 1 at r3](https://reviewable.io/reviews/ocadotechnology/rapid-router/1606#-NweGJQ16c5RAlWEWftX:-NweJ75HA3jI50ftczQ9:b6jyrgl) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/d1afd628bc304972528d4f41c858121adf4ed8b3/game/views/language_code_conversions.py#L1)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Please make a note here to only populate the languages that we have fully translations with for the custom blocks - we can comment out the ones that aren't ready.
</blockquote></details>

Fixed and will push with the other changes!

**Review by faucomte97 — CHANGES_REQUESTED** [review]
> Reviewed 14 of 14 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1606)* status: all files reviewed, 2 unresolved discussions (waiting on @evemartin)

___
*[`game/static/game/css/backgrounds.css` line 4 at r4](https://reviewable.io/reviews/ocadotechnology/rapid-router/1606#-NxMtKf_5cKUJvlHOcwH:-NxMtKf_5cKUJvlHOcwI:bb76mu4) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/b8020bbf717aebb33bd5951538e0ca55d9150215/game/static/game/css/backgrounds.css#L4)):*
> ```CSS
> 
> .bg--easy {
>     background-color: #86ae18;
> ```

Why?

**Review by evemartin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1606)* status: all files reviewed, 2 unresolved discussions (waiting on @faucomte97)

___
*[`game/static/game/css/backgrounds.css` line 4 at r4](https://reviewable.io/reviews/ocadotechnology/rapid-router/1606#-NxMtKf_5cKUJvlHOcwH:-NxMwyAA7fkO_LRO-Ny7:b-w1dg55) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/b8020bbf717aebb33bd5951538e0ca55d9150215/game/static/game/css/backgrounds.css#L4)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Why?
</blockquote></details>

When it was just "background" it was covering up the dropdown menu's arrow icon - changing it to "background-color" brought the icon back (though I'm not 100% sure why this is the case)! 
___
*[`game/static/game/css/game_screen.css` line 437 at r3](https://reviewable.io/reviews/ocadotechnology/rapid-router/1606#-NweFd9eANhMRuNCwVX9:-NxMxJvq5fUK5WSwjQRz:bfe4hje) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/d1afd628bc304972528d4f41c858121adf4ed8b3/game/static/game/css/game_screen.css#L437)):*
<details><summary><i>Previously, evemartin wrote…</i></summary><blockquote>

I'll send her a screen recording to confirm!
</blockquote></details>

I have got the okay after checking!

**Review by faucomte97 — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1606#-:-NxSfztfEiozF2lSWIMK:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @evemartin)

**Pull request merged**
