### PR TITLE
feat: prev next buttons

### PR DESCRIPTION
**Pull request by KamilPawel**
## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have linked this PR to a ZenHub Issue.

- - -
This change is [Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1383)

### CODE REVIEW

**Review by faucomte97 — CHANGES_REQUESTED** [review]
> Reviewed 12 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1383)* status: all files reviewed, 5 unresolved discussions (waiting on @KamilPawel)

___
*[`game/migrations/0077_alter_level_next_level.py` line 19 at r1](https://reviewable.io/reviews/ocadotechnology/rapid-router/1383#-NID3-I22l7eUajA5WBY:-NID3-I22l7eUajA5WBZ:b-d5bfp4) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/506a38fb68fb615fdf0d3edbbe0b6482f8eccee5/game/migrations/0077_alter_level_next_level.py#L19)):*
> ```Python
>             Level_Object_Wrapper.filter(name=level.name).update(
>                 next_level=next_level_update
>             )
> ```

can you add some code which is the reverse of this please, just like we have in migration 0075 for example



_Code quote:_
```Python
    def add_next_level_to_last_levels(apps, schema_editor):
        Level = apps.get_model("game", "Level")
        db_alias = schema_editor.connection.alias
        Level_Object_Wrapper = Level.objects.using(db_alias)
        levels = Level_Object_Wrapper.filter(next_level=None).exclude(name="109")
        for level in levels:
            next_level_update = Level_Object_Wrapper.get(
                name=(str(int(level.name) + 1))
            )
            Level_Object_Wrapper.filter(name=level.name).update(
                next_level=next_level_update
            )
```
___
*[`game/static/game/css/game_screen.css` line 291 at r1](https://reviewable.io/reviews/ocadotechnology/rapid-router/1383#-NID3FPHEJfCTjRZEshv:-NID3FPHEJfCTjRZEshw:bktldk9) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/506a38fb68fb615fdf0d3edbbe0b6482f8eccee5/game/static/game/css/game_screen.css#L291)):*
> ```CSS
>   padding: 0px;
> }
> ```

Extra line
___
*[`game/static/game/js/drawing.js` line 1057 at r1](https://reviewable.io/reviews/ocadotechnology/rapid-router/1383#-NID3UET5sPRr7blumXK:-NID3UET5sPRr7blumXL:bdocd0j) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/506a38fb68fb615fdf0d3edbbe0b6482f8eccee5/game/static/game/js/drawing.js#L1057)):*
> ```JavaScript
>   // buttons are passed as html string..
>   // hence this terribleness
>   if (Array.isArray(buttons)) {
> ```

Can we have more comments for this function please
___
*[`game/static/game/js/game.js` line 428 at r1](https://reviewable.io/reviews/ocadotechnology/rapid-router/1383#-NID3i2F6fLgILui5_HC:-NID3i2F6fLgILui5_HD:bzbe37d) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/506a38fb68fb615fdf0d3edbbe0b6482f8eccee5/game/static/game/js/game.js#L428)):*
> ```JavaScript
>     if (pythonSliderPosition < 30) {
>       pythonSliderPosition = 30
>       codeWindowHeight = 30
> ```

What is this for?



_Code quote:_
```JavaScript
    if (pythonSliderPosition < 30) {
      pythonSliderPosition = 30
      codeWindowHeight = 30
```
___
*[`game/views/level.py` line 68 at r1](https://reviewable.io/reviews/ocadotechnology/rapid-router/1383#-NID4PJM4g2bX2XFSmAZ:-NID4PJM4g2bX2XFSmA_:b-lsarrs) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/506a38fb68fb615fdf0d3edbbe0b6482f8eccee5/game/views/level.py#L68)):*
> ```Python
>                 prev_level = prev_level.prev_level.all()[0]
>         except:
>             print("Fegcrjhsvunicoa khudsFAUL")
> ```

Kamil come on :stuck_out_tongue:

**Review by faucomte97 — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1383)* status: all files reviewed, 6 unresolved discussions (waiting on @KamilPawel)

___
*[`game/end_to_end_tests/base_game_test.py` line 82 at r3](https://reviewable.io/reviews/ocadotechnology/rapid-router/1383#-NIHOXg3-1ld_OAYIMgu:-NIHOXg3-1ld_OAYIMgv:b-kdnp9o) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/804396a01adbefb76081a96dcfe8de35202eb515/game/end_to_end_tests/base_game_test.py#L82)):*
> ```Python
>         path = reverse("play_default_level", kwargs={"levelName": str(level_name)})
>         self._go_to_path(path)
>         if close_popup:
> ```

Do we need this in the end?

**Review by faucomte97 — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1383)* status: all files reviewed, 1 unresolved discussion (waiting on @KamilPawel)

___
*[`game/end_to_end_tests/base_game_test.py` line 82 at r3](https://reviewable.io/reviews/ocadotechnology/rapid-router/1383#-NIHOXg3-1ld_OAYIMgu:-NIHlEQ18g1ByTDMLgjD:bbc3kq0) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/804396a01adbefb76081a96dcfe8de35202eb515/game/end_to_end_tests/base_game_test.py#L82)):*
<details><summary><i>Previously, KamilPawel wrote…</i></summary><blockquote>

Nope
</blockquote></details>

Then remove it from the arguments as well 😉
___
*[`game/migrations/0077_alter_level_next_level.py` line 19 at r1](https://reviewable.io/reviews/ocadotechnology/rapid-router/1383#-NID3-I22l7eUajA5WBY:-NIHllan7r-6OdraMNt8:b-rcx6hf) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/506a38fb68fb615fdf0d3edbbe0b6482f8eccee5/game/migrations/0077_alter_level_next_level.py#L19)):*
<details><summary><i>Previously, KamilPawel wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Ok but you need to call it 😝

**Review by KamilPawel — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1383#-:-NIHleTR79Rae8MEzOdG:bnfp4nl)* status: 12 of 14 files reviewed, 1 unresolved discussion (waiting on @faucomte97)

___
*[`game/end_to_end_tests/base_game_test.py` line 82 at r3](https://reviewable.io/reviews/ocadotechnology/rapid-router/1383#-NIHOXg3-1ld_OAYIMgu:-NIHmCdb9FDEd5KqWbnN:b-896fix) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/804396a01adbefb76081a96dcfe8de35202eb515/game/end_to_end_tests/base_game_test.py#L82)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Then remove it from the arguments as well 😉
</blockquote></details>

Done.
___
*[`game/migrations/0077_alter_level_next_level.py` line 19 at r1](https://reviewable.io/reviews/ocadotechnology/rapid-router/1383#-NID3-I22l7eUajA5WBY:-NIHmEH2BECznrbLkbnW:bneqptx) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/506a38fb68fb615fdf0d3edbbe0b6482f8eccee5/game/migrations/0077_alter_level_next_level.py#L19)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Ok but you need to call it 😝
</blockquote></details>

:joy:

**Review by faucomte97 — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1383#-:-NIHmvZ2ASpX3ovFI1W-:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @KamilPawel)

**Pull request merged**
