### PR TITLE
fix: invalid cow squares remain highlighted

### PR DESCRIPTION
**Pull request by RaihanRasheedApurbo**
## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have linked this PR to a ZenHub Issue.

- - -
This change is [Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1752)

### CODE REVIEW

**Comment by RaihanRasheedApurbo** [comment]
I have looked at the failed test's log. I don't know why it failed and how it could be related to the changes I made. I checked out master and ran the tests and it failed as well. Let me know what you think? @faucomte97

**Comment by faucomte97** [comment]
Hi @RaihanRasheedApurbo, I'm looking into this now - it is weird, and what's weirder is that I'm getting different error logs locally. I'll let you know what I find, but as of now it looks like an issue on our side.

**Comment by faucomte97** [comment]
Hi again @RaihanRasheedApurbo, the tests have passed after a few times of me rerunning them which confirms this is an flakiness issue on our side. I will now review your PR 🙂

**Review by faucomte97 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1752#-:-ODl-KBw46J6ZMvssIAW:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @RaihanRasheedApurbo)

**Pull request merged**
