### PR TITLE
feat: Remove superflous python commands in rapid router.

### PR DESCRIPTION
**Pull request by Ridwanah**
## Description

I implemented level specific commands for the following levels: 92-109, 113-115, 119-122. Originally clicking on the "Python command" button would give all the possible Python commands. Now it gives only the commands needed to complete that level. The commands for each level can be found in messages.py. I changed game.js and game.html to implement these changes. I added a commands field level.py in the views. It gets the commands for a level if it exists in messages.py, or it returns an empty string. 

## How Has This Been Tested?
I tested this using pytest. It passed 57 and failed 1 because I could not run the selenium tests locally. I am creating this pull request to test my code using the workflow.

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have linked this PR to a ZenHub Issue.

- - -
This change is [Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1680)

### CODE REVIEW

**Comment by faucomte97** [comment]
Hi again @Ridwanah,

It's great to see you've got some code ready for review for this task!
You can check the statuses of your PR too, including tests and semantic pull request name - feel free to ask any questions about these.

A few other points:
- don't worry about the Snyk status check. It's an optional check that only works for internal team members at the minute.
- now that you are submitting a contribution, you need to go through our [Contributor Agreement](https://github.com/ocadotechnology/codeforlife-workspace/blob/main/CONTRIBUTING.md#contributor-agreement) and follow the guide at the end on how to officially sign it. This needs to happen before we can merge in your pull request. Feel free to ask questions about this too, if anything is unclear!

**Comment by faucomte97** [comment]
Hi @Ridwanah, I've just reviewed your PR. Let me know if anything doesn't make sense 🙂

**Comment by Ridwanah** [comment]
> Hi, I have been working on making these changes. I am been struggling with the last change because my migrations are not being applied. I changed the default value for commands for the level model to the full list of commands, and when I do makemigrations and migrate, the change is reflected in the migrations folder, and using showmigrations, but when I test the website, it uses the previous default value. I have tested this with different values and I have tried editing the migrations file. I am going to try again to see if I can get this working.

Edit: I have solved this issue.

**Review by faucomte97 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1680#-:-O2yrA5EE36en1abt_Hd:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @Ridwanah)

**Review by faucomte97 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1680)* status: all files reviewed, 1 unresolved discussion (waiting on @Ridwanah)

___
*[`game/serializers.py` line 87 at r2](https://reviewable.io/reviews/ocadotechnology/rapid-router/1680#-O2Zv3s774rAV8cTjsKq:-O2yuHUS7IkkXM4CXPn4:bru0v4i) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/5cab8b0d5183edb45e183ec2efe7ebfbbcbece77/game/serializers.py#L87)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Remove the extra whitespaces you have in this line
</blockquote></details>

Spaces are still there

**Comment by faucomte97** [comment]
Hi @Ridwanah, your code is almost ready to be merged in, just need to remove a few more extra whitespaces 🙂

**Comment by Ridwanah** [comment]
I have now removed the extra whitespace.

**Review by faucomte97 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1680#-:-O31lk_S76AdnRHuKe7J:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Ridwanah)

**Comment by Ridwanah** [comment]
> :lgtm:
> 
> > Reviewed 1 of 1 files at r5, all commit messages.
> > _[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1680#-:-O31lk_S76AdnRHuKe7J:bnfp4nl)_ status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Ridwanah)

Thank you for the review and approval. Is there anything left for me to do as I don't have the permissions to merge this PR myself?

**Comment by faucomte97** [comment]
Hi @Ridwanah, no that's it, you've completed the task!
I will now go ahead and merge in your pull request. Your change will be deployed to our staging environment in the next few minutes, and once we've manually tested it on staging we will release it to our live website!

Well done! We will be adding your username to our [Wall of Fame](https://docs.codeforlife.education/wall-of-fame) too!

**Pull request merged**
