### PR TITLE
feat: make scenery decor draggable

### PR DESCRIPTION
**Pull request by evemartin**
This change is [Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1634)

### CODE REVIEW

**Review by faucomte97 — DISMISSED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1634)* status: all files reviewed, 3 unresolved discussions (waiting on @evemartin)

___
*[`game/static/game/js/level_editor.js` line 11 at r1](https://reviewable.io/reviews/ocadotechnology/rapid-router/1634#-NzYW02q6gIPsP9ocXSq:-NzYW02r1l1E7j241JKL:bo8fcp6) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/0f7e3f4101f5cae97b21226c4383f927820e5d2c/game/static/game/js/level_editor.js#L11)):*
> ```JavaScript
>     /*************/
> 
>     var TAB_PANE_WIDTH = 500;
> ```

when creating new variables or constants, please use either `let` or `const`.
We want to stop using `var` anywhere we can - ideally we update the old `var`s in the code throughout as we edit the code but for new code we definitely want to use `let` or `const`.

Let me know if you're not sure what the difference is between `let` and `const` and when you should use which.
___
*[`game/static/game/js/level_editor.js` line 1530 at r1](https://reviewable.io/reviews/ocadotechnology/rapid-router/1634#-NzYWN0G8x2EI3iPu-fI:-NzYWN0G8x2EI3iPu-fJ:b-2r5qo9) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/0f7e3f4101f5cae97b21226c4383f927820e5d2c/game/static/game/js/level_editor.js#L1530)):*
> ```JavaScript
>         dragged_decor.parent = this.parentElement;
> 
>         var clone = $(this).clone(true);
> ```

Please update `var`s in this function as well :slightly_smiling_face: 
___
*[`game/static/game/js/level_editor.js` line 1543 at r1](https://reviewable.io/reviews/ocadotechnology/rapid-router/1634#-NzYX3Qv5O-2ZhlcBCjL:-NzYX3Qv5O-2ZhlcBCjM:b3qt5k4) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/0f7e3f4101f5cae97b21226c4383f927820e5d2c/game/static/game/js/level_editor.js#L1543)):*
> ```JavaScript
>                         && (e.pageY + paper.scrollTop() + dragged_decor.height / 2) <= (PAPER_HEIGHT + PAPER_PADDING) 
>                         && (e.pageX + paper.scrollLeft() + dragged_decor.width / 2) <= (TAB_PANE_WIDTH + PAPER_WIDTH + PAPER_PADDING)
>                     ) {
> ```

At a glance I imagine that this is a condition that checks that you are in fact dropping the decor element within the bounds of the level grid so the element can be added to the level.

But it looks like a pretty complex check so could you add a comment to explain it please :slightly_smiling_face: 



_Code quote:_
```JavaScript
                if (e.pageX >= (TAB_PANE_WIDTH + PAPER_PADDING)
                        && (e.pageY + paper.scrollTop() + dragged_decor.height / 2) <= (PAPER_HEIGHT + PAPER_PADDING)
                        && (e.pageX + paper.scrollLeft() + dragged_decor.width / 2) <= (TAB_PANE_WIDTH + PAPER_WIDTH + PAPER_PADDING)
                    ) {
```

**Review by faucomte97 — CHANGES_REQUESTED** [review]
changes

> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1634#-:-NzYXviVCDx7EGFfWVgw:b-n9tkgy)* status: all files reviewed, 3 unresolved discussions (waiting on @evemartin)

**Review by evemartin — COMMENTED** [review]
Thank you for the comments, I have made some changes!

> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1634#-:-NzYnbE_423VT2Cy5wcE:b-7s9a22)* status: 3 of 4 files reviewed, 3 unresolved discussions (waiting on @faucomte97)

___
*[`game/static/game/js/level_editor.js` line 11 at r1](https://reviewable.io/reviews/ocadotechnology/rapid-router/1634#-NzYW02q6gIPsP9ocXSq:-NzYnNAo59uJBrMJeC-p:bc8rtgc) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/0f7e3f4101f5cae97b21226c4383f927820e5d2c/game/static/game/js/level_editor.js#L11)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

when creating new variables or constants, please use either `let` or `const`.
We want to stop using `var` anywhere we can - ideally we update the old `var`s in the code throughout as we edit the code but for new code we definitely want to use `let` or `const`.

Let me know if you're not sure what the difference is between `let` and `const` and when you should use which.
</blockquote></details>

I've changed all the vars here and in the other function you commented on! If there are any changes you disagree with just let me know :)
___
*[`game/static/game/js/level_editor.js` line 1530 at r1](https://reviewable.io/reviews/ocadotechnology/rapid-router/1634#-NzYWN0G8x2EI3iPu-fI:-NzYnWTq5aKvQBGZsg86:bx566qv) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/0f7e3f4101f5cae97b21226c4383f927820e5d2c/game/static/game/js/level_editor.js#L1530)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Please update `var`s in this function as well :slightly_smiling_face:
</blockquote></details>

See my previous response :)
___
*[`game/static/game/js/level_editor.js` line 1543 at r1](https://reviewable.io/reviews/ocadotechnology/rapid-router/1634#-NzYX3Qv5O-2ZhlcBCjL:-NzYnZyK-MVaJaEtOhse:bs3mhd3) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/0f7e3f4101f5cae97b21226c4383f927820e5d2c/game/static/game/js/level_editor.js#L1543)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

At a glance I imagine that this is a condition that checks that you are in fact dropping the decor element within the bounds of the level grid so the element can be added to the level.

But it looks like a pretty complex check so could you add a comment to explain it please :slightly_smiling_face:
</blockquote></details>

Comment added!

**Review by faucomte97 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1634#-:-NzYrFCt19jxtBPM3cQg:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @evemartin)

**Pull request merged**
