### PR TITLE
fix: add snow and city solar panel graphics

### PR DESCRIPTION
**Pull request by evemartin**
This change is [Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1716)

### CODE REVIEW

**Review by faucomte97 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1716)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @evemartin)

___
*[`game/static/game/image/decor/city/solar_panel.svg` line 1 at r1](https://reviewable.io/reviews/ocadotechnology/rapid-router/1716#-O5sZAX-CVo4fJk_Czvg:-O5sZAX-CVo4fJk_Czvh:bayrvd3) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/f6be05601ef93c2533e625f5a71fa9f778cdd4ed/game/static/game/image/decor/city/solar_panel.svg#L1)):*
> ```SVG
> <?xml version="1.0" encoding="UTF-8"?>
> ```

As far as I can tell, this image (and the other one) are also needed in the `static/game/raphael-image/decor/` directory - right now they don't appear in the level editor properly.

**Review by evemartin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1716)* status: 0 of 9 files reviewed, 1 unresolved discussion (waiting on @faucomte97)

___
*[`game/static/game/image/decor/city/solar_panel.svg` line 1 at r1](https://reviewable.io/reviews/ocadotechnology/rapid-router/1716#-O5sZAX-CVo4fJk_Czvg:-O5wKh6N9gB2FBw68uim:b-9ptw0q) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/f6be05601ef93c2533e625f5a71fa9f778cdd4ed/game/static/game/image/decor/city/solar_panel.svg#L1)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

As far as I can tell, this image (and the other one) are also needed in the `static/game/raphael-image/decor/` directory - right now they don't appear in the level editor properly.
</blockquote></details>

I've now uploaded the images to all the places where the original solar panel image appears and confirmed locally that they show up properly!

**Review by faucomte97 — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r1, 4 of 4 files at r2, 174 of 174 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1716#-:-O5wRyqU955wNLDg8hh0:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @evemartin)

**Review by faucomte97 — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1716)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @evemartin)

**Pull request merged**
