### PR TITLE
feat: Rapid router 1732

### PR DESCRIPTION
**Pull request by SKairinos**
This change is [Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1737)

### CODE REVIEW

**Review by faucomte97 — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1737)* status: all files reviewed, 4 unresolved discussions (waiting on @SKairinos)

___
*[`game/static/game/js/blockly/msg/js/bg.js` line 464 at r1](https://reviewable.io/reviews/ocadotechnology/rapid-router/1737#-O8CGPX77mKZW9eMWD-2:-O8CGPX77mKZW9eMWD-3:bwwgc35) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/11761d99d01d557234d1e3c8e13bacfa30b5a336/game/static/game/js/blockly/msg/js/bg.js#L464)):*
> ```JavaScript
> Blockly.Msg["AT_DESTINATION_TITLE"] = "На адреса";
> Blockly.Msg["COW_CROSSING_TITLE"] = "Крави";
> Blockly.Msg["PIGEON_CROSSING_TITLE"] = "pigeons"; // untranslated
> ```

translate using Google Translate pls
___
*[`game/static/game/js/blockly/msg/js/pl.js` line 464 at r1](https://reviewable.io/reviews/ocadotechnology/rapid-router/1737#-O8CGgh-6qK60Z95CMBN:-O8CGgh-6qK60Z95CMBO:bwwgc35) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/11761d99d01d557234d1e3c8e13bacfa30b5a336/game/static/game/js/blockly/msg/js/pl.js#L464)):*
> ```JavaScript
> Blockly.Msg["AT_DESTINATION_TITLE"] = "U celu";
> Blockly.Msg["COW_CROSSING_TITLE"] = "Krowy";
> Blockly.Msg["PIGEON_CROSSING_TITLE"] = "pigeons"; // untranslated
> ```

translate using Google Translate pls
___
*[`game/static/game/js/blockly/msg/js/pt-br.js` line 464 at r1](https://reviewable.io/reviews/ocadotechnology/rapid-router/1737#-O8CGiW44dOyw7dlhJzm:-O8CGiW44dOyw7dlhJzn:bwwgc35) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/11761d99d01d557234d1e3c8e13bacfa30b5a336/game/static/game/js/blockly/msg/js/pt-br.js#L464)):*
> ```JavaScript
> Blockly.Msg["AT_DESTINATION_TITLE"] = "No destino";
> Blockly.Msg["COW_CROSSING_TITLE"] = "Vacas";
> Blockly.Msg["PIGEON_CROSSING_TITLE"] = "pigeons"; // untranslated
> ```

translate using Google Translate pls
___
*[`game/static/game/js/blockly/msg/js/ru.js` line 464 at r1](https://reviewable.io/reviews/ocadotechnology/rapid-router/1737#-O8CH5s7-imDd6Ltnm98:-O8CH5s7-imDd6Ltnm99:bwwgc35) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/11761d99d01d557234d1e3c8e13bacfa30b5a336/game/static/game/js/blockly/msg/js/ru.js#L464)):*
> ```JavaScript
> Blockly.Msg["AT_DESTINATION_TITLE"] = "В пункте назначения";
> Blockly.Msg["COW_CROSSING_TITLE"] = "Коровы";
> Blockly.Msg["PIGEON_CROSSING_TITLE"] = "pigeons"; // untranslated
> ```

translate using Google Translate pls

**Review by SKairinos — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1737)* status: all files reviewed, 4 unresolved discussions (waiting on @faucomte97)

___
*[`game/static/game/js/blockly/msg/js/bg.js` line 464 at r1](https://reviewable.io/reviews/ocadotechnology/rapid-router/1737#-O8CGPX77mKZW9eMWD-2:-O8H1lSmB-Cn_NYQItvr:b-896fix) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/11761d99d01d557234d1e3c8e13bacfa30b5a336/game/static/game/js/blockly/msg/js/bg.js#L464)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

translate using Google Translate pls
</blockquote></details>

Done.
___
*[`game/static/game/js/blockly/msg/js/pl.js` line 464 at r1](https://reviewable.io/reviews/ocadotechnology/rapid-router/1737#-O8CGgh-6qK60Z95CMBN:-O8H1uso5xXCEcZj-eUO:b-896fix) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/11761d99d01d557234d1e3c8e13bacfa30b5a336/game/static/game/js/blockly/msg/js/pl.js#L464)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

translate using Google Translate pls
</blockquote></details>

Done.
___
*[`game/static/game/js/blockly/msg/js/pt-br.js` line 464 at r1](https://reviewable.io/reviews/ocadotechnology/rapid-router/1737#-O8CGiW44dOyw7dlhJzm:-O8H2CTD6PpAo0_nZhYh:b-896fix) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/11761d99d01d557234d1e3c8e13bacfa30b5a336/game/static/game/js/blockly/msg/js/pt-br.js#L464)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

translate using Google Translate pls
</blockquote></details>

Done.
___
*[`game/static/game/js/blockly/msg/js/ru.js` line 464 at r1](https://reviewable.io/reviews/ocadotechnology/rapid-router/1737#-O8CH5s7-imDd6Ltnm98:-O8H2Pgq1M-o_oTDwQxP:b-896fix) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/11761d99d01d557234d1e3c8e13bacfa30b5a336/game/static/game/js/blockly/msg/js/ru.js#L464)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

translate using Google Translate pls
</blockquote></details>

Done.

**Review by faucomte97 — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1737)* status: all files reviewed, 4 unresolved discussions (waiting on @SKairinos)

___
*[`game/static/game/js/blockly/msg/js/bg.js` line 464 at r1](https://reviewable.io/reviews/ocadotechnology/rapid-router/1737#-O8CGPX77mKZW9eMWD-2:-O8H9mk0EI_oWuumo999:b-omid6n) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/11761d99d01d557234d1e3c8e13bacfa30b5a336/game/static/game/js/blockly/msg/js/bg.js#L464)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Very pedantic I know but can you capitalise the translations for pigeons? so it's consistent with the other blocks (especially the cow block)

**Review by faucomte97 — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1737#-:-O8HJtAO3u2y5bDEbQJ_:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @SKairinos)

**Pull request merged**
