### PR TITLE
feat: add pigeon

### PR DESCRIPTION
**Pull request by evemartin**
This change is [Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1712)

### CODE REVIEW

**Review by faucomte97 — CHANGES_REQUESTED** [review]
> Reviewed 11 of 11 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1712)* status: all files reviewed, 3 unresolved discussions (waiting on @evemartin)

*[a discussion](https://reviewable.io/reviews/ocadotechnology/rapid-router/1712#-O5nNfKA9rMnJJ4ey2r4:-O5nNfKA9rMnJJ4ey2r5:b6ohak9) (no related file):*
The `if cows` block is still the same, it needs to be dynamic too ideally, otherwise we can just have it say `if animal` which is similar to what the Python code has anyway

___
___
*[`game/static/game/js/animation.js` line 44 at r2](https://reviewable.io/reviews/ocadotechnology/rapid-router/1712#-O5nMvbn6vkWgE8AN5Pi:-O5nMvbn6vkWgE8AN5Pj:byp18fd) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/aa55222c126f3b7f3195d1822a249e339c982cfb/game/static/game/js/animation.js#L44)):*
> ```JavaScript
> 	for (let i = 0 ; i < cows.length ; i++){
> 		let cow = cows[i];
> 		console.log(cow.type);
> ```

Remove
___
*[`game/static/game/js/cow.js` line 26 at r2](https://reviewable.io/reviews/ocadotechnology/rapid-router/1712#-O5nN3sW58Af0qajKgwT:-O5nN3sW58Af0qajKgwU:b1psubu) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/aa55222c126f3b7f3195d1822a249e339c982cfb/game/static/game/js/cow.js#L26)):*
> ```JavaScript
> };
> 
> ocargo.Cow.prototype.queueLeaveAnimation = function(model, node) {
> ```

How much time do you reckon you'd need to rename the `Cow` object to `Animal`? :confused: Is it used in a lot of places / would it cause a lot of issues?

**Comment by SKairinos** [comment]
[Screencast from 03-09-24 10:02:11.webm](https://github.com/user-attachments/assets/73a2d9da-9a6c-40d3-9b89-6113e35dbf58)
Pigeon rotates if you re-place it

**Comment by SKairinos** [comment]
placing a pigeon on the map does not auto-insert the pigeon block into the list of available blocks. It shouldn't be possible to have a pigeon without the pigeon block.
image

**Comment by SKairinos** [comment]
What is the django migr button?
image

**Comment by SKairinos** [comment]
Still says cows in the level editor
image

**Comment by lauracumming** [comment]
Thanks Stefan, some of these will be separate tasks. Elements should all rotate if clicked on as some roads will be vertical and some horizontal - is that what you mean?

**Review by evemartin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1712)* status: 9 of 19 files reviewed, 3 unresolved discussions (waiting on @faucomte97 and @SKairinos)

*[a discussion](https://reviewable.io/reviews/ocadotechnology/rapid-router/1712#-O5nNfKA9rMnJJ4ey2r4:-O5sGlNE4YYrzpasWz5K:bawtgl8) (no related file):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

The `if cows` block is still the same, it needs to be dynamic too ideally, otherwise we can just have it say `if animal` which is similar to what the Python code has anyway
</blockquote></details>

Thank you both for the reviews, in addition to the changes I've mentioned in other comments I've also changed the `cows` block to dynamically update to `pigeons`! @SKairinos I've had a look at the issues you pointed out and since they apply to cows as well as pigeons I think it would make sense for them to be done in their own tasks. 

___
___
*[`game/static/game/js/cow.js` line 26 at r2](https://reviewable.io/reviews/ocadotechnology/rapid-router/1712#-O5nN3sW58Af0qajKgwT:-O5sGIQd7E7WcYG6f014:b294n9m) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/aa55222c126f3b7f3195d1822a249e339c982cfb/game/static/game/js/cow.js#L26)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

How much time do you reckon you'd need to rename the `Cow` object to `Animal`? :confused: Is it used in a lot of places / would it cause a lot of issues?
</blockquote></details>

I think it would probably take a little while just to make sure I had changed it everywhere but renaming just the object would be more doable than renaming the object plus all the associated variables - what are your thoughts on doing one of these two things?
___
*[`game/static/game/js/animation.js` line 44 at r2](https://reviewable.io/reviews/ocadotechnology/rapid-router/1712#-O5nMvbn6vkWgE8AN5Pi:-O5sGjtyEXE66IarO-rP:bss4a1y) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/aa55222c126f3b7f3195d1822a249e339c982cfb/game/static/game/js/animation.js#L44)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Remove
</blockquote></details>

Removed!

**Comment by evemartin** [comment]
A note about the translations: I have used google translate to add translations for the word "pigeons" for the languages we have so far, since I've heard it's pretty reliable for single words. I have also added the word "pigeons" to the translations doc so that future volunteers will know, but I haven't pinged anyone asking for them to add this word to their translation. I wanted to get your opinions about this - for the translated languages that are currently verified but need this one more word, should I

1. send out a mass message in the relevant channels asking people to translate this one word
2. message people who worked on the translations specifically to translate this one word (based on doc edit history)
3. use Google Translate just for the word "pigeons"

**Review by faucomte97 — APPROVED** [review]
:lgtm:

> Reviewed 10 of 10 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1712#-:-O5sYJcp36LJvOqI1JQv:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @evemartin)

**Comment by evemartin** [comment]
To address Stefan's comments, I have made/found the following tasks:

- users should not be allowed to place invalid pigeons(/cows/traffic lights): Task #1669 
- placing pigeon(/cow/traffic light) doesn't automatically include the pigeon(/cow/traffic light) block: Task #1719 
- when a pigeon/cow is re-dragged right after being dragged to the grid, its orientation changes. Also, when a pigeon/cow is clicked right after being dragged to the grid, its orientation changes and it jumps to 0,0: Task #1717 and #1718 
- get rid of the django migration button: Task #1720

**Review by faucomte97 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1712#-:-O5w_0e1BU44U-11_wTv:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @evemartin)

**Pull request merged**
