### PR TITLE
fix: fixed the start block appearing in the bin 

### PR DESCRIPTION
**Pull request by KamilPawel**
## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have linked this PR to a Zenhub Issue.

---
This change is [Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1328)

### CODE REVIEW

**Review by faucomte97 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1328)* status: all files reviewed, 2 unresolved discussions (waiting on @KamilPawel)

___
*[game/static/game/js/blocklyControl.js, line 78 at r2](https://reviewable.io/reviews/ocadotechnology/rapid-router/1328#-N-bYxfb8N66HVkQDgPY:-N-bYxfc15FdhU70-ehQ:b-gtf8sx) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/945f195bc487bfb73ef2e5e7340dc7abb842bb75/game/static/game/js/blocklyControl.js#L78)):*
> ```JavaScript
>     // Therefore a simple check is preformed to see if the level
>     // has a start button, if not then create a start button
> ```

Can you remove that empty line please?
___
*[game/static/game/js/blocklyControl.js, line 80 at r2](https://reviewable.io/reviews/ocadotechnology/rapid-router/1328#-N-bYu6f5dItXGl-NapL:-N-bYu6g723Dw6Cu05RM:b2r0kzm) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/945f195bc487bfb73ef2e5e7340dc7abb842bb75/game/static/game/js/blocklyControl.js#L80)):*
> ```JavaScript
> 
>     if (!wasGameStarted(allBlocks)) {
>         var startBlock = this.createBlock('start');
> ```

`let` please :stuck_out_tongue:

**Review by KamilPawel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1328)* status: all files reviewed, 2 unresolved discussions (waiting on @faucomte97)

___
*[game/static/game/js/blocklyControl.js, line 78 at r2](https://reviewable.io/reviews/ocadotechnology/rapid-router/1328#-N-bYxfb8N66HVkQDgPY:-N-ba_j10-mNEO8HPdwU:b-896fix) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/945f195bc487bfb73ef2e5e7340dc7abb842bb75/game/static/game/js/blocklyControl.js#L78)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Can you remove that empty line please?
</blockquote></details>

Done.
___
*[game/static/game/js/blocklyControl.js, line 80 at r2](https://reviewable.io/reviews/ocadotechnology/rapid-router/1328#-N-bYu6f5dItXGl-NapL:-N-ba_uP1oMkYEumSRnI:b-896fix) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/945f195bc487bfb73ef2e5e7340dc7abb842bb75/game/static/game/js/blocklyControl.js#L80)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

`let` please :stuck_out_tongue: 
</blockquote></details>

Done.

**Review by faucomte97 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1328)* status: all files reviewed, 1 unresolved discussion (waiting on @KamilPawel)

___
*[game/static/game/js/blocklyControl.js, line 78 at r2](https://reviewable.io/reviews/ocadotechnology/rapid-router/1328#-N-bYxfb8N66HVkQDgPY:-N-bjeGm6I38DtrNdepw:bn7g4gd) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/945f195bc487bfb73ef2e5e7340dc7abb842bb75/game/static/game/js/blocklyControl.js#L78)):*
<details><summary><i>Previously, KamilPawel wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I meant the one after the comment and before the function :stuck_out_tongue:

**Review by KamilPawel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1328)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @faucomte97)

___
*[game/static/game/js/blocklyControl.js, line 78 at r2](https://reviewable.io/reviews/ocadotechnology/rapid-router/1328#-N-bYxfb8N66HVkQDgPY:-N-bk3tvDlaRSeAUT_ou:b-x9ba83) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/945f195bc487bfb73ef2e5e7340dc7abb842bb75/game/static/game/js/blocklyControl.js#L78)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

I meant the one after the comment and before the function :stuck_out_tongue: 
</blockquote></details>

Like this?

**Review by faucomte97 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1328)* status: all files reviewed, 1 unresolved discussion (waiting on @KamilPawel)

___
*[game/static/game/js/blocklyControl.js, line 78 at r2](https://reviewable.io/reviews/ocadotechnology/rapid-router/1328#-N-bYxfb8N66HVkQDgPY:-N-blRKZ2YHhmQypn59k:b-x0p0tw) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/945f195bc487bfb73ef2e5e7340dc7abb842bb75/game/static/game/js/blocklyControl.js#L78)):*
<details><summary><i>Previously, KamilPawel wrote…</i></summary><blockquote>

Like this?
</blockquote></details>

Yes...
___
*[game/static/game/js/blocklyControl.js, line 65 at r3](https://reviewable.io/reviews/ocadotechnology/rapid-router/1328#-N-blTNi4X1UPoXBgiPb:-N-blTNi4X1UPoXBgiPc:b-gm9fv) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/ac5d0e77741e049d7525bbc6c0ada11c4d44460c/game/static/game/js/blocklyControl.js#L65)):*
> ```JavaScript
>     return gameStarted;
> }
> ```

But why did you remove this one? :stuck_out_tongue:

**Review by KamilPawel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1328)* status: all files reviewed, 1 unresolved discussion (waiting on @faucomte97)

___
*[game/static/game/js/blocklyControl.js, line 65 at r3](https://reviewable.io/reviews/ocadotechnology/rapid-router/1328#-N-blTNi4X1UPoXBgiPb:-N-c9XyM0ke3MvKLW1bR:b-896fix) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/ac5d0e77741e049d7525bbc6c0ada11c4d44460c/game/static/game/js/blocklyControl.js#L65)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

But why did you remove this one? :stuck_out_tongue: 
</blockquote></details>

Done.

**Review by faucomte97 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1328#-:-N-cEhDk9XAAMYAF8w4M:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @KamilPawel)

**Pull request merged**
