### PR TITLE
fix: rename episodes and levels

### PR DESCRIPTION
**Pull request by SKairinos**
This change is [Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1581)

### CODE REVIEW

**Review by faucomte97 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1581)* status: 2 of 3 files reviewed, 11 unresolved discussions (waiting on @SKairinos)

___
*[`game/messages.py` line 1229 at r1](https://reviewable.io/reviews/ocadotechnology/rapid-router/1581#-NqbpMPVElP40TSquYR8:-NqbpMPVElP40TSquYR9:b-smlez4) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/5c2b81320e1acd46dd5fdb274babb61e6c8f86c3/game/messages.py#L1229)):*
> ```Python
> 
> def title_level52():
>     return "A bit more Tricky"
> ```

lowercase tricky please
___
*[`game/messages.py` line 1818 at r1](https://reviewable.io/reviews/ocadotechnology/rapid-router/1581#-NqbpuZRERiNu2CE606R:-NqbpuZS4iLCqopz34Ta:b-vmvhsd) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/5c2b81320e1acd46dd5fdb274babb61e6c8f86c3/game/messages.py#L1818)):*
> ```Python
> 
> def title_level84():
>     return "Repeat and watch"
> ```

Maybe "Repeat" should be bold
___
*[`game/messages.py` line 1835 at r1](https://reviewable.io/reviews/ocadotechnology/rapid-router/1581#-Nqbpive-PRcdmgJgsAD:-Nqbpive-PRcdmgJgsAE:bpfv7mx) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/5c2b81320e1acd46dd5fdb274babb61e6c8f86c3/game/messages.py#L1835)):*
> ```Python
> 
> def title_level85():
>     return "Looks easy but use repeat until and see what happens?"
> ```

"repeat until" should be bold
___
*[`game/messages.py` line 1853 at r1](https://reviewable.io/reviews/ocadotechnology/rapid-router/1581#-NqbpnOR2LjM6umpFm9N:-NqbpnOR2LjM6umpFm9O:b-kz9byr) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/5c2b81320e1acd46dd5fdb274babb61e6c8f86c3/game/messages.py#L1853)):*
> ```Python
> 
> def title_level86():
>     return "See what the if blocks looks like in Python"
> ```

"if" should be bold
___
*[`game/messages.py` line 1869 at r1](https://reviewable.io/reviews/ocadotechnology/rapid-router/1581#-NqbppayECoFAYq_WOGv:-NqbppayECoFAYq_WOGw:br05rq2) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/5c2b81320e1acd46dd5fdb274babb61e6c8f86c3/game/messages.py#L1869)):*
> ```Python
> 
> def title_level87():
>     return "Don't forget to use else if"
> ```

"else if" should be bold
___
*[`game/messages.py` line 2477 at r1](https://reviewable.io/reviews/ocadotechnology/rapid-router/1581#-NqbqE_T3O-j88eOGV9d:-NqbqE_T3O-j88eOGV9e:b-9kwa9a) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/5c2b81320e1acd46dd5fdb274babb61e6c8f86c3/game/messages.py#L2477)):*
> ```Python
>     hint_level117,
> ) = (
>     lambda: "Wiggle while you work",
> ```

Should "while" be bold?
___
*[`game/messages.py` line 2890 at r1](https://reviewable.io/reviews/ocadotechnology/rapid-router/1581#-Nqbo2hK3JwSGV23yFOP:-Nqbo2hK3JwSGV23yFOQ:b-ilna4b) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/5c2b81320e1acd46dd5fdb274babb61e6c8f86c3/game/messages.py#L2890)):*
> ```Python
>         11: "Python",
>         12: "Counted Loops Using While",
>         13: "Indeterminate While loops - coming soon",
> ```

Shouldn't "loops" be capitalised if we're following title case?
___
*[`game/migrations/0087_rename_episodes.py` line 0 at r1](https://reviewable.io/reviews/ocadotechnology/rapid-router/1581#-Nqbls5Z62_NQem0CGKx:-Nqbls5_2iARAZwMFMl5:b-1cgo0n) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/5c2b81320e1acd46dd5fdb274babb61e6c8f86c3/game/migrations/0087_rename_episodes.py#L0)):*
1. Merge master into this branch
2. Update this migration to be migration 0088 (0087 already exists)
___
*[`game/migrations/0087_rename_episodes.py` line 0 at r1](https://reviewable.io/reviews/ocadotechnology/rapid-router/1581#-NqbmPaz6sYEqxYwFgfu:-NqbmPaz6sYEqxYwFgfv:bw8ffy0) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/5c2b81320e1acd46dd5fdb274babb61e6c8f86c3/game/migrations/0087_rename_episodes.py#L0)):*
Run Black on this file
___
*[`game/migrations/0087_rename_episodes.py` line 14 at r1](https://reviewable.io/reviews/ocadotechnology/rapid-router/1581#-NqbnzB88LgF6blOGKoh:-NqbnzB88LgF6blOGKoi:b-ilna4b) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/5c2b81320e1acd46dd5fdb274babb61e6c8f86c3/game/migrations/0087_rename_episodes.py#L14)):*
> ```Python
>     
>     update_episode_name(pk=12, name="Counted Loops Using While")
>     update_episode_name(pk=13, name="Indeterminate While loops - coming soon")
> ```

Shouldn't "loops" be capitalised if we're following title case?
___
*[`game/migrations/0087_rename_episodes.py` line 29 at r1](https://reviewable.io/reviews/ocadotechnology/rapid-router/1581#-NqbmtvzBdg5ihK3ouDY:-NqbmtvzBdg5ihK3ouDZ:brjqht5) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/5c2b81320e1acd46dd5fdb274babb61e6c8f86c3/game/migrations/0087_rename_episodes.py#L29)):*
> ```Python
> 
> class Migration(migrations.Migration):
>     dependencies = [("game", "0086_loop_levels")]
> ```

Update this to the name of migration 0087

**Review by faucomte97 — COMMENTED** [review]
> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1581)* status: all files reviewed, 11 unresolved discussions (waiting on @SKairinos)

**Review by SKairinos — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1581)* status: all files reviewed, 11 unresolved discussions (waiting on @faucomte97)

___
*[`game/messages.py` line 1229 at r1](https://reviewable.io/reviews/ocadotechnology/rapid-router/1581#-NqbpMPVElP40TSquYR8:-NqbtQ78DTLfNn7eytw2:b-896fix) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/5c2b81320e1acd46dd5fdb274babb61e6c8f86c3/game/messages.py#L1229)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

lowercase tricky please
</blockquote></details>

Done.
___
*[`game/messages.py` line 1818 at r1](https://reviewable.io/reviews/ocadotechnology/rapid-router/1581#-NqbpuZRERiNu2CE606R:-NqbtWy2BBRH65PKNA94:b-896fix) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/5c2b81320e1acd46dd5fdb274babb61e6c8f86c3/game/messages.py#L1818)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Maybe "Repeat" should be bold
</blockquote></details>

Done.
___
*[`game/messages.py` line 1835 at r1](https://reviewable.io/reviews/ocadotechnology/rapid-router/1581#-Nqbpive-PRcdmgJgsAD:-NqbtaEu3QumKi5_s9Dg:b-896fix) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/5c2b81320e1acd46dd5fdb274babb61e6c8f86c3/game/messages.py#L1835)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

"repeat until" should be bold
</blockquote></details>

Done.
___
*[`game/messages.py` line 1853 at r1](https://reviewable.io/reviews/ocadotechnology/rapid-router/1581#-NqbpnOR2LjM6umpFm9N:-Nqbte8Q1jSMEFt6vy36:b-896fix) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/5c2b81320e1acd46dd5fdb274babb61e6c8f86c3/game/messages.py#L1853)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

"if" should be bold
</blockquote></details>

Done.
___
*[`game/messages.py` line 1869 at r1](https://reviewable.io/reviews/ocadotechnology/rapid-router/1581#-NqbppayECoFAYq_WOGv:-NqbtkZPDnynvG9Z0V1m:b-896fix) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/5c2b81320e1acd46dd5fdb274babb61e6c8f86c3/game/messages.py#L1869)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

"else if" should be bold
</blockquote></details>

Done.
___
*[`game/messages.py` line 2477 at r1](https://reviewable.io/reviews/ocadotechnology/rapid-router/1581#-NqbqE_T3O-j88eOGV9d:-Nqbu1HAESNc9ZEuDxDG:b-896fix) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/5c2b81320e1acd46dd5fdb274babb61e6c8f86c3/game/messages.py#L2477)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Should "while" be bold?
</blockquote></details>

Done.
___
*[`game/messages.py` line 2890 at r1](https://reviewable.io/reviews/ocadotechnology/rapid-router/1581#-Nqbo2hK3JwSGV23yFOP:-Nqbu6s_1B_3ji15O3dt:b-896fix) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/5c2b81320e1acd46dd5fdb274babb61e6c8f86c3/game/messages.py#L2890)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Shouldn't "loops" be capitalised if we're following title case?
</blockquote></details>

Done.
___
*[`game/migrations/0087_rename_episodes.py` line 14 at r1](https://reviewable.io/reviews/ocadotechnology/rapid-router/1581#-NqbnzB88LgF6blOGKoh:-NqbuIEz7cz32HhebzN3:b-896fix) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/5c2b81320e1acd46dd5fdb274babb61e6c8f86c3/game/migrations/0087_rename_episodes.py#L14)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Shouldn't "loops" be capitalised if we're following title case?
</blockquote></details>

Done.
___
*[`game/migrations/0087_rename_episodes.py` line 29 at r1](https://reviewable.io/reviews/ocadotechnology/rapid-router/1581#-NqbmtvzBdg5ihK3ouDY:-NqbuJck5q6--9I1FElY:b-896fix) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/5c2b81320e1acd46dd5fdb274babb61e6c8f86c3/game/migrations/0087_rename_episodes.py#L29)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Update this to the name of migration 0087
</blockquote></details>

Done.

**Review by faucomte97 — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1581)* status: all files reviewed, 1 unresolved discussion (waiting on @SKairinos)

**Review by faucomte97 — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1581)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @SKairinos)

**Review by faucomte97 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1581#-:-Nqbw59T6xqL6yQc0rGi:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @SKairinos)

**Review by SKairinos — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1581)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @SKairinos)

___
*[`game/migrations/0087_rename_episodes.py` line  at r1](https://reviewable.io/reviews/ocadotechnology/rapid-router/1581#-Nqbls5Z62_NQem0CGKx:-NqbupQO3RECYoOeT0WD:b-896fix) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/5c2b81320e1acd46dd5fdb274babb61e6c8f86c3/game/migrations/0087_rename_episodes.py#L)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

1. Merge master into this branch
2. Update this migration to be migration 0088 (0087 already exists)
</blockquote></details>

Done.
___
*[`game/migrations/0087_rename_episodes.py` line  at r1](https://reviewable.io/reviews/ocadotechnology/rapid-router/1581#-NqbmPaz6sYEqxYwFgfu:-Nqbupii7LHfydDGZDZ2:b-896fix) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/5c2b81320e1acd46dd5fdb274babb61e6c8f86c3/game/migrations/0087_rename_episodes.py#L)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Run Black on this file
</blockquote></details>

Done.

**Review by faucomte97 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1581)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @SKairinos)

**Pull request merged**
