### PR TITLE
MakeTranslationSetupOptional

### PR DESCRIPTION
**Pull request by ChrisMukherjee**
This will allow the game to run without all devs having to install the
libraries required to work on the translation/localisation

### CODE REVIEW

**Comment by piotrrepetowski** [comment]
What's the problem with installing them?

**Comment by ChrisMukherjee** [comment]
@piotrrepetowski The problem is that the dependencies are not all packaged and installed automatically, meaning that anyone working on the project will have to install the missing dependencies manually. The error I received is:
`CommandError:` Can't find msguniq. Make sure you have GNU gettext tools 0.15 or newer installed.`

I also think it's safe to assume that most developers working on Rapid Router will probably not be working on dependencies and therefore shouldn't have to clutter up their machines with these additional libraries.

**Comment by piotrrepetowski** [comment]
Ok, I know what you mean.

Maybe we can provide an option to the run script e.g. --with-translation-tools to achieve what you want more deliberately? What do you think?

**Comment by ChrisMukherjee** [comment]
@piotrrepetowski Good suggestion! That's done now, please have another look. Sorry for the delay by the way; I was on holiday.

**Comment by CelineBoudier** [comment]
Might be good to update the Readme if we add an option :)
Thanks ^^

**Comment by ChrisMukherjee** [comment]
@CelineBoudier Done! Good catch :)

**Pull request merged**
