### PR TITLE
Add missing translations

### PR DESCRIPTION
**Pull request by piotrrepetowski**
Part of #760

### CODE REVIEW

**Comment by CelineBoudier** [comment]
As I was saying on Slack, I ḿ just a bit concerned about the fact that we're having lots of different ways to deal with sentences - having them all in messages.js and messages.py might not be a big requirement anymore since we're using crowdin - but hey...
Any other opinion?

**Comment by mikebryant** [comment]
I'm against trying to move all the strings to some central file (e.g. `messages.py`)
I feel it makes more sense to have the messages be in context in the file they get displayed in. Our translation software is capable of finding them where they're used, and if someone's trying to find where a message is defined we have search locally or in github.
(Or, looking at the generated `.po` file tells you where it got the message from too)

**Comment by CelineBoudier** [comment]
Well we should either have them all in centralised files or have them all in context. So far we are sort of doing a bit of both with is really confusing.
We can definitely try to have them all in context, but so we need to clean the messages.py and messages.js at some point ^^ 
Not a big issue so far though

**Comment by piotrrepetowski** [comment]
I'm also voting for the context option. I think this is more natural for gettext.

My plan is to inline all translations from messages.js to appropriate scripts and remove messages.js. I think we may do similar thing for messages.py but I would wait until we externalize all messages.

**Pull request merged**
