### PR TITLE
feat: add variables, maths and comparison blocks

### PR DESCRIPTION
**Pull request by razvan-pro**
This change is [Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1270)

### CODE REVIEW

**Review by razvan-pro — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1270)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @razvan-pro)

___
*[game/migrations/0074_add_new_blocks.py, line 9 at r1](https://reviewable.io/reviews/ocadotechnology/rapid-router/1270#-MqxVTn5-7dnobwvrbs6:-MqxVTn5-7dnobwvrbs7:b3mty17) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/21eba93d796a23c0df0b59316875030298f137a0/game/migrations/0074_add_new_blocks.py#L9)):*
> ```
>     block2 = Block(type="variables_numeric_set")
>     block3 = Block(type="variables_increment")
> ```

We might remove these 2 :slightly_smiling_face: 
___
*[game/static/game/js/blocklyCompiler.js, line 161 at r1](https://reviewable.io/reviews/ocadotechnology/rapid-router/1270#-MqxVk6g6ncYBh1wmu2E:-MqxVk6g6ncYBh1wmu2F:b-rswali) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/21eba93d796a23c0df0b59316875030298f137a0/game/static/game/js/blocklyCompiler.js#L161)):*
> ```JavaScript
> };
> 
> ocargo.BlocklyCompiler.prototype.createVariableNumeric = function (block) {
> ```

This and the below are probably to be removed as well (and all references)

**Review by faucomte97 — COMMENTED** [review]
> Reviewed 1 of 2 files at r4, 1 of 2 files at r7, 54 of 56 files at r8, 1 of 3 files at r9, 1 of 1 files at r10, 1 of 1 files at r11, 1 of 1 files at r13, 2 of 2 files at r14, 3 of 3 files at r15, all commit messages.
> Dismissed @razvan-pro from 2 discussions.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1270)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @razvan-pro)

**Review by faucomte97 — COMMENTED** [review]
> Reviewed 3 of 4 files at r16, 1 of 1 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1270)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @razvan-pro)

**Review by faucomte97 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r18, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1270#-:-NhyKAA59a-d7xQJi20J:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @razvan-pro)

**Pull request merged**
