### PR TITLE
feat: enable cow crossing condition, and horn action

### LINKED ISSUE #1334: Enabling the cows

### PR DESCRIPTION
**Pull request by sebp999**
## Description
Fixes #1334 #1335 #1843 #952 (partly) 

Add
* Cow crossing condition block
* Horn action, which removes cows from adjacent blocks
* Block ordering for display
* A cow as scenery, which can be positioned on the road.  

Remove
* declare_event block and corresponding block type
* puff up 
* puff down actions

The cows are now not random but set up, like traffic lights.  Horns remove all cows, so puffing up and down to remove brown cows is also gone.  
  
## How Has This Been Tested?

Manually using several scenarios.  Cow collisions are already tested.  The next PR (will be added later) adds a simple level demonstrating cows and the corresponding runthrough test will test it.  

## Checklist:

- [ x ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ x ] I have linked this PR to a ZenHub Issue.

- - -
This change is [Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1376)

### CODE REVIEW

**Review by faucomte97 — CHANGES_REQUESTED** [review]
> Reviewed 7 of 16 files at r1, 10 of 27 files at r2, 16 of 16 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1376)* status: all files reviewed, 12 unresolved discussions (waiting on @sebp999)

___
*[`game/migrations/0077_auto_20221106_1608_data.py` line 1 at r4](https://reviewable.io/reviews/ocadotechnology/rapid-router/1376#-NI7w2l27EbuM4dqUB4S:-NI7w2l27EbuM4dqUB4T:b6319bl) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/05e370c2a45c386df46c461589c2707ca2243264/game/migrations/0077_auto_20221106_1608_data.py#L1)):*
> ```Python
> # Generated by Django 3.2.15 on 2022-11-06 16:08
> ```

Can you rename this migration please to reflect what it does? (although I can see it does a few things so maybe something like `update_blocks`?
___
*[`game/migrations/0077_auto_20221106_1608_data.py` line 37 at r4](https://reviewable.io/reviews/ocadotechnology/rapid-router/1376#-NI7wCse1UonA3noxVqj:-NI7wCse1UonA3noxVqk:br6g36o) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/05e370c2a45c386df46c461589c2707ca2243264/game/migrations/0077_auto_20221106_1608_data.py#L37)):*
> ```Python
>         Block = apps.get_model("game", "Block")
>         Block.objects.filter(type="puff_up").delete()
>         Block.objects.filter(type="declare_event").delete()
> ```

Just using `get` instead of `filter` should work here



_Code quote:_
```Python
        Block.objects.filter(type="puff_up").delete()
        Block.objects.filter(type="declare_event").delete()
```
___
*[`game/migrations/0078_merge_20221127_1108.py` line 1 at r4](https://reviewable.io/reviews/ocadotechnology/rapid-router/1376#-NI7w_T_5hrJtiailrYf:-NI7w_T_5hrJtiailrYg:b-fwhdg9) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/05e370c2a45c386df46c461589c2707ca2243264/game/migrations/0078_merge_20221127_1108.py#L1)):*
> ```Python
> # Generated by Django 3.2.16 on 2022-11-27 11:08
> ```

Do we need this merging of the migrations?
___
*[`game/migrations/0079_alter_block_options.py` line 1 at r4](https://reviewable.io/reviews/ocadotechnology/rapid-router/1376#-NI7widD4b3xqSqZH0RH:-NI7widD4b3xqSqZH0RI:b-vbug5n) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/05e370c2a45c386df46c461589c2707ca2243264/game/migrations/0079_alter_block_options.py#L1)):*
> ```Python
> # Generated by Django 3.2.16 on 2022-11-27 11:09
> ```

If I understand correctly this migration exists because you've edited the `Block` model again after adding the options.
Maybe it would be cleaner to delete migrations 79 and 76, and re-run `makemigrations` which would combine them anyway. And then keep 77 as you have it now. That way we end up with just 2 migrations overall
___
*[`game/static/game/js/map.js` line 50 at r4](https://reviewable.io/reviews/ocadotechnology/rapid-router/1376#-NI7yVGTCy_jFvp1YuKv:-NI7yVGTCy_jFvp1YuKw:bxkh6z3) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/05e370c2a45c386df46c461589c2707ca2243264/game/static/game/js/map.js#L50)):*
> ```JavaScript
>             nextCoordinates.x = currentNode.coordinate.x + 1;
>             if (nextCoordinates.x > 9) { // right-most extremity
>                 return null;  
> ```

extra whitespaces here
___
*[`game/static/game/js/map.js` line 59 at r4](https://reviewable.io/reviews/ocadotechnology/rapid-router/1376#-NI7y_SI4gsD4KWpkifv:-NI7y_SI4gsD4KWpkifw:b-i21izm) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/05e370c2a45c386df46c461589c2707ca2243264/game/static/game/js/map.js#L59)):*
> ```JavaScript
>         }
>     } else { // moving vertically
>         nextCoordinates.x = currentNode.coordinate.x; 
> ```

Extra whitespace here
___
*[`game/static/game/js/model.js` line 106 at r4](https://reviewable.io/reviews/ocadotechnology/rapid-router/1376#-NI7z7HLE7FVKoH0hF2d:-NI7z7HLE7FVKoH0hF2e:b-tzccb2) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/05e370c2a45c386df46c461589c2707ca2243264/game/static/game/js/model.js#L106)):*
> ```JavaScript
>         if (cow) {
>             return true;
>         } 
> ```

Extra whitespace
___
*[`game/static/game/js/model.js` line 439 at r4](https://reviewable.io/reviews/ocadotechnology/rapid-router/1376#-NI7zFAdACxnMJP8h4UU:-NI7zFAdACxnMJP8h4UV:b-615vr3) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/05e370c2a45c386df46c461589c2707ca2243264/game/static/game/js/model.js#L439)):*
> ```JavaScript
>         };
>     });
>     
> ```

Extra whitespaces
___
*[`game/static/game/js/model.js` line 581 at r4](https://reviewable.io/reviews/ocadotechnology/rapid-router/1376#-NI7zGyI0AvwUpXMGGnv:-NI7zGyI0AvwUpXMGGnw:b-615vr3) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/05e370c2a45c386df46c461589c2707ca2243264/game/static/game/js/model.js#L581)):*
> ```JavaScript
>     for (var i = 0; i < this.trafficLights.length; i++) {
>         var light = this.trafficLights[i];
>         
> ```

Extra whitespaces
___
*[`game/static/game/js/model.js` line 610 at r4](https://reviewable.io/reviews/ocadotechnology/rapid-router/1376#-NI7zIeIEqrhlastNb6S:-NI7zIeIEqrhlastNb6T:b-tzccb2) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/05e370c2a45c386df46c461589c2707ca2243264/game/static/game/js/model.js#L610)):*
> ```JavaScript
>                 if (typeof(state) === "string") {
>                     state = [state];
>                 } 
> ```

Extra whitespace
___
*[`game/static/game/js/model.js` line 613 at r4](https://reviewable.io/reviews/ocadotechnology/rapid-router/1376#-NI7zK0l6475JLuEd4LE:-NI7zK0l6475JLuEd4LF:b-tzccb2) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/05e370c2a45c386df46c461589c2707ca2243264/game/static/game/js/model.js#L613)):*
> ```JavaScript
>                 if (state.includes(cow.activeNodes[jsonCoordinate])) {
>                     return cow;
>                 } 
> ```

Extra whitespace
___
*[`game/templates/game/level_editor.html` line 341 at r4](https://reviewable.io/reviews/ocadotechnology/rapid-router/1376#-NI7zSir3imx4Ukw5_MP:-NI7zSir3imx4Ukw5_MQ:b-615vr3) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/05e370c2a45c386df46c461589c2707ca2243264/game/templates/game/level_editor.html#L341)):*
> ```HTML
>                       <td></td>
>                       <td>
>                         
> ```

Extra whitespaces

**Review by sebp999 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1376)* status: 27 of 36 files reviewed, 12 unresolved discussions (waiting on @faucomte97)

___
*[`game/static/game/js/map.js` line 50 at r4](https://reviewable.io/reviews/ocadotechnology/rapid-router/1376#-NI7yVGTCy_jFvp1YuKv:-NIHBXfn0Vz5jq4e_Xhd:b-896fix) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/05e370c2a45c386df46c461589c2707ca2243264/game/static/game/js/map.js#L50)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

extra whitespaces here
</blockquote></details>

Done.
___
*[`game/static/game/js/map.js` line 59 at r4](https://reviewable.io/reviews/ocadotechnology/rapid-router/1376#-NI7y_SI4gsD4KWpkifv:-NIHBYcd7CsW3nJznyTL:b-896fix) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/05e370c2a45c386df46c461589c2707ca2243264/game/static/game/js/map.js#L59)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Extra whitespace here
</blockquote></details>

Done.
___
*[`game/static/game/js/model.js` line 106 at r4](https://reviewable.io/reviews/ocadotechnology/rapid-router/1376#-NI7z7HLE7FVKoH0hF2d:-NIHB__xECC4vKcHXY0a:b-896fix) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/05e370c2a45c386df46c461589c2707ca2243264/game/static/game/js/model.js#L106)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Extra whitespace
</blockquote></details>

Done.
___
*[`game/static/game/js/model.js` line 439 at r4](https://reviewable.io/reviews/ocadotechnology/rapid-router/1376#-NI7zFAdACxnMJP8h4UU:-NIHBb8o17ruWHApVU6C:b-896fix) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/05e370c2a45c386df46c461589c2707ca2243264/game/static/game/js/model.js#L439)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Extra whitespaces
</blockquote></details>

Done.
___
*[`game/static/game/js/model.js` line 581 at r4](https://reviewable.io/reviews/ocadotechnology/rapid-router/1376#-NI7zGyI0AvwUpXMGGnv:-NIHBbc_9KNiFcPQANuE:b-896fix) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/05e370c2a45c386df46c461589c2707ca2243264/game/static/game/js/model.js#L581)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Extra whitespaces
</blockquote></details>

Done.
___
*[`game/static/game/js/model.js` line 610 at r4](https://reviewable.io/reviews/ocadotechnology/rapid-router/1376#-NI7zIeIEqrhlastNb6S:-NIHBcJrCDiH9P8NpBjE:b-896fix) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/05e370c2a45c386df46c461589c2707ca2243264/game/static/game/js/model.js#L610)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Extra whitespace
</blockquote></details>

Done.
___
*[`game/static/game/js/model.js` line 613 at r4](https://reviewable.io/reviews/ocadotechnology/rapid-router/1376#-NI7zK0l6475JLuEd4LE:-NIHBd9T9PG4mYruhQZb:b-896fix) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/05e370c2a45c386df46c461589c2707ca2243264/game/static/game/js/model.js#L613)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Extra whitespace
</blockquote></details>

Done.
___
*[`game/templates/game/level_editor.html` line 341 at r4](https://reviewable.io/reviews/ocadotechnology/rapid-router/1376#-NI7zSir3imx4Ukw5_MP:-NIHBeXh-JvRE_wyEtG4:b-896fix) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/05e370c2a45c386df46c461589c2707ca2243264/game/templates/game/level_editor.html#L341)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Extra whitespaces
</blockquote></details>

Done.
___
*[`game/migrations/0078_merge_20221127_1108.py` line 1 at r4](https://reviewable.io/reviews/ocadotechnology/rapid-router/1376#-NI7w_T_5hrJtiailrYf:-NIHBi757shEXNRgHFh3:bss4a1b) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/05e370c2a45c386df46c461589c2707ca2243264/game/migrations/0078_merge_20221127_1108.py#L1)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Do we need this merging of the migrations?
</blockquote></details>

Removed
___
*[`game/migrations/0077_auto_20221106_1608_data.py` line 1 at r4](https://reviewable.io/reviews/ocadotechnology/rapid-router/1376#-NI7w2l27EbuM4dqUB4S:-NIHBBOr87AUVUYM4VVO:b-896fix) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/05e370c2a45c386df46c461589c2707ca2243264/game/migrations/0077_auto_20221106_1608_data.py#L1)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Can you rename this migration please to reflect what it does? (although I can see it does a few things so maybe something like `update_blocks`?
</blockquote></details>

Done.
___
*[`game/migrations/0077_auto_20221106_1608_data.py` line 37 at r4](https://reviewable.io/reviews/ocadotechnology/rapid-router/1376#-NI7wCse1UonA3noxVqj:-NIHBCaF9i7ArPiODBXh:b-tbah68) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/05e370c2a45c386df46c461589c2707ca2243264/game/migrations/0077_auto_20221106_1608_data.py#L37)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Just using `get` instead of `filter` should work here
</blockquote></details>

I just prefer filter because type isn't a unique constraint and if there were 2 then `get` would break
___
*[`game/migrations/0079_alter_block_options.py` line 1 at r4](https://reviewable.io/reviews/ocadotechnology/rapid-router/1376#-NI7widD4b3xqSqZH0RH:-NIHB9L28FqoRlB7lh5g:b-896fix) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/05e370c2a45c386df46c461589c2707ca2243264/game/migrations/0079_alter_block_options.py#L1)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

If I understand correctly this migration exists because you've edited the `Block` model again after adding the options.
Maybe it would be cleaner to delete migrations 79 and 76, and re-run `makemigrations` which would combine them anyway. And then keep 77 as you have it now. That way we end up with just 2 migrations overall
</blockquote></details>

Done.

**Review by faucomte97 — COMMENTED** [review]
> Reviewed 6 of 9 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1376)* status: 33 of 36 files reviewed, 3 unresolved discussions (waiting on @sebp999)

**Review by faucomte97 — CHANGES_REQUESTED** [review]
> Reviewed 3 of 9 files at r5.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1376)* status: all files reviewed, 1 unresolved discussion (waiting on @sebp999)

___
*[`game/migrations/0077_auto_20221106_1608_data.py` line 37 at r4](https://reviewable.io/reviews/ocadotechnology/rapid-router/1376#-NI7wCse1UonA3noxVqj:-NIraVCvB2a6YBq2UWVG:b-mtlsvb) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/05e370c2a45c386df46c461589c2707ca2243264/game/migrations/0077_auto_20221106_1608_data.py#L37)):*
<details><summary><i>Previously, sebp999 wrote…</i></summary><blockquote>

I just prefer filter because type isn't a unique constraint and if there were 2 then `get` would break
</blockquote></details>

ok :thumbsup: 
___
*[`game/migrations/0079_alter_block_options.py` line 1 at r4](https://reviewable.io/reviews/ocadotechnology/rapid-router/1376#-NI7widD4b3xqSqZH0RH:-NIraHq0-III8pmNWniy:bos5tqh) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/05e370c2a45c386df46c461589c2707ca2243264/game/migrations/0079_alter_block_options.py#L1)):*
<details><summary><i>Previously, sebp999 wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Looks good, although I think you're gonna have to just change the numbering now because we've since merged a new migration that we've labelled as 0077, so this one will now need to be 0078 and the next one 0079

**Review by sebp999 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1376)* status: 30 of 36 files reviewed, 1 unresolved discussion (waiting on @faucomte97)

___
*[`game/migrations/0079_alter_block_options.py` line 1 at r4](https://reviewable.io/reviews/ocadotechnology/rapid-router/1376#-NI7widD4b3xqSqZH0RH:-NKEAndiEcsJTRzsghYS:b-896fix) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/05e370c2a45c386df46c461589c2707ca2243264/game/migrations/0079_alter_block_options.py#L1)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Looks good, although I think you're gonna have to just change the numbering now because we've since merged a new migration that we've labelled as 0077, so this one will now need to be 0078 and the next one 0079
</blockquote></details>

Done.

**Review by faucomte97 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1376)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sebp999)

**Pull request merged**
