### PR TITLE
fix: level 50 solution

### PR DESCRIPTION
**Pull request by sebp999**
## Description
#497: new optimal level solution.  This issue referred to optimal solutions getting less than 20: an issue prevents solutions that are *better* than the model solution from scoring 20 so in this case that is fixed by providing a better solution.  

# How Has This Been Tested?
* All unit tests under end_to_end_tests pass
* Functional test: provide optimal solution and get 20/20 (or click solve as teacher).  Provide worse solution and get less.

## Screenshots (if appropriate):
Screenshot from 2020-09-25 16-50-01

## Checklist:
- [ / ] My change requires a change to the documentation.
- [ / ] I have updated the documentation accordingly.
- [ / ] I have linked this PR to a Zenhub Issue.

---
This change is [Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1124)

### CODE REVIEW

**Review by faucomte97 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1124)* status: all files reviewed, 2 unresolved discussions (waiting on @sebp999)

*[a discussion](https://reviewable.io/reviews/ocadotechnology/rapid-router/1124#-MId3yNyB9XrCfvaiSMP:-MId3yNz1dIqv2PqDCSL:b-3fooch) (no related file):*
cf my comment on the main issue https://app.zenhub.com/workspaces/code-for-life-development-56f2afba6e54555c586f6db3/issues/ocadotechnology/rapid-router/497 - I suggested a way to improve the level even more :)

---
___
*[game/migrations/0072_level_50_solution.py, line 4 at r3](https://reviewable.io/reviews/ocadotechnology/rapid-router/1124#-MId1grR8MZeSKldxRho:-MId1grR8MZeSKldxRhp:b-ipjl4f) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/9e9c70f0d47243895e26745f1c402c64863cb326/game/migrations/0072_level_50_solution.py#L4)):*
> ```Python
> # Code for Life
> #
> # Copyright (C) 2019, Ocado Innovation Limited
> ```

Can we make this 2020 please? :)

**Comment by sebp999** [comment]
Updated the solution and optimal blocks, and changed the date in copyright

**Review by faucomte97 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1124)* status: all files reviewed, 3 unresolved discussions (waiting on @sebp999)

___
*[game/views/level_solutions.py, line 332 at r4](https://reviewable.io/reviews/ocadotechnology/rapid-router/1124#-MJm3_oh6-CtATCOQLg6:-MJm3_oh6-CtATCOQLg7:b-nxuxdj) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/b459ab7fa84cd264143b2d8c0b88d7e5d2901ba1/game/views/level_solutions.py#L332)):*
> ```Python
>     "48": '<xml xmlns="http://www.w3.org/1999/xhtml"><block type="start" deletable="false" x="415" y="678"><next><block type="controls_repeat_until"><value name="condition"><block type="at_destination"></block></value><statement name="body"><block type="controls_if"><mutation elseif="4"></mutation><value name="IF0"><block type="traffic_light"><field name="CHOICE">RED</field></block></value><statement name="DO0"><block type="wait"></block></statement><value name="IF1"><block type="road_exists"><field name="CHOICE">RIGHT</field></block></value><statement name="DO1"><block type="turn_right"></block></statement><value name="IF2"><block type="road_exists"><field name="CHOICE">FORWARD</field></block></value><statement name="DO2"><block type="move_forwards"></block></statement><value name="IF3"><block type="road_exists"><field name="CHOICE">LEFT</field></block></value><statement name="DO3"><block type="turn_left"></block></statement><value name="IF4"><block type="dead_end"></block></value><statement name="DO4"><block type="turn_around"></block></statement></block></statement></block></next></block></xml>',
>     "49": '<xml xmlns="http://www.w3.org/1999/xhtml"><block type="start" deletable="false" x="748" y="797"><next><block type="controls_repeat_until"><value name="condition"><block type="at_destination"></block></value><statement name="body"><block type="controls_if"><mutation elseif="2" else="1"></mutation><value name="IF0"><block type="traffic_light"><field name="CHOICE">RED</field></block></value><statement name="DO0"><block type="wait"></block></statement><value name="IF1"><block type="road_exists"><field name="CHOICE">LEFT</field></block></value><statement name="DO1"><block type="turn_left"></block></statement><value name="IF2"><block type="road_exists"><field name="CHOICE">FORWARD</field></block></value><statement name="DO2"><block type="move_forwards"></block></statement><statement name="ELSE"><block type="turn_right"></block></statement></block></statement></block></next></block></xml>',
>     "50": '<xml xmlns="http://www.w3.org/1999/xhtml"><block type="start" deletable="false" x="125" y="37"><next><block type="controls_repeat"><field name="TIMES">13</field><statement name="DO"><block type="controls_repeat_while"><value name="condition"><block type="traffic_light"><field name="CHOICE">RED</field></block></value><statement name="body"><block type="wait"></block></statement><next><block type="controls_if"><mutation elseif="1" else="1"></mutation><value name="IF0"><block type="road_exists"><field name="CHOICE">LEFT</field></block></value><statement name="DO0"><block type="turn_left" ></block></statement><value name="IF1"><block type="road_exists"><field name="CHOICE">RIGHT</field></block></value><statement name="DO1"><block type="turn_right" ></block></statement><statement name="ELSE"><block type="move_forwards"></block></statement></block></next></block></statement><next><block type="turn_right" ></block></next></block></next></block></xml>',
> ```

Not sure if the latest changes have been pushed, I seem to still see the 13 repeat block?

**Comment by sebp999** [comment]
Revised solution in level_solutions.py

**Review by faucomte97 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1124#-:-MK-IZXB1PdBkVrNjT9V:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sebp999)

**Review by faucomte97 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1124)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sebp999)

**Pull request merged**
