### PR TITLE
Updated go button Fixes #790

### LINKED ISSUE #790: Localisation of the "Go" button
The English "Go" word is hardcoded in the button to play the game in the first levels of Rapid router.
It is a problem for localisation.

(We should figure a way to change the button from an image (especially since Go is not that easily translatable in Polish, the language we're currently translating the game in) )

@piotrrepetowski

### PR DESCRIPTION
**Pull request by j4mesholland**
Changed from ‘Go’ to an play icon. @piotrrepetowski

### CODE REVIEW

**Comment by CelineBoudier** [comment]
Looks good!

**Comment by piotrrepetowski** [comment]
Can you see the 'GO' button? I can only see a black circle?

**Comment by CelineBoudier** [comment]
Yes I can
screenshot from 2016-06-14 16-11-40

**Comment by piotrrepetowski** [comment]
Indeed it works in a browser, but this is how it looks in my file manager :)

screenshot

**Comment by CelineBoudier** [comment]
ha me too indeed

**Comment by CelineBoudier** [comment]
@piotrrepetowski @j4mesholland should work now

**Comment by piotrrepetowski** [comment]
Looks good on my machine.

**Pull request merged**
