### PR TITLE
fix: Make algorithm score setting consistent with presence of model solutions

### PR DESCRIPTION
**Pull request by faucomte97**
The Level model has many fields, among which are the following:
- `disable_algorithm_score`, set to `True` if we want the level not to have an algorithm score (therefore, max score is 10).
- `model_solution`. Badly named, this field is a string which represents a *list of integers*, each integer in the list represents how many blocks can be used in the solution of the level to get 10/10 algorithm score. Eg, if `model_solution` is `[5, 6, 8]`, then the player will get 10/10 in algorithm score for using a solution which has either 5, 6 or 8 blocks in it. Most levels have only one integer in this list.

There are a few considerations to be done here:
- The `model_solution` field applies only to levels which use Blockly. Any Python-only levels should have a blank `model_solution` field (currently represented by an empty list string).
- The point of the `model_solution` field is to allow for the computation of the algorithm score. As such, levels for which `disable_algorithm_score` is `True` should also have a "blank" `model_solution`.

The problem is that these constraints aren't enforced anywhere, as such we had two main issues:
- Some Blockly levels did not have a populated `model_solution` field: this meant that these levels only had a score out of 10 when in fact they should've been out of 20. This manifested in the form of the "full score" star not appearing on the scoreboard for these levels, as the logic was expecting a score out of 20.
- Some levels which had no `model_solution` (most of them Python only levels) still had the algorithm score enabled. This is non-sensical since the algorithm score computation requires a) Blockly and b) a `model_solution` and Python only levels don't have either. This is a symptom of the fact that we still need to implement an algorithm score for Python levels. For this issue, this manifested itself as scores showing 20/10 in the game.

Main fixes:
- Added a migration (0090) which populates the `model_solution` field for the levels that were missing it (these were only the levels in Episode 10).
- Added a migration (0091) which disables the algorithm score for all levels without a `model_solution`.
- Commented out the "hack" in `game.js` which doubled the total score in Python levels to force them to be 20 even though the level itself is out of 10.
- Removed the additional check in `pathFinder.js` which checked for the presence of `model_solution` in order to compute the algorithm score - now redundant as the code can only check whether the level has the algorithm score enabled directly or not.

This change is [Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1585)

### CODE REVIEW

**Review by SKairinos — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1585)* status: all files reviewed, 4 unresolved discussions (waiting on @faucomte97)

___
*[`game/migrations/0090_add_missing_model_solutions.py` line 24 at r1](https://reviewable.io/reviews/ocadotechnology/rapid-router/1585#-Nr_5SHP5sCKQ_lENOk0:-Nr_5SHP5sCKQ_lENOk1:b-gdul0k) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/950f3881fd01279a45c0199fb21204d125f8de18/game/migrations/0090_add_missing_model_solutions.py#L24)):*
> ```Python
> 
>     for level_name, model_solution in model_solutions.items():
>         level = Level.objects.get(name=level_name)
> ```

don't pull the objects into memory. you don't need to read - only update. instead:

```
count = Level.objects.filter(name=level_name).update(model_solution=model_solution)
assert count == 1
```
___
*[`game/migrations/0090_add_missing_model_solutions.py` line 30 at r1](https://reviewable.io/reviews/ocadotechnology/rapid-router/1585#-Nr_6S-Z3Q0kp5prBeKL:-Nr_6S-Z3Q0kp5prBeKM:b-cdnwcr) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/950f3881fd01279a45c0199fb21204d125f8de18/game/migrations/0090_add_missing_model_solutions.py#L30)):*
> ```Python
>     Attempt = apps.get_model("game", "Attempt")
> 
>     Attempt.objects.filter(level__episode__pk=10, score=10).update(score=20)
> ```

rather than giving the students' attempt 20 by default, should we not check if their attempt contains the required number of blocks in the solution?

I have a follow up question: how do we calculate the score if it's less/more than a model solution? let's discuss on a call.
___
*[`game/migrations/0090_add_missing_model_solutions.py` line 37 at r1](https://reviewable.io/reviews/ocadotechnology/rapid-router/1585#-Nr_fEuVCFLpEeJmuK_b:-Nr_fEuVCFLpEeJmuK_c:b-i26bto) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/950f3881fd01279a45c0199fb21204d125f8de18/game/migrations/0090_add_missing_model_solutions.py#L37)):*
> ```Python
>     episode_10 = Episode.objects.get(pk=10)
> 
>     episode_10.level_set.all().update(model_solution="[]")
> ```

This code is dangerous because it assumes the queryset is the same as the forward migration. should be explicit:

Level.objects.filter(name__in=["80", "81", "82", "83", "84", "85", "86", "87", "88", "89", "90", "91"]).update(model_solution="[]")
___
*[`game/migrations/0091_disable_algo_score_if_no_model_solution.py` line 15 at r1](https://reviewable.io/reviews/ocadotechnology/rapid-router/1585#-Nr_nJBG7A-lC4G8upcw:-Nr_nJBG7A-lC4G8upcx:bc31969) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/950f3881fd01279a45c0199fb21204d125f8de18/game/migrations/0091_disable_algo_score_if_no_model_solution.py#L15)):*
> ```Python
> 
>     Attempt.objects.filter(
>         level__default=True, level__model_solution=False, score=20
> ```

why level__model_solution=False? isn't model_solution a char field? did you mean level__model_solution=""?

**Review by SKairinos — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1585)* status: all files reviewed, 2 unresolved discussions (waiting on @faucomte97)

___
*[`game/migrations/0090_add_missing_model_solutions.py` line 51 at r2](https://reviewable.io/reviews/ocadotechnology/rapid-router/1585#-NrdtMSVAwtrzoHi3OEU:-NrdtMSVAwtrzoHi3OEV:b-qe3dj4) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/30cb0935c44b48da2fe599e4430e813b17e36930/game/migrations/0090_add_missing_model_solutions.py#L51)):*
> ```Python
>     )
> 
>     for attempt in attempts:
> ```

Dangerous to iterate a large queryset - this could cause an out-of-memory exception.

You'll need to use an iterator: https://docs.djangoproject.com/en/5.0/ref/models/querysets/#iterator

Your solution will need to incorporate:
- iterator()
- prefetch_related() since we know we need attempt.level
- chunk_size

**Review by faucomte97 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1585)* status: 6 of 7 files reviewed, 2 unresolved discussions (waiting on @SKairinos)

___
*[`game/migrations/0090_add_missing_model_solutions.py` line 24 at r1](https://reviewable.io/reviews/ocadotechnology/rapid-router/1585#-Nr_5SHP5sCKQ_lENOk0:-NraE7Vy-twXudGmvwtA:b-896fix) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/950f3881fd01279a45c0199fb21204d125f8de18/game/migrations/0090_add_missing_model_solutions.py#L24)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

don't pull the objects into memory. you don't need to read - only update. instead:

```
count = Level.objects.filter(name=level_name).update(model_solution=model_solution)
assert count == 1
```
</blockquote></details>

Done.
___
*[`game/migrations/0090_add_missing_model_solutions.py` line 30 at r1](https://reviewable.io/reviews/ocadotechnology/rapid-router/1585#-Nr_6S-Z3Q0kp5prBeKL:-NraE7p63Wwn7VzhIWm5:b85kapv) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/950f3881fd01279a45c0199fb21204d125f8de18/game/migrations/0090_add_missing_model_solutions.py#L30)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

rather than giving the students' attempt 20 by default, should we not check if their attempt contains the required number of blocks in the solution?

I have a follow up question: how do we calculate the score if it's less/more than a model solution? let's discuss on a call.
</blockquote></details>

Done. Bit worried again about memory though.
___
*[`game/migrations/0090_add_missing_model_solutions.py` line 37 at r1](https://reviewable.io/reviews/ocadotechnology/rapid-router/1585#-Nr_fEuVCFLpEeJmuK_b:-NraE6Om8hKXSHMTEuaI:b-896fix) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/950f3881fd01279a45c0199fb21204d125f8de18/game/migrations/0090_add_missing_model_solutions.py#L37)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

This code is dangerous because it assumes the queryset is the same as the forward migration. should be explicit:

Level.objects.filter(name__in=["80", "81", "82", "83", "84", "85", "86", "87", "88", "89", "90", "91"]).update(model_solution="[]")
</blockquote></details>

Done.
___
*[`game/migrations/0090_add_missing_model_solutions.py` line 51 at r2](https://reviewable.io/reviews/ocadotechnology/rapid-router/1585#-NrdtMSVAwtrzoHi3OEU:-NreFO6-4Z27u8WZ8wCQ:b-896fix) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/30cb0935c44b48da2fe599e4430e813b17e36930/game/migrations/0090_add_missing_model_solutions.py#L51)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

Dangerous to iterate a large queryset - this could cause an out-of-memory exception.

You'll need to use an iterator: https://docs.djangoproject.com/en/5.0/ref/models/querysets/#iterator

Your solution will need to incorporate:
- iterator()
- prefetch_related() since we know we need attempt.level
- chunk_size
</blockquote></details>

Done.
___
*[`game/migrations/0091_disable_algo_score_if_no_model_solution.py` line 15 at r1](https://reviewable.io/reviews/ocadotechnology/rapid-router/1585#-Nr_nJBG7A-lC4G8upcw:-Nr_tYDM6p5F5I7kP8tG:b-896fix) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/950f3881fd01279a45c0199fb21204d125f8de18/game/migrations/0091_disable_algo_score_if_no_model_solution.py#L15)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

why level__model_solution=False? isn't model_solution a char field? did you mean level__model_solution=""?
</blockquote></details>

Done.

**Review by SKairinos — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1585)* status: all files reviewed, 1 unresolved discussion (waiting on @faucomte97)

___
*[`game/migrations/0090_add_missing_model_solutions.py` line 30 at r1](https://reviewable.io/reviews/ocadotechnology/rapid-router/1585#-Nr_6S-Z3Q0kp5prBeKL:-NreKPovD1_5E1YvX3G8:b-2c1857) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/950f3881fd01279a45c0199fb21204d125f8de18/game/migrations/0090_add_missing_model_solutions.py#L30)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Done. Bit worried again about memory though.
</blockquote></details>

what is the scenario you're worried about?

**Review by faucomte97 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1585)* status: all files reviewed, 1 unresolved discussion (waiting on @SKairinos)

___
*[`game/migrations/0090_add_missing_model_solutions.py` line 30 at r1](https://reviewable.io/reviews/ocadotechnology/rapid-router/1585#-Nr_6S-Z3Q0kp5prBeKL:-NreUgO10QbdhoqUvKqx:byn4rru) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/950f3881fd01279a45c0199fb21204d125f8de18/game/migrations/0090_add_missing_model_solutions.py#L30)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

what is the scenario you're worried about?
</blockquote></details>

no all good now, since we fixed it with the iterator

**Review by SKairinos — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1585)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @faucomte97)

**Pull request merged**
