### PR TITLE
feat: Create levels 110-122

### PR DESCRIPTION
**Pull request by faucomte97**
This PR:
- Adds in the data for levels 110-122, including path, origin, destination, level type, theme, decors and blocks.
- Adds model_solution number for suitable levels.
- Adds tests for all new levels.
- Includes the new blocks in the path finder logic so they count towards the model solution number.

- - -
This change is [Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1509)

### CODE REVIEW

**Review by SKairinos — COMMENTED** [review]
> Reviewed 4 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1509)* status: 4 of 9 files reviewed, all discussions resolved (waiting on @faucomte97)

**Review by SKairinos — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1509)* status: 4 of 9 files reviewed, 2 unresolved discussions (waiting on @faucomte97)

___
*[`game/migrations/0086_loop_levels.py` line 460 at r1](https://reviewable.io/reviews/ocadotechnology/rapid-router/1509#-Ni5qfhlDbq00BmYw1W7:-Ni5qfhlDbq00BmYw1W8:bigy6m8) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/8387d99008f4431fe6c5112bf18eba7797adfaa5/game/migrations/0086_loop_levels.py#L460)):*
> ```Python
>     Episode = apps.get_model("game", "Episode")
> 
>     for levelID in range(110, 154):
> ```

Don't pull these into memory. Do a bulk delete on the sql server instead.

Level.objects.filter(id__in=range(110, 154)).delete()
___
*[`game/migrations/0086_loop_levels.py` line 471 at r1](https://reviewable.io/reviews/ocadotechnology/rapid-router/1509#-Ni5r0_l5jIMVMAGy4Ud:-Ni5r0_l5jIMVMAGy4Ue:b-ppsxik) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/8387d99008f4431fe6c5112bf18eba7797adfaa5/game/migrations/0086_loop_levels.py#L471)):*
> ```Python
>     Episode.objects.get(pk=14).delete()
>     Episode.objects.get(pk=13).delete()
>     Episode.objects.get(pk=12).delete()
> ```

bulk delete

**Review by SKairinos — COMMENTED** [review]
> Reviewed 1 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1509)* status: 5 of 9 files reviewed, 2 unresolved discussions (waiting on @faucomte97)

**Review by faucomte97 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1509)* status: 5 of 9 files reviewed, 2 unresolved discussions (waiting on @faucomte97 and @SKairinos)

___
*[`game/migrations/0086_loop_levels.py` line 460 at r1](https://reviewable.io/reviews/ocadotechnology/rapid-router/1509#-Ni5qfhlDbq00BmYw1W7:-Ni5uYOi3vlIn6Ko1A3M:b-896fix) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/8387d99008f4431fe6c5112bf18eba7797adfaa5/game/migrations/0086_loop_levels.py#L460)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

Don't pull these into memory. Do a bulk delete on the sql server instead.

Level.objects.filter(id__in=range(110, 154)).delete()
</blockquote></details>

Done.
___
*[`game/migrations/0086_loop_levels.py` line 471 at r1](https://reviewable.io/reviews/ocadotechnology/rapid-router/1509#-Ni5r0_l5jIMVMAGy4Ud:-Ni5uYtS0qjmbCc9zpth:b-896fix) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/8387d99008f4431fe6c5112bf18eba7797adfaa5/game/migrations/0086_loop_levels.py#L471)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

bulk delete
</blockquote></details>

Done.

**Review by SKairinos — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1509)* status: 5 of 9 files reviewed, 1 unresolved discussion (waiting on @faucomte97)

___
*[`game/migrations/0086_loop_levels.py` line 460 at r1](https://reviewable.io/reviews/ocadotechnology/rapid-router/1509#-Ni5qfhlDbq00BmYw1W7:-Ni9Is3S6j9bjVtvz8jE:bxt113w) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/8387d99008f4431fe6c5112bf18eba7797adfaa5/game/migrations/0086_loop_levels.py#L460)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Have you tested this? Does it not break because episode_109 has a FK to episode_110?
___
*[`game/migrations/0086_loop_levels.py` line 471 at r1](https://reviewable.io/reviews/ocadotechnology/rapid-router/1509#-Ni5r0_l5jIMVMAGy4Ud:-Ni9IWW70f8OALHJJx2L:b-264qyp) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/8387d99008f4431fe6c5112bf18eba7797adfaa5/game/migrations/0086_loop_levels.py#L471)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Have you tested this? Does it not break because episode_11 has a FK to episode_12?

**Review by SKairinos — COMMENTED** [review]
> Reviewed 1 of 9 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1509)* status: 7 of 9 files reviewed, 1 unresolved discussion (waiting on @faucomte97)

**Review by SKairinos — CHANGES_REQUESTED** [review]
> Reviewed 1 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1509)* status: 8 of 9 files reviewed, 2 unresolved discussions (waiting on @faucomte97)

___
*[`game/static/game/js/blocklyControl.js` line 327 at r2](https://reviewable.io/reviews/ocadotechnology/rapid-router/1509#-Ni9aGM8EyMdUigJRdJi:-Ni9aGM8EyMdUigJRdJj:b3dglsv) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/210f8544e919c209508d62d6ac31fe59d706d1b1/game/static/game/js/blocklyControl.js#L327)):*
> ```JavaScript
>       n += count(conditionBlock);
>     } else if (block.type === "variables_get" || block.type === "math_number") {
>       n++
> ```

validate that parent is directly or indirectly connected to start block

**Review by SKairinos — APPROVED** [review]
> Reviewed 1 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1509)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @faucomte97)

**Review by SKairinos — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1509)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @faucomte97)

___
*[`game/migrations/0086_loop_levels.py` line 471 at r1](https://reviewable.io/reviews/ocadotechnology/rapid-router/1509#-Ni5r0_l5jIMVMAGy4Ud:-NiA9uUe-FDSEXVtGS2j:b-c4j34z) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/8387d99008f4431fe6c5112bf18eba7797adfaa5/game/migrations/0086_loop_levels.py#L471)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

Have you tested this? Does it not break because episode_11 has a FK to episode_12?
</blockquote></details>

must do

**Review by SKairinos — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1509)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @faucomte97)

**Pull request merged**
