### PR TITLE
Decor refactor

### PR DESCRIPTION
**Pull request by mikebryant**

### CODE REVIEW

**Comment by paulheideman** [comment]
While I agree that storing the decor in the database might not be the best place for our use-case, it is a big change for very little benefit as the load on the database isn't that big now that the decor is cached for every level.

Anyone else have an opinion?

**Comment by CelineBoudier** [comment]
I don't think it makes sense to have the decor in the database - it's a big change true but the tests seem to pass now :p

**Comment by paulheideman** [comment]
Crowd source some testing on staging? Sounds like @CelineBoudier wants to do this change first.

**Comment by CelineBoudier** [comment]
OK let's test this - later we'll try Paul's changes #739 so don't merge them before this pr has been tested on staging :) Thanks!

**Pull request merged**
