### PR TITLE
Fixes #766: Mute button reverts on next level

### LINKED ISSUE #766: Mute button reverts on next level (and doesn't mute Blockly noises)
It'd be better if the mute button honoured your choice through the levels, rather than reverting to unmuted each time.

Also, it'd be good if it could mute the noises Blockly makes as you drag/drop the blocks around.

### PR DESCRIPTION
**Pull request by ChrisMukherjee**

### CODE REVIEW

**Comment by ChrisMukherjee** [comment]
@CelineBoudier @piotrrepetowski Take a look now, please. (Other stuff was too complicated 😛 )

**Comment by CelineBoudier** [comment]
I think @ruthdw had some concerns about the respective use of cookies vs settings?
I think the path might be a problem here - game is only used in the local setting, in the prod website the path is /rapidrouter (you can check and try things with http://www.editthiscookie.com/start/)
Also I'd just add a few words in the title that this is about the mute button so people know without clicking on the bug link  ^^
Thanks

**Comment by ChrisMukherjee** [comment]
Ah, you're right. The path is different on local and prod. I'll change it to match. I don't know if we want to take another approach other than using cookies. I just left it as is and changed a parameter of the cookie.

**Comment by ChrisMukherjee** [comment]
@CelineBoudier @mikebryant Changed it to use `django-reverse-js` as suggested. As far as I can tell, `Urls.levels()` seems to correspond with the rapid router game root. Have a look! Thanks.

**Pull request merged**
