### PR TITLE
fix: Changed colour from black to white for text

### PR DESCRIPTION
**Pull request by morganclarkeee**
## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have linked this PR to a ZenHub Issue.

- - -
This change is [Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1683)

### CODE REVIEW

**Review by faucomte97 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1683)* status: all files reviewed, 1 unresolved discussion (waiting on @morganclarkeee)

___
*[`game/static/game/css/game.css` line 46 at r1](https://reviewable.io/reviews/ocadotechnology/rapid-router/1683#-O38DrEx5AgUBIC64KZK:-O38DrEx5AgUBIC64KZL:bfp5zay) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/b51d2b8e98f798ec3a5e01f63a932258506876eb/game/static/game/css/game.css#L46)):*
> ```CSS
> #tabs #blockly_tab span,
> #tabs #python_tab span,
> #tabs #language_tab select {
> ```

Text looks good and is white :raised_hands:

We also need the dropdown's arrow icon and the other icons white too if possible, ie the puzzle piece icon next to "Blockly" and the "Py" icon next to "Python" (when playing Python levels, example in level 92).

If I remember correctly these two icons come from `game/static/game/image/icons/blockly.svg` and `game/static/game/image/icons/python.svg` which you should be able to turn white in the SVG XML.

Not sure where the arrow for the language dropdown comes from :sweat_smile:

**Comment by faucomte97** [comment]
Hey @morganclarkeee, just letting you know that we've done some significant changes to this repository since you started working on this branch, so you'll need to make sure you update your fork's `master` branch to our `master` branch, and then merge your `master` branch into this branch.

After that you'll also need to delete the `Pipfile.lock` file in the root, and re-run `pipenv install --dev`. Let me know if you have any issues.

**Comment by faucomte97** [comment]
Hey @morganclarkeee, gentle nudge on this - let us know if you're still able to look at it 🙂

**Comment by evemartin** [comment]
Hi Morgan, thank you for having a look at this task from the contributor session! Since our new Python Den is releasing soon we had to move this change up in our priorities, so we've actually changed the text color in another PR - unfortunately this means I have to close this PR but hopefully you'll be happy to know that your change was very useful in addressing the issue! :+1: :+1: We're sorry for the sudden change, thanks for your help and please feel free to keep looking at our tasks and picking any up that look interesting :)

**Pull request closed without merging**
