### PR TITLE
Show a popup if DELIVER block is reached at a non-destination

### PR DESCRIPTION
**Pull request by javicg**
This is what the game would display to the user:

screen shot 2016-01-13 at 20 08 55

Suggestions for a better copy are more than welcome! :)

Fixes #596

### CODE REVIEW

**Comment by javicg** [comment]
I will look at adding tests for the new functionality next week.

**Comment by CelineBoudier** [comment]
Will get @sophinlondon advice on the wording but it seems good to me!

**Comment by CelineBoudier** [comment]
Here are Sophie's suggestions:

It looks like you're trying to deliver to the wrong location. 
It looks like you're delivering to the wrong house.
Have you got the right house? Make sure you don't deliver to the wrong location.
Make sure you deliver to the right house, and don't forget the 'Deliver' command.
Make sure you deliver to the right houses, and don't forget the 'Deliver' command each time.
Don't forget 'Deliver'! 
Make sure you 'Deliver' to the right house
Make sure you 'Deliver' to the right houses

She thinks the second part of your message is for a different issue than Delivering to a random location, so it could be another message depending on the context (like you delivered on one house only.. ?)

Anyway I like her suggestions!
What do you think?

**Comment by sophinlondon** [comment]
If you think I've misunderstood the issue at all or it needs any extra
info, just shout!

On 14 January 2016 at 16:27, CelineBoudier <notifications@github.com> wrote:

> Here are Sophie's suggestions:
>
> It looks like you're trying to deliver to the wrong location.
> It looks like you're delivering to the wrong house.
> Have you got the right house? Make sure you don't deliver to the wrong
> location.
> Make sure you deliver to the right house, and don't forget the 'Deliver'
> command.
> Make sure you deliver to the right houses, and don't forget the 'Deliver'
> command each time.
> Don't forget 'Deliver'!
> Make sure you 'Deliver' to the right house
> Make sure you 'Deliver' to the right houses
>
> She thinks the second part of your message is for a different issue than
> Delivering to a random location, so it could be another message depending
> on the context (like you delivered on one house only.. ?)
>
> Anyway I like her suggestions!
> What do you think?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ocadotechnology/rapid-router/pull/729#issuecomment-171690636>
> .
>



-- 
Social Media and Content Lead   |   Ocado Technology

*T*: 01707228435

-- 


Notice:  This email is confidential and may contain copyright material of 
members of the Ocado Group. Opinions and views expressed in this message 
may not necessarily reflect the opinions and views of the members of the 
Ocado Group. 

 

If you are not the intended recipient, please notify us immediately and 
delete all copies of this message. Please note that it is your 
responsibility to scan this message for viruses. 

 

Fetch and Sizzle are trading names of Speciality Stores Limited, a member 
of the Ocado Group.

 

References to the “Ocado Group” are to Ocado Group plc (registered in 
England and Wales with number 7098618) and its subsidiary undertakings (as 
that expression is defined in the Companies Act 2006) from time to time.  
The registered office of Ocado Group plc is Titan Court, 3 Bishops Square, 
Hatfield Business Park, Hatfield, Herts. AL10 9NE.

**Comment by javicg** [comment]
Yeah, they are very good, thanks!
I think the first three resemble more closely what the problem actually is (the student using the "Deliver" block too early/late, not reaching/missing the delivery location.

I will work on the coverage and copy, and update the PR when I get a chance.
Thanks! :)

**Comment by javicg** [comment]
Copy changed, and I will look at the tests now.

**Comment by CelineBoudier** [comment]
Looks good!

**Comment by CelineBoudier** [comment]
Javi, any new changes? Please rebase and we can merge :) Thanks

**Comment by mrniket** [comment]
Looks like this has gone stale :( (sorry @javicg) so I'm going to close it. If you want to merge it in please re-open :)

**Pull request closed without merging**
