### PR TITLE
feat: include students from other classes in level moderation for admin teachers

### PR DESCRIPTION
**Pull request by razvan-pro**
This change is [Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1358)

### CODE REVIEW

**Review by faucomte97 — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1358)* status: all files reviewed, 1 unresolved discussion (waiting on @razvan-pro)

*[a discussion](https://reviewable.io/reviews/ocadotechnology/rapid-router/1358#-N897B081imTSviLFBx1:-N897B095EcWvtL6igLE:b-1jsr2z) (no related file):*
Admin teachers missing the permission to play levels owned by other teachers' students

___

**Review by razvan-pro — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1358)* status: all files reviewed, 1 unresolved discussion (waiting on @faucomte97)

*[a discussion](https://reviewable.io/reviews/ocadotechnology/rapid-router/1358#-N897B081imTSviLFBx1:-N89B7UlEUGBj4kOjyD0:bipx1n8) (no related file):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Admin teachers missing the permission to play levels owned by other teachers' students
</blockquote></details>

To be done in the other task :slightly_smiling_face: 

___

**Review by faucomte97 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1358#-:-N8Oau7Y2o19yddNbYwe:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @razvan-pro)

**Review by faucomte97 — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1358)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @razvan-pro)

**Pull request merged**
