### PR TITLE
fix: add hint text for RR lv 80 onwards

### PR DESCRIPTION
**Pull request by dionizh**
This change is [Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1203)

### CODE REVIEW

**Review by faucomte97 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1203)* status: all files reviewed, 1 unresolved discussion (waiting on @dionizh)

___
*[game/messages.py, line 2079 at r1](https://reviewable.io/reviews/ocadotechnology/rapid-router/1203#-Md1kf7xCtJmiKa9m-ch:-Md1kf7y8mLpBYcmudkY:b-m4px6c) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/c9d84dc82111dcf2b9152b0c97154b73b2edcac5/game/messages.py#L2079)):*
> ```Python
> PYTHONHINT = (
>     "<br /><br />Check our documentation site, to see "
>     "<a href='https://docs.codeforlife.education/rapid-router/python-commands' target='_blank'>the full list of the commands</a>."
> ```

the full list of commands

**Review by razvan-pro — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1203)* status: all files reviewed, 2 unresolved discussions (waiting on @dionizh)

___
*[game/messages.py, line 1863 at r1](https://reviewable.io/reviews/ocadotechnology/rapid-router/1203#-Md1kbjZ3a_mwTyFNG5h:-Md1kbjZ3a_mwTyFNG5i:b-ktgkwn) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/c9d84dc82111dcf2b9152b0c97154b73b2edcac5/game/messages.py#L1863)):*
> ```Python
> # --- Introduction to Python levels ---
> 
> INTROHINT = (
> ```

Minor, maybe `INTRO_HINT` would be better? Same for `PYTHON_HINT` below, not a strong suggestion though :slightly_smiling_face:

**Review by dionizh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1203)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @faucomte97)

___
*[game/messages.py, line 1863 at r1](https://reviewable.io/reviews/ocadotechnology/rapid-router/1203#-Md1kbjZ3a_mwTyFNG5h:-Md1m9AhAAoOmAHIGx4-:b-896fix) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/c9d84dc82111dcf2b9152b0c97154b73b2edcac5/game/messages.py#L1863)):*
<details><summary><i>Previously, razvan-pro (Razvan Mahu) wrote…</i></summary><blockquote>

Minor, maybe `INTRO_HINT` would be better? Same for `PYTHON_HINT` below, not a strong suggestion though :slightly_smiling_face: 
</blockquote></details>

Done.
___
*[game/messages.py, line 2079 at r1](https://reviewable.io/reviews/ocadotechnology/rapid-router/1203#-Md1kf7xCtJmiKa9m-ch:-Md1m7aE1DKTzYOTnUSg:b-896fix) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/c9d84dc82111dcf2b9152b0c97154b73b2edcac5/game/messages.py#L2079)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

the full list of commands
</blockquote></details>

Done.

**Review by faucomte97 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1203#-:-Md1mJD11hpC6OsjUIoy:bnfp4nl)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @faucomte97)

**Review by faucomte97 — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1203)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dionizh)

**Pull request merged**
