### PR TITLE
Fix mute button

### PR DESCRIPTION
**Pull request by ChrisMukherjee**
Fix for issue #766

### CODE REVIEW

**Comment by CelineBoudier** [comment]
@ChrisMukherjee can you please write Fixes #766 in a commit message so that it updates the issue automatically when the PR is accepted? ^^ Thanks

**Comment by ChrisMukherjee** [comment]
@CelineBoudier You got it, boss. Haven't used GitHub too much for this type of thing yet, so I didn't know how to link it. Wrote the issue number in the comment above to try to link them, but I'll do the commit message thing next time.

**Comment by piotrrepetowski** [comment]
The change looks good to me. Can you squash the commits?

**Comment by ChrisMukherjee** [comment]
@piotrrepetowski I have no idea what I'm doing

**Comment by piotrrepetowski** [comment]
I think we could do the following:
- create another local branch e.g. 'fix-mute-button-2' 
- reset 'fix-mute-button' to the same state as upstream/master branch
- move commit with the fix from 'fix-mute-button-2' to 'fix-mute-button'
- push 'fix-mute-button' with '--force'

**Comment by CelineBoudier** [comment]
http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html ?

**Comment by CelineBoudier** [comment]
http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html :)
As Piotr said, you need a clean slate here rebased on upstream/master :)

**Pull request closed without merging**
