### PR TITLE
feat!: Upgrade from Django 2.2 to 3.2

### PR DESCRIPTION
**Pull request by razvan-pro**
This change is [Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1316)

### CODE REVIEW

**Review by faucomte97 — CHANGES_REQUESTED** [review]
> Reviewed 50 of 50 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1316)* status: all files reviewed, 2 unresolved discussions (waiting on @razvan-pro)

___
*[Pipfile, line 11 at r1](https://reviewable.io/reviews/ocadotechnology/rapid-router/1316#-Mxnd8jQDD8z8SN11IuF:-Mxnd8jQDD8z8SN11IuG:b-h5e49k) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/dda4bb7548a8b3834092dc2ad4099da55f8bc4f4/Pipfile#L11)):*
> ```TOML
> 
> [dev-packages]
> django-selenium-clean = "==0.3.3"
> ```

Our `SeleniumTestCase` is manually copied from 0.3.2. Were there any changes in 0.3.3 that we need to copy over too?
___
*[game/static/game/sass/foundation.scss, line 8 at r1](https://reviewable.io/reviews/ocadotechnology/rapid-router/1316#-MxndtAR6vXe7j1WHJvh:-MxndtAR6vXe7j1WHJvi:b8nak9l) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/dda4bb7548a8b3834092dc2ad4099da55f8bc4f4/game/static/game/sass/foundation.scss#L8)):*
> ```SCSS
> // Make sure the charset is set appropriately
> 
> // Behold, here are all the Foundation components.
> ```

Do we really need all of these files? :confused:

**Review by razvan-pro — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1316)* status: 50 of 53 files reviewed, 2 unresolved discussions (waiting on @faucomte97 and @razvan-pro)

___
*[Pipfile, line 11 at r1](https://reviewable.io/reviews/ocadotechnology/rapid-router/1316#-Mxnd8jQDD8z8SN11IuF:-MxoCupUBk0VI0eW5AiB:bkd67tx) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/dda4bb7548a8b3834092dc2ad4099da55f8bc4f4/Pipfile#L11)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Our `SeleniumTestCase` is manually copied from 0.3.2. Were there any changes in 0.3.3 that we need to copy over too?
</blockquote></details>

Ah, good catch, I did not know this - found a nicer solution I think :slightly_smiling_face: 
___
*[game/static/game/sass/foundation.scss, line 8 at r1](https://reviewable.io/reviews/ocadotechnology/rapid-router/1316#-MxndtAR6vXe7j1WHJvh:-MxoDW5Q3PqZWPMz4Pkr:bc7j65e) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/dda4bb7548a8b3834092dc2ad4099da55f8bc4f4/game/static/game/sass/foundation.scss#L8)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Do we really need all of these files? :confused: 
</blockquote></details>

I think so, we had them before, I just copied them from another package - oh, we may not need the package in this case

**Review by razvan-pro — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1316)* status: 47 of 53 files reviewed, 2 unresolved discussions (waiting on @faucomte97 and @razvan-pro)

___
*[game/static/game/sass/foundation.scss, line 8 at r1](https://reviewable.io/reviews/ocadotechnology/rapid-router/1316#-MxndtAR6vXe7j1WHJvh:-MxoH5BA8DWbAKc5vNpG:b-1ker15) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/dda4bb7548a8b3834092dc2ad4099da55f8bc4f4/game/static/game/sass/foundation.scss#L8)):*
<details><summary><i>Previously, razvan-pro (Razvan Mahu) wrote…</i></summary><blockquote>

I think so, we had them before, I just copied them from another package - oh, we may not need the package in this case
</blockquote></details>

Done - removed the package :slightly_smiling_face:

**Review by faucomte97 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1316)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @razvan-pro)

**Review by faucomte97 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1316)* status: all files reviewed, 1 unresolved discussion (waiting on @razvan-pro)

___
*[game/end_to_end_tests/base_game_test.py, line 1 at r3](https://reviewable.io/reviews/ocadotechnology/rapid-router/1316#-Mxu1WcZ0y-x8JJ5bLC6:-Mxu1WcZ0y-x8JJ5bLC7:b-rengju) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/53eb9037fe20fe8682f10695e8860b21ae53bbc1/game/end_to_end_tests/base_game_test.py#L1)):*
> ```Python
> import os
> ```

Wouldn't you need the same "Site" fix in this file as you did in portal? :thinking:

**Review by faucomte97 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1316#-:-My8Qpd3CUvTCzGom8G0:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @razvan-pro)

**Pull request merged**
