### PR TITLE
fix: Make Scoreboard logic more efficient

### PR DESCRIPTION
**Pull request by faucomte97**
This change is [Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1279)

### CODE REVIEW

**Review by dionizh — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1279)* status: all files reviewed, 2 unresolved discussions (waiting on @faucomte97)

___
*[game/templates/game/level_selection.html, line 54 at r2](https://reviewable.io/reviews/ocadotechnology/rapid-router/1279#-MskYMaBDn62tbiRcxiV:-MskYMaBDn62tbiRcxiW:b-6dp2v9) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/ae3f976b09ef03d684433aa9f482f3fbb09d2a73/game/templates/game/level_selection.html#L54)):*
> ```HTML
> {% block header %}
> <div class="banner banner--rapid-router--background">
>     <section class="level_rr_logo">
> ```

As `section` aligns the text to center, can you remove the related css class that does that (`level_rr_logo`)
___
*[game/views/scoreboard.py, line 107 at r2](https://reviewable.io/reviews/ocadotechnology/rapid-router/1279#-Mskac-A0nCxage8CByQ:-Mskac-A0nCxage8CByR:b-2dboti) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/ae3f976b09ef03d684433aa9f482f3fbb09d2a73/game/views/scoreboard.py#L107)):*
> ```Python
> 
> 
> def scoreboard_data(episode_ids, attempts_per_students):
> ```

Good combining these two! I was thinking about it.
___
*[game/views/scoreboard.py, line 141 at r2](https://reviewable.io/reviews/ocadotechnology/rapid-router/1279#-MskaPzWCiIM4ihFrxh7:-MskaPzWCiIM4ihFrxh8:bxzznil) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/ae3f976b09ef03d684433aa9f482f3fbb09d2a73/game/views/scoreboard.py#L141)):*
> ```Python
>         total_possible_score = 0
>         # Get the best attempts for the specific Episode
>         attempts_dict = [
> ```

Not a dict, incorrect name.

**Review by faucomte97 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1279)* status: all files reviewed, 2 unresolved discussions (waiting on @dionizh)

___
*[game/templates/game/level_selection.html, line 54 at r2](https://reviewable.io/reviews/ocadotechnology/rapid-router/1279#-MskYMaBDn62tbiRcxiV:-MskeK8QEuWtAuqeEVJl:b-896fix) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/ae3f976b09ef03d684433aa9f482f3fbb09d2a73/game/templates/game/level_selection.html#L54)):*
<details><summary><i>Previously, dionizh (Dioni Zhong) wrote…</i></summary><blockquote>

As `section` aligns the text to center, can you remove the related css class that does that (`level_rr_logo`)
</blockquote></details>

Done.
___
*[game/views/scoreboard.py, line 107 at r2](https://reviewable.io/reviews/ocadotechnology/rapid-router/1279#-Mskac-A0nCxage8CByQ:-MskdS9QDka_ldfZ-YBX:b2x9v3l) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/ae3f976b09ef03d684433aa9f482f3fbb09d2a73/game/views/scoreboard.py#L107)):*
<details><summary><i>Previously, dionizh (Dioni Zhong) wrote…</i></summary><blockquote>

Good combining these two! I was thinking about it.
</blockquote></details>

:blush: 
___
*[game/views/scoreboard.py, line 141 at r2](https://reviewable.io/reviews/ocadotechnology/rapid-router/1279#-MskaPzWCiIM4ihFrxh7:-Mskd_NsCcnMbzPW-NrV:b-896fix) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/ae3f976b09ef03d684433aa9f482f3fbb09d2a73/game/views/scoreboard.py#L141)):*
<details><summary><i>Previously, dionizh (Dioni Zhong) wrote…</i></summary><blockquote>

Not a dict, incorrect name.
</blockquote></details>

Done.

**Review by dionizh — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1279)* status: all files reviewed, 5 unresolved discussions (waiting on @dionizh and @faucomte97)

___
*[game/static/game/css/level_selection.css, line 98 at r3](https://reviewable.io/reviews/ocadotechnology/rapid-router/1279#-MsnmGbzAtIxVtYbyWlD:-MsnmGbzAtIxVtYbyWlE:b-xycfzt) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/a2e1b264348c63da90570b939480aae9ef9422aa/game/static/game/css/level_selection.css#L98)):*
> ```CSS
> }
> 
> .banner--rapid-router--background img {
> ```

Sorry, this is minor, but let's not call it `background` as it's actually foreground. Just `banner--rapid-router` is fine I think.
___
*[game/static/game/css/scoreboard.css, line 1 at r3](https://reviewable.io/reviews/ocadotechnology/rapid-router/1279#-MsnmOcd4e8e05v_3rb6:-MsnmOcd4e8e05v_3rb7:brhumzt) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/a2e1b264348c63da90570b939480aae9ef9422aa/game/static/game/css/scoreboard.css#L1)):*
> ```CSS
> .banner--rapid-router--background img {
> ```

Same here.
___
*[game/templates/game/level_selection.html, line 53 at r3](https://reviewable.io/reviews/ocadotechnology/rapid-router/1279#-MsnmT9-0NVFzeE77VZt:-MsnmT9-0NVFzeE77VZu:b-j1i6gu) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/a2e1b264348c63da90570b939480aae9ef9422aa/game/templates/game/level_selection.html#L53)):*
> ```HTML
> 
> {% block header %}
> <div class="banner banner--rapid-router--background">
> ```

Can we have all these in the section and remove the div?
___
*[game/templates/game/scoreboard.html, line 33 at r3](https://reviewable.io/reviews/ocadotechnology/rapid-router/1279#-Msnm_4U9rHyF3lLVgeo:-Msnm_4U9rHyF3lLVgep:brhumzt) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/a2e1b264348c63da90570b939480aae9ef9422aa/game/templates/game/scoreboard.html#L33)):*
> ```HTML
> {% block header %}
> <div class="banner banner--rapid-router--background">
>     <section>
> ```

Same here.

**Review by faucomte97 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1279)* status: 3 of 7 files reviewed, 5 unresolved discussions (waiting on @dionizh)

___
*[game/static/game/css/level_selection.css, line 98 at r3](https://reviewable.io/reviews/ocadotechnology/rapid-router/1279#-MsnmGbzAtIxVtYbyWlD:-Mso0ROp41pJFaKMWMJX:b-896fix) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/a2e1b264348c63da90570b939480aae9ef9422aa/game/static/game/css/level_selection.css#L98)):*
<details><summary><i>Previously, dionizh (Dioni Zhong) wrote…</i></summary><blockquote>

Sorry, this is minor, but let's not call it `background` as it's actually foreground. Just `banner--rapid-router` is fine I think.
</blockquote></details>

Done.
___
*[game/static/game/css/scoreboard.css, line 1 at r3](https://reviewable.io/reviews/ocadotechnology/rapid-router/1279#-MsnmOcd4e8e05v_3rb6:-Mso0SCZ7iDVnySRN7Ev:b-896fix) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/a2e1b264348c63da90570b939480aae9ef9422aa/game/static/game/css/scoreboard.css#L1)):*
<details><summary><i>Previously, dionizh (Dioni Zhong) wrote…</i></summary><blockquote>

Same here.
</blockquote></details>

Done.
___
*[game/templates/game/level_selection.html, line 53 at r3](https://reviewable.io/reviews/ocadotechnology/rapid-router/1279#-MsnmT9-0NVFzeE77VZt:-Mso3WxC522PxxwiSx7A:b-896fix) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/a2e1b264348c63da90570b939480aae9ef9422aa/game/templates/game/level_selection.html#L53)):*
<details><summary><i>Previously, dionizh (Dioni Zhong) wrote…</i></summary><blockquote>

Can we have all these in the section and remove the div?
</blockquote></details>

Done.
___
*[game/templates/game/scoreboard.html, line 33 at r3](https://reviewable.io/reviews/ocadotechnology/rapid-router/1279#-Msnm_4U9rHyF3lLVgeo:-Mso3XZL5cjZfRmOHeiz:b-896fix) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/a2e1b264348c63da90570b939480aae9ef9422aa/game/templates/game/scoreboard.html#L33)):*
<details><summary><i>Previously, dionizh (Dioni Zhong) wrote…</i></summary><blockquote>

Same here.
</blockquote></details>

Done.

**Review by dionizh — APPROVED** [review]
> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1279)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @faucomte97)

**Pull request merged**
