### PR TITLE
fix: 1476-Video sound keeps playing after closing the popup it's in

### PR DESCRIPTION
**Pull request by AbdelrahmanDeghedy**
## Description
- This is a fix to this issue: https://github.com/ocadotechnology/rapid-router/issues/1476
- Added a function that stops the iframe video, and I called it on the play, and close modal buttons.
## How Has This Been Tested?
[stopVideoAfterPopup.webm](https://github.com/ocadotechnology/rapid-router/assets/68364202/b4c88f3e-0226-46cf-8b0b-e6869502f2ec)

- - -
This change is [Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1554)

### CODE REVIEW

**Review by faucomte97 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1554)* status: all files reviewed, 1 unresolved discussion (waiting on @AbdelrahmanDeghedy)

___
*[`game/static/game/js/drawing.js` line 1020 at r1](https://reviewable.io/reviews/ocadotechnology/rapid-router/1554#-NlUJc6WAMiKTUJ3y4c3:-NlUJc6WAMiKTUJ3y4c4:b-zai6v8) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/5799fc568eba159fd5cb0edcea01b60b0bae4dbc/game/static/game/js/drawing.js#L1020)):*
> ```JavaScript
>   // https://gist.github.com/cferdinandi/9044694
>   const video = document.getElementsByClassName("video");
>   var iframeSrc = video[0].src;
> ```

Can you replace `var` with `let` please :pray: :blush:

**Comment by AbdelrahmanDeghedy** [comment]
I have replaced it with a `const` since it's not mutated.

**Comment by AbdelrahmanDeghedy** [comment]
> > Reviewed 1 of 1 files at r1, all commit messages.
> > _[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1554)_ status: all files reviewed, 1 unresolved discussion (waiting on @AbdelrahmanDeghedy)
> 
> _[`game/static/game/js/drawing.js` line 1020 at r1](https://reviewable.io/reviews/ocadotechnology/rapid-router/1554#-NlUJc6WAMiKTUJ3y4c3:-NlUJc6WAMiKTUJ3y4c4:b-zai6v8) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/5799fc568eba159fd5cb0edcea01b60b0bae4dbc/game/static/game/js/drawing.js#L1020)):_
> 
> > ```js
> >   // https://gist.github.com/cferdinandi/9044694
> >   const video = document.getElementsByClassName("video");
> >   var iframeSrc = video[0].src;
> > ```
> 
> Can you replace `var` with `let` please 🙏 😊

I have replaced it with a const since it's not mutated.

**Review by faucomte97 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1554#-:-NlhsDJ09j8WY_6CGVy4:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @AbdelrahmanDeghedy)

**Pull request merged**
