### PR TITLE
feat: scoreboard top,  bottom, teacher, student

### PR DESCRIPTION
**Pull request by dionizh**
Including sub nav bar for all types of users.

---
This change is [Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1272)

### CODE REVIEW

**Review by razvan-pro — CHANGES_REQUESTED** [review]
> Reviewed 4 of 10 files at r1, 1 of 6 files at r3, 1 of 4 files at r5, 3 of 5 files at r6, 5 of 5 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1272)* status: all files reviewed, 9 unresolved discussions (waiting on @dionizh)

___
*[game/static/game/js/scoreboard.js, line 15 at r8](https://reviewable.io/reviews/ocadotechnology/rapid-router/1272#-Mrfs8n777i5HMHqg7La:-Mrfs8n777i5HMHqg7Lb:b-8mylu6) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/c7a429615ccf37241d808135bc0261b8435a0181/game/static/game/js/scoreboard.js#L15)):*
> ```JavaScript
> $('#select-all-levels').on('click', () => {
>     $('[id^="id_episodes_"]').prop('checked', $('#select-all-levels').is(':checked'))
> })
> ```

empty line missing
___
*[game/templates/game/base.html, line 36 at r8](https://reviewable.io/reviews/ocadotechnology/rapid-router/1272#-Mrfyt5m-wExkWC-vnmU:-Mrfyt5m-wExkWC-vnmV:b-2q64l0) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/c7a429615ccf37241d808135bc0261b8435a0181/game/templates/game/base.html#L36)):*
> ```HTML
> <div class="sub-nav sub-nav--teacher">
> {% elif user|is_independent_student %}
> <div class="sub-nav" style="background-color: #f6be00">
> ```

Should we make something like a `sub-nav--independent-student` class in portal for this? :grimacing: 
___
*[game/templates/game/scoreboard.html, line 267 at r8](https://reviewable.io/reviews/ocadotechnology/rapid-router/1272#-Mrg2JIyEeTwBiLG261B:-Mrg2JIyEeTwBiLG261C:bd11mfm) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/c7a429615ccf37241d808135bc0261b8435a0181/game/templates/game/scoreboard.html#L267)):*
> ```HTML
>                             {{ student.total_score }}</td>
>                     </tr>
>                     {% else %}
> ```

Hm, is this else block almost an exact copy of the above except all `td`s have `current-student`? If so, should we move this class to the `tr` and shrink the ifelse to that tag only?
___
*[game/templates/game/scoreboard.html, line 317 at r8](https://reviewable.io/reviews/ocadotechnology/rapid-router/1272#-Mrg2s2q21wFidu44KK0:-Mrg2s2q21wFidu44KK1:b-caf5q8) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/c7a429615ccf37241d808135bc0261b8435a0181/game/templates/game/scoreboard.html#L317)):*
> ```HTML
>                 {% endfor %}
>             </table>
>         {% endif %}
> ```

Should we add a "no data" message if the table is empty/doesn't exist?
___
*[game/templatetags/game/utils.py, line 52 at r8](https://reviewable.io/reviews/ocadotechnology/rapid-router/1272#-Mrg3UzABWzinDGEN-fv:-Mrg3UzABWzinDGEN-fw:bzdruln) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/c7a429615ccf37241d808135bc0261b8435a0181/game/templatetags/game/utils.py#L52)):*
> ```Python
>         and u.userprofile.student
>         and u.userprofile.student.is_independent()
>     )
> ```

Is there no way to use all of these directly from portal to avoid copying them? We may need to move them to `common` to share them.
___
*[game/views/scoreboard.py, line 126 at r8](https://reviewable.io/reviews/ocadotechnology/rapid-router/1272#-MrgARIcB_j6N8vOGTA3:-MrgARId4Oep1W0hgKTP:b2ni78k) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/c7a429615ccf37241d808135bc0261b8435a0181/game/views/scoreboard.py#L126)):*
> ```Python
> 
> 
> class StudentInTrouble:
> ```

lol
___
*[game/views/scoreboard.py, line 168 at r8](https://reviewable.io/reviews/ocadotechnology/rapid-router/1272#-MrgBt0f-_UhKzHaCEQc:-MrgBt0f-_UhKzHaCEQd:b-u0cd6g) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/c7a429615ccf37241d808135bc0261b8435a0181/game/views/scoreboard.py#L168)):*
> ```Python
>     all_students = students_of_classes(classes)
> 
>     the_students = []  # that need improvement
> ```

Minor, `students_in_trouble`? :laughing: 
___
*[game/views/scoreboard.py, line 213 at r8](https://reviewable.io/reviews/ocadotechnology/rapid-router/1272#-MrgCHNtBSMMXABUFFQl:-MrgCHNtBSMMXABUFFQm:bk3t0fw) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/c7a429615ccf37241d808135bc0261b8435a0181/game/views/scoreboard.py#L213)):*
> ```Python
>     episode_ids = set(map(int, request.POST.getlist("episodes")))
> 
>     # Get default data if sets above are empty. Also allows to load scoreboard using
> ```

This may need to be a frontend default, but not too sure. As far as I remember, the users can de-select the default first class and see an empty table if they choose to, though it would be a bit weird :thinking: It can also be confusing at the moment though - if they select nothing, but they still see results in the table.
___
*[game/views/scoreboard_csv.py, line 23 at r8](https://reviewable.io/reviews/ocadotechnology/rapid-router/1272#-MrgD0vbADDkSfIL1cBO:-MrgD0vbADDkSfIL1cBP:b-rvhjrf) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/c7a429615ccf37241d808135bc0261b8435a0181/game/views/scoreboard_csv.py#L23)):*
> ```Python
>         idx = f"{student.class_field.name}_{student.name}"
>         improvement_dict[idx] = student.areas
>     print(improvement_dict)
> ```

This `print` can be removed :slightly_smiling_face:

**Review by razvan-pro — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1272)* status: all files reviewed, 10 unresolved discussions (waiting on @dionizh)

___
*[game/templates/game/scoreboard.html, line 18 at r8](https://reviewable.io/reviews/ocadotechnology/rapid-router/1272#-MrgPLF140m3V5r24NXv:-MrgPLF140m3V5r24NXw:b-v1kf37) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/c7a429615ccf37241d808135bc0261b8435a0181/game/templates/game/scoreboard.html#L18)):*
> ```HTML
>     <script src="{% static 'game/js/scoreboard.js' %}"></script>
>     <script>
>         $(document).ready(function() {
> ```

I just noticed - since we have a `scoreboard.js`, shall we move this whole script there?

**Review by razvan-pro — COMMENTED** [review]
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1272)* status: all files reviewed, 9 unresolved discussions (waiting on @dionizh)

**Review by dionizh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1272)* status: 12 of 14 files reviewed, 9 unresolved discussions (waiting on @razvan-pro)

___
*[game/templates/game/base.html, line 36 at r8](https://reviewable.io/reviews/ocadotechnology/rapid-router/1272#-Mrfyt5m-wExkWC-vnmU:-Mrh2-WO5KToCNifTg5r:bb2hu7f) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/c7a429615ccf37241d808135bc0261b8435a0181/game/templates/game/base.html#L36)):*
<details><summary><i>Previously, razvan-pro (Razvan Mahu) wrote…</i></summary><blockquote>

Should we make something like a `sub-nav--independent-student` class in portal for this? :grimacing: 
</blockquote></details>

Ideally I think these should be available on portal CSS as RR does not have a base CSS for the scoreboard, level selection, etc. Thought maybe we can clean up later when restructuring with react 😬
___
*[game/templates/game/scoreboard.html, line 18 at r8](https://reviewable.io/reviews/ocadotechnology/rapid-router/1272#-MrgPLF140m3V5r24NXv:-Mrh2QHV3tju7CGEzG-M:b-896fix) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/c7a429615ccf37241d808135bc0261b8435a0181/game/templates/game/scoreboard.html#L18)):*
<details><summary><i>Previously, razvan-pro (Razvan Mahu) wrote…</i></summary><blockquote>

I just noticed - since we have a `scoreboard.js`, shall we move this whole script there?
</blockquote></details>

Done.
___
*[game/templates/game/scoreboard.html, line 267 at r8](https://reviewable.io/reviews/ocadotechnology/rapid-router/1272#-Mrg2JIyEeTwBiLG261B:-Mrh4RSRDlr7gA-wlWzx:bsjxyya) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/c7a429615ccf37241d808135bc0261b8435a0181/game/templates/game/scoreboard.html#L267)):*
<details><summary><i>Previously, razvan-pro (Razvan Mahu) wrote…</i></summary><blockquote>

Hm, is this else block almost an exact copy of the above except all `td`s have `current-student`? If so, should we move this class to the `tr` and shrink the ifelse to that tag only?
</blockquote></details>

Ok moved things around.
___
*[game/templates/game/scoreboard.html, line 317 at r8](https://reviewable.io/reviews/ocadotechnology/rapid-router/1272#-Mrg2s2q21wFidu44KK0:-Mrh4YUa65BgMBLTwOj-:b-6vdzxh) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/c7a429615ccf37241d808135bc0261b8435a0181/game/templates/game/scoreboard.html#L317)):*
<details><summary><i>Previously, razvan-pro (Razvan Mahu) wrote…</i></summary><blockquote>

Should we add a "no data" message if the table is empty/doesn't exist?
</blockquote></details>

Mm there's already a no data message as I remember it. Probably comes from datatables?
___
*[game/templatetags/game/utils.py, line 52 at r8](https://reviewable.io/reviews/ocadotechnology/rapid-router/1272#-Mrg3UzABWzinDGEN-fv:-Mrh50gL3bcFEpBGkYcA:b-vja21u) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/c7a429615ccf37241d808135bc0261b8435a0181/game/templatetags/game/utils.py#L52)):*
<details><summary><i>Previously, razvan-pro (Razvan Mahu) wrote…</i></summary><blockquote>

Is there no way to use all of these directly from portal to avoid copying them? We may need to move them to `common` to share them.
</blockquote></details>

It was complaining without this bunch. Need another look.
___
*[game/views/scoreboard.py, line 126 at r8](https://reviewable.io/reviews/ocadotechnology/rapid-router/1272#-MrgARIcB_j6N8vOGTA3:-Mrh55U9AfxnvXfm6TS3:b44u26) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/c7a429615ccf37241d808135bc0261b8435a0181/game/views/scoreboard.py#L126)):*
<details><summary><i>Previously, razvan-pro (Razvan Mahu) wrote…</i></summary><blockquote>

lol
</blockquote></details>

😆
___
*[game/views/scoreboard.py, line 168 at r8](https://reviewable.io/reviews/ocadotechnology/rapid-router/1272#-MrgBt0f-_UhKzHaCEQc:-Mrh5AbpC6PbxYVcM5pJ:butf2k5) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/c7a429615ccf37241d808135bc0261b8435a0181/game/views/scoreboard.py#L168)):*
<details><summary><i>Previously, razvan-pro (Razvan Mahu) wrote…</i></summary><blockquote>

Minor, `students_in_trouble`? :laughing: 
</blockquote></details>

Better not overuse it 😂
___
*[game/views/scoreboard.py, line 213 at r8](https://reviewable.io/reviews/ocadotechnology/rapid-router/1272#-MrgCHNtBSMMXABUFFQl:-Mrh5rf0DGTX-U1GBRfc:b-n1ogr7) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/c7a429615ccf37241d808135bc0261b8435a0181/game/views/scoreboard.py#L213)):*
<details><summary><i>Previously, razvan-pro (Razvan Mahu) wrote…</i></summary><blockquote>

This may need to be a frontend default, but not too sure. As far as I remember, the users can de-select the default first class and see an empty table if they choose to, though it would be a bit weird :thinking: It can also be confusing at the moment though - if they select nothing, but they still see results in the table.
</blockquote></details>

Need a closer look.
___
*[game/views/scoreboard_csv.py, line 23 at r8](https://reviewable.io/reviews/ocadotechnology/rapid-router/1272#-MrgD0vbADDkSfIL1cBO:-Mrh683W0hgzNb6VPzi7:b-u2kpac) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/c7a429615ccf37241d808135bc0261b8435a0181/game/views/scoreboard_csv.py#L23)):*
<details><summary><i>Previously, razvan-pro (Razvan Mahu) wrote…</i></summary><blockquote>

This `print` can be removed :slightly_smiling_face: 
</blockquote></details>

Oops, thanks!

**Review by razvan-pro — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1272)* status: all files reviewed, 6 unresolved discussions (waiting on @dionizh and @razvan-pro)

___
*[game/static/game/js/scoreboard.js, line 17 at r11](https://reviewable.io/reviews/ocadotechnology/rapid-router/1272#-MrhGUYd5QTHWtGiF6o2:-MrhGUYfBJ8KWB2M4V8W:be8cmwq) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/90ee07855610d368c18df3a796077f2be75e0c1c/game/static/game/js/scoreboard.js#L17)):*
> ```JavaScript
> });
> 
> $(document).ready(function () {
> ```

Minor, we can probably put the above inside the ready function too
___
*[game/templates/game/base.html, line 36 at r8](https://reviewable.io/reviews/ocadotechnology/rapid-router/1272#-Mrfyt5m-wExkWC-vnmU:-MrhGi6O2LWG5xsuHdCJ:b-eu4xs) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/c7a429615ccf37241d808135bc0261b8435a0181/game/templates/game/base.html#L36)):*
<details><summary><i>Previously, dionizh (Dioni Zhong) wrote…</i></summary><blockquote>

Ideally I think these should be available on portal CSS as RR does not have a base CSS for the scoreboard, level selection, etc. Thought maybe we can clean up later when restructuring with react 😬
</blockquote></details>

Yep, in portal I was suggesting :slightly_smiling_face: Fine to do it later though :thumbsup: 
___
*[game/templates/game/scoreboard.html, line 317 at r8](https://reviewable.io/reviews/ocadotechnology/rapid-router/1272#-Mrg2s2q21wFidu44KK0:-MrhHryQEo980ZOjGZfK:birxsy9) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/c7a429615ccf37241d808135bc0261b8435a0181/game/templates/game/scoreboard.html#L317)):*
<details><summary><i>Previously, dionizh (Dioni Zhong) wrote…</i></summary><blockquote>

Mm there's already a no data message as I remember it. Probably comes from datatables?
</blockquote></details>

It shows like this to me :grimacing: 


___
*[game/tests/test_scoreboard.py, line 36 at r11](https://reviewable.io/reviews/ocadotechnology/rapid-router/1272#-MrhI8gq9SG9KLVsUGb6:-MrhI8gq9SG9KLVsUGb7:b-4hf8ds) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/90ee07855610d368c18df3a796077f2be75e0c1c/game/tests/test_scoreboard.py#L36)):*
> ```Python
>     # print(student_row.level_scores)
>     print(student_row.completed)
>     print(student_row.percentage_complete)
> ```

Lines above to be removed I assume :smile: 
___
*[game/views/scoreboard.py, line 213 at r8](https://reviewable.io/reviews/ocadotechnology/rapid-router/1272#-MrgCHNtBSMMXABUFFQl:-MrhIJgr6_-rMJpjErXZ:b-ajwimo) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/c7a429615ccf37241d808135bc0261b8435a0181/game/views/scoreboard.py#L213)):*
<details><summary><i>Previously, dionizh (Dioni Zhong) wrote…</i></summary><blockquote>

Need a closer look.
</blockquote></details>

Yep, I'll keep this open as a reminder, but feel free to dismiss it of course, if we decide to go with it like this :slightly_smiling_face: 
___
*[game/views/scoreboard_csv.py, line 23 at r8](https://reviewable.io/reviews/ocadotechnology/rapid-router/1272#-MrgD0vbADDkSfIL1cBO:-MrhIXQ6ET-W7jEeAOJa:b-pwzyxv) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/c7a429615ccf37241d808135bc0261b8435a0181/game/views/scoreboard_csv.py#L23)):*
<details><summary><i>Previously, dionizh (Dioni Zhong) wrote…</i></summary><blockquote>

Oops, thanks!
</blockquote></details>

Still here :grin:

**Review by faucomte97 — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r12, all commit messages.
> Dismissed @razvan-pro from 3 discussions.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1272)* status: all files reviewed, 3 unresolved discussions (waiting on @dionizh and @razvan-pro)

___
*[game/tests/test_scoreboard.py, line 36 at r11](https://reviewable.io/reviews/ocadotechnology/rapid-router/1272#-MrhI8gq9SG9KLVsUGb6:-Ms5LWDm7FryCfpfn4py:bgzcbxz) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/90ee07855610d368c18df3a796077f2be75e0c1c/game/tests/test_scoreboard.py#L36)):*
<details><summary><i>Previously, razvan-pro (Razvan Mahu) wrote…</i></summary><blockquote>

Lines above to be removed I assume :smile: 
</blockquote></details>

Do we not need this function at all anymore?

**Review by dionizh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1272)* status: all files reviewed, 2 unresolved discussions (waiting on @dionizh, @faucomte97, and @razvan-pro)

___
*[game/static/game/js/scoreboard.js, line 17 at r11](https://reviewable.io/reviews/ocadotechnology/rapid-router/1272#-MrhGUYd5QTHWtGiF6o2:-Ms4ZTuMB4ChRr-hBh5U:b-896fix) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/90ee07855610d368c18df3a796077f2be75e0c1c/game/static/game/js/scoreboard.js#L17)):*
<details><summary><i>Previously, razvan-pro (Razvan Mahu) wrote…</i></summary><blockquote>

Minor, we can probably put the above inside the ready function too
</blockquote></details>

Done.
___
*[game/templates/game/base.html, line 36 at r8](https://reviewable.io/reviews/ocadotechnology/rapid-router/1272#-Mrfyt5m-wExkWC-vnmU:-Ms5A9xr6oLAKQmx2Jng:b-896fix) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/c7a429615ccf37241d808135bc0261b8435a0181/game/templates/game/base.html#L36)):*
<details><summary><i>Previously, razvan-pro (Razvan Mahu) wrote…</i></summary><blockquote>

Yep, in portal I was suggesting :slightly_smiling_face: Fine to do it later though :thumbsup: 
</blockquote></details>

Done.



_Code quote:_
```HTML
sub-nav--student
```
___
*[game/templates/game/scoreboard.html, line 317 at r8](https://reviewable.io/reviews/ocadotechnology/rapid-router/1272#-Mrg2s2q21wFidu44KK0:-Ms5CCL2Agyow5_Qe00N:b-896fix) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/c7a429615ccf37241d808135bc0261b8435a0181/game/templates/game/scoreboard.html#L317)):*
<details><summary><i>Previously, razvan-pro (Razvan Mahu) wrote…</i></summary><blockquote>

It shows like this to me :grimacing: 



</blockquote></details>

Done.
___
*[game/templatetags/game/utils.py, line 52 at r8](https://reviewable.io/reviews/ocadotechnology/rapid-router/1272#-Mrg3UzABWzinDGEN-fv:-Ms5CwMuA_G0YvgM_srG:b-3k92ag) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/c7a429615ccf37241d808135bc0261b8435a0181/game/templatetags/game/utils.py#L52)):*
<details><summary><i>Previously, dionizh (Dioni Zhong) wrote…</i></summary><blockquote>

It was complaining without this bunch. Need another look.
</blockquote></details>

Done, just need to load app_tags on scoreboard.html :)
___
*[game/tests/test_scoreboard.py, line 36 at r11](https://reviewable.io/reviews/ocadotechnology/rapid-router/1272#-MrhI8gq9SG9KLVsUGb6:-Ms5D4hUC7Uc0G4QedTE:bme7f90) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/90ee07855610d368c18df3a796077f2be75e0c1c/game/tests/test_scoreboard.py#L36)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Do we not need this function at all anymore? 
</blockquote></details>

No it's not used anymore.
___
*[game/views/scoreboard_csv.py, line 23 at r8](https://reviewable.io/reviews/ocadotechnology/rapid-router/1272#-MrgD0vbADDkSfIL1cBO:-Ms5DQj97SgEjvPFzILQ:b-q59rpa) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/c7a429615ccf37241d808135bc0261b8435a0181/game/views/scoreboard_csv.py#L23)):*
<details><summary><i>Previously, razvan-pro (Razvan Mahu) wrote…</i></summary><blockquote>

Still here :grin: 
</blockquote></details>

Done now?

**Review by faucomte97 — APPROVED** [review]
> Dismissed @razvan-pro from a discussion.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1272)* status: all files reviewed, 1 unresolved discussion (waiting on @dionizh)

**Review by dionizh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1272)* status: 13 of 16 files reviewed, 4 unresolved discussions (waiting on @dionizh, @faucomte97, and @razvan-pro)

___
*[game/static/game/js/scoreboard.js, line 48 at r17](https://reviewable.io/reviews/ocadotechnology/rapid-router/1272#-Ms9jfwBD8GADr-kCPfd:-Ms9jfwBD8GADr-kCPfe:bp08sjf) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/dd1d02f36d5de319123e9f7cc5c14bede51d2177/game/static/game/js/scoreboard.js#L48)):*
> ```JavaScript
>     });
>     // document.getElementById("tableWrapper").scrollIntoView();
> ```

To remove?
___
*[game/views/scoreboard.py, line 213 at r17](https://reviewable.io/reviews/ocadotechnology/rapid-router/1272#-Ms9jspJ6bLOTe_ezkSA:-Ms9jspJ6bLOTe_ezkSB:bv2l1v7) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/dd1d02f36d5de319123e9f7cc5c14bede51d2177/game/views/scoreboard.py#L213)):*
> ```Python
>         episode_ids = set(map(int, request.POST.getlist("episodes")))
>     else:
>         class_ids = {users_classes[0].id}
> ```

Can you get the default magic numbers to constants? Also add comment about defaulting to these values (essentially the comment you removed 😆)
___
*[game/views/scoreboard.py, line 231 at r17](https://reviewable.io/reviews/ocadotechnology/rapid-router/1272#-Ms9k09-2LUcyADpBFgA:-Ms9k09-2LUcyADpBFgB:bn1d7yh) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/dd1d02f36d5de319123e9f7cc5c14bede51d2177/game/views/scoreboard.py#L231)):*
> ```Python
>         classes=users_classes,
>         initial={"classes": ["1"], "episodes": ["1"]},
>     )
> ```

Same here to constants.

**Review by faucomte97 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1272)* status: 13 of 16 files reviewed, 4 unresolved discussions (waiting on @dionizh, @faucomte97, and @razvan-pro)

___
*[game/static/game/js/scoreboard.js, line 48 at r17](https://reviewable.io/reviews/ocadotechnology/rapid-router/1272#-Ms9jfwBD8GADr-kCPfd:-MsA4Wjq7nghIDN7quU8:b-896fix) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/dd1d02f36d5de319123e9f7cc5c14bede51d2177/game/static/game/js/scoreboard.js#L48)):*
<details><summary><i>Previously, dionizh (Dioni Zhong) wrote…</i></summary><blockquote>

To remove?
</blockquote></details>

Done.
___
*[game/views/scoreboard.py, line 213 at r8](https://reviewable.io/reviews/ocadotechnology/rapid-router/1272#-MrgCHNtBSMMXABUFFQl:-MsA3FO0-4fpwrNDg_7H:b-896fix) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/c7a429615ccf37241d808135bc0261b8435a0181/game/views/scoreboard.py#L213)):*
<details><summary><i>Previously, razvan-pro (Razvan Mahu) wrote…</i></summary><blockquote>

Yep, I'll keep this open as a reminder, but feel free to dismiss it of course, if we decide to go with it like this :slightly_smiling_face: 
</blockquote></details>

Done.
___
*[game/views/scoreboard.py, line 213 at r17](https://reviewable.io/reviews/ocadotechnology/rapid-router/1272#-Ms9jspJ6bLOTe_ezkSA:-MsA4PRC8byVnZrhJfSj:b-896fix) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/dd1d02f36d5de319123e9f7cc5c14bede51d2177/game/views/scoreboard.py#L213)):*
<details><summary><i>Previously, dionizh (Dioni Zhong) wrote…</i></summary><blockquote>

Can you get the default magic numbers to constants? Also add comment about defaulting to these values (essentially the comment you removed 😆)
</blockquote></details>

Done.
___
*[game/views/scoreboard.py, line 231 at r17](https://reviewable.io/reviews/ocadotechnology/rapid-router/1272#-Ms9k09-2LUcyADpBFgA:-MsA4RmqBVIwRkUfe31P:b-896fix) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/dd1d02f36d5de319123e9f7cc5c14bede51d2177/game/views/scoreboard.py#L231)):*
<details><summary><i>Previously, dionizh (Dioni Zhong) wrote…</i></summary><blockquote>

Same here to constants.
</blockquote></details>

Done.

**Review by dionizh — COMMENTED** [review]
> Dismissed @razvan-pro from a discussion.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1272)* status: 13 of 16 files reviewed, all discussions resolved (waiting on @faucomte97 and @razvan-pro)

___
*[game/views/scoreboard.py, line 213 at r8](https://reviewable.io/reviews/ocadotechnology/rapid-router/1272#-MrgCHNtBSMMXABUFFQl:-MsA51c98hYuTXpKUCFi:b-896fix) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/c7a429615ccf37241d808135bc0261b8435a0181/game/views/scoreboard.py#L213)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done.

**Review by faucomte97 — COMMENTED** [review]
> Reviewed 1 of 1 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1272)* status: 14 of 16 files reviewed, all discussions resolved (waiting on @faucomte97 and @razvan-pro)

**Review by faucomte97 — COMMENTED** [review]
> Reviewed 2 of 2 files at r18.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1272)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dionizh)

**Review by faucomte97 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r19, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1272)* status: all files reviewed, 1 unresolved discussion (waiting on @dionizh)

___
*[game/tests/test_scoreboard.py, line 205 at r19](https://reviewable.io/reviews/ocadotechnology/rapid-router/1272#-MsALleE4l7FKPgxWIv0:-MsALleE4l7FKPgxWIv1:bckwbco) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/c0ffcccf616b7e87eeee7ba884d2349a90a2b7fb/game/tests/test_scoreboard.py#L205)):*
> ```Python
> 
>         # check first row
>         class_name, name, completed_levels, total_time, total_scores, l1, l2, improvement = actual_rows[0].split(",")        
> ```

Whitespaces :stuck_out_tongue: I'd say run Black here since you have some long lines

**Review by dionizh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1272)* status: 14 of 16 files reviewed, 1 unresolved discussion (waiting on @faucomte97 and @razvan-pro)

___
*[game/tests/test_scoreboard.py, line 205 at r19](https://reviewable.io/reviews/ocadotechnology/rapid-router/1272#-MsALleE4l7FKPgxWIv0:-MsAPdf4D_B_99MEiX8W:bpccunz) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/c0ffcccf616b7e87eeee7ba884d2349a90a2b7fb/game/tests/test_scoreboard.py#L205)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Whitespaces :stuck_out_tongue: I'd say run Black here since you have some long lines
</blockquote></details>

Oops, sorry forgot to turn the reformat back on after HTML work.

**Review by faucomte97 — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r20, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1272#-:-MsAQFjL2A8Ob7qe4l4s:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dionizh)

**Pull request merged**
