### PR TITLE
feat: resizeble window

### PR DESCRIPTION
**Pull request by KamilPawel**
## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have linked this PR to a ZenHub Issue.

---
This change is [Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1359)

### CODE REVIEW

**Review by faucomte97 — CHANGES_REQUESTED** [review]
> Reviewed 8 of 9 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1359)* status: all files reviewed, 12 unresolved discussions (waiting on @KamilPawel)

___
*[`.vscode/settings.json` line 1 at r2](https://reviewable.io/reviews/ocadotechnology/rapid-router/1359#-N8O-uVK7VOAh82S-rOo:-N8O-uVK7VOAh82S-rOp:bx74y9a) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/c3b78405eb98f89049835f2b5cd870aa9c1f5cad/.vscode/settings.json#L1)):*
> ```JSON
> {
> ```

Remove this file please, or add to gitignore :slightly_smiling_face: 
___
*[`game/static/game/css/game.css` line 298 at r2](https://reviewable.io/reviews/ocadotechnology/rapid-router/1359#-N8O1Y_eAgPplVhJa8gX:-N8O1Y_eAgPplVhJa8gY:b-cr058s) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/c3b78405eb98f89049835f2b5cd870aa9c1f5cad/game/static/game/css/game.css#L298)):*
> ```CSS
>     cursor: row-resize;
> }
> ```

2 extra lines here
___
*[`game/static/game/js/event.js` line 13 at r2](https://reviewable.io/reviews/ocadotechnology/rapid-router/1359#-N8O1y47BUOEBsjfN-YY:-N8O1y47BUOEBsjfN-YZ:bktldk9) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/c3b78405eb98f89049835f2b5cd870aa9c1f5cad/game/static/game/js/event.js#L13)):*
> ```JavaScript
>   ocargo.event = new ocargo.Event();
> });
> ```

Extra line
___
*[`game/static/game/js/event.js` line 17 at r2](https://reviewable.io/reviews/ocadotechnology/rapid-router/1359#-N8O2-Ep1wbMwbOhScCp:-N8O2-Ep1wbMwbOhScCq:bktldk9) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/c3b78405eb98f89049835f2b5cd870aa9c1f5cad/game/static/game/js/event.js#L17)):*
> ```JavaScript
> // The play button seems to have very complicated implementation
> // therefore, retriggerring the current event when click run code
> ```

Extra line
___
*[`game/static/game/js/event.js` line 20 at r2](https://reviewable.io/reviews/ocadotechnology/rapid-router/1359#-N8O2091CnNFWe3gidQh:-N8O2091CnNFWe3gidQi:b-i2ta6r) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/c3b78405eb98f89049835f2b5cd870aa9c1f5cad/game/static/game/js/event.js#L20)):*
> ```JavaScript
> const runCode = () => {
>   $("#play_radio").click()
> }
> ```

Add empty line after this one please
___
*[`game/templates/game/game.html` line 181 at r2](https://reviewable.io/reviews/ocadotechnology/rapid-router/1359#-N8O2M0oCelpgHzZmJUm:-N8O2M0oCelpgHzZmJUn:b-sw933a) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/c3b78405eb98f89049835f2b5cd870aa9c1f5cad/game/templates/game/game.html#L181)):*
> ```HTML
>       <input type="radio" name="tabs" id="play_radio">
>       <label for="play_radio">
>         <span class="iconify icon" data-icon="ic:outline-play-arrow" style="color: white;"></span>
> ```

This icon is no longer replaced with the "Pause" icon that normally shows up after pressing play (check staging to see how it normally works)
___
*[`game/templates/game/game.html` line 190 at r2](https://reviewable.io/reviews/ocadotechnology/rapid-router/1359#-N8O2UQA4UU4zqVNDdHX:-N8O2UQA4UU4zqVNDdHY:bpanvkf) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/c3b78405eb98f89049835f2b5cd870aa9c1f5cad/game/templates/game/game.html#L190)):*
> ```HTML
>       <input type="radio" name="tabs" id="fast_radio">
>       <label for="fast_radio">
>           <span class="iconify icon" data-icon="charm:media-fast-forward" style="color: white;"></span>
> ```

This icon is no longer replaced with the "Slow" icon that normally shows up after pressing play (check staging to see how it normally works)
___
*[`game/templates/game/game.html` line 206 at r2](https://reviewable.io/reviews/ocadotechnology/rapid-router/1359#-N8O2YmK7MSflIFFR1xa:-N8O2YmK7MSflIFFR1xb:byktfgs) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/c3b78405eb98f89049835f2b5cd870aa9c1f5cad/game/templates/game/game.html#L206)):*
> ```HTML
>       <input type="radio" name="tabs" id="step_radio">
>       <label for="step_radio">
>         <span class="iconify icon" data-icon="mdi:arrow-u-down-right" style="color: white;" data-width="5" data-height="20"></span>
> ```

This icon is slightly different to the one Laura has on Miro, is that OK?
___
*[`game/templates/game/game.html` line 268 at r2](https://reviewable.io/reviews/ocadotechnology/rapid-router/1359#-N8O2g_CD0paDFhPrRfh:-N8O2g_CD0paDFhPrRfi:b49uic5) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/c3b78405eb98f89049835f2b5cd870aa9c1f5cad/game/templates/game/game.html#L268)):*
> ```HTML
>       <input type="radio" name="tabs" id="mute_radio">
>       <label for="mute_radio">
>         <span class="iconify icon" data-icon="material-symbols:volume-off-outline" style="color: white;"></span>
> ```

I can't check it locally cos cookies aren't enabled but we'll need to check if that icon gets replaced with the "Unmute" one like it does on staging. Maybe deploy to dev to test it?
___
*[`game/templates/game/game.html` line 339 at r2](https://reviewable.io/reviews/ocadotechnology/rapid-router/1359#-N8O36BKCt3AdcOtTE_V:-N8O36BKCt3AdcOtTE_W:bickqis) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/c3b78405eb98f89049835f2b5cd870aa9c1f5cad/game/templates/game/game.html#L339)):*
> ```HTML
>             <div id="console">
>               <div id="consoleRunCode">
>                 <button onclick="runCode()" id="run-code-button" class="navigation_button_kurono">
> ```

Not sure how I feel about this class name, maybe it could be called something else to signify it's a different nav button? But I understand it's because it's similar to Kurono's button. Maybe it's fine, I'll leave this comment as non-blocking.
___
*[`game/templates/game/game.html` line 341 at r2](https://reviewable.io/reviews/ocadotechnology/rapid-router/1359#-N8O3YzaELLPSgwfTGxa:-N8O3YzaELLPSgwfTGxb:bs07dbb) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/c3b78405eb98f89049835f2b5cd870aa9c1f5cad/game/templates/game/game.html#L341)):*
> ```HTML
>                 <button onclick="runCode()" id="run-code-button" class="navigation_button_kurono">
>                   <span>{% trans "Run code" %}</span>
>                   <span class="iconify icon" data-icon="ic:outline-play-arrow"></span>
> ```

The icons in the Kurono-style buttons seem to be a bit too small compared to the designs, maybe you can increase their size?
___
*[`game/templates/game/game.html` line 353 at r2](https://reviewable.io/reviews/ocadotechnology/rapid-router/1359#-N8O3MLq5Q3L-7-CuODt:-N8O3MLq5Q3L-7-CuODu:b-ffna6v) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/c3b78405eb98f89049835f2b5cd870aa9c1f5cad/game/templates/game/game.html#L353)):*
> ```HTML
>               </button>
>               <div class="d-flex">
>               </div>
> ```

Empty div? (maybe it's necessary for the resizing, if so maybe leave a comment?)



_Code quote:_
```HTML
              <div class="d-flex">
              </div>
```

**Review by KamilPawel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1359)* status: 2 of 20 files reviewed, 11 unresolved discussions (waiting on @faucomte97)

___
*[`game/static/game/css/game.css` line 298 at r2](https://reviewable.io/reviews/ocadotechnology/rapid-router/1359#-N8O1Y_eAgPplVhJa8gX:-N8OCpqh8UU_X6PD_hq9:b-896fix) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/c3b78405eb98f89049835f2b5cd870aa9c1f5cad/game/static/game/css/game.css#L298)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

2 extra lines here
</blockquote></details>

Done.
___
*[`game/static/game/js/event.js` line 13 at r2](https://reviewable.io/reviews/ocadotechnology/rapid-router/1359#-N8O1y47BUOEBsjfN-YY:-N8OCxOT-Rc-nmSKgyxs:b-896fix) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/c3b78405eb98f89049835f2b5cd870aa9c1f5cad/game/static/game/js/event.js#L13)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Extra line
</blockquote></details>

Done.
___
*[`game/static/game/js/event.js` line 17 at r2](https://reviewable.io/reviews/ocadotechnology/rapid-router/1359#-N8O2-Ep1wbMwbOhScCp:-N8OD2ge8Et_nrT-ulo2:b-896fix) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/c3b78405eb98f89049835f2b5cd870aa9c1f5cad/game/static/game/js/event.js#L17)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Extra line
</blockquote></details>

Done.
___
*[`game/static/game/js/event.js` line 20 at r2](https://reviewable.io/reviews/ocadotechnology/rapid-router/1359#-N8O2091CnNFWe3gidQh:-N8OD3-S6FL37_70rn4f:b-896fix) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/c3b78405eb98f89049835f2b5cd870aa9c1f5cad/game/static/game/js/event.js#L20)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Add empty line after this one please
</blockquote></details>

Done.
___
*[`game/templates/game/game.html` line 181 at r2](https://reviewable.io/reviews/ocadotechnology/rapid-router/1359#-N8O2M0oCelpgHzZmJUm:-N8YOJx3BUz7X4DDceQ7:b-896fix) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/c3b78405eb98f89049835f2b5cd870aa9c1f5cad/game/templates/game/game.html#L181)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

This icon is no longer replaced with the "Pause" icon that normally shows up after pressing play (check staging to see how it normally works)
</blockquote></details>

Done.
___
*[`game/templates/game/game.html` line 190 at r2](https://reviewable.io/reviews/ocadotechnology/rapid-router/1359#-N8O2UQA4UU4zqVNDdHX:-N8YOLPo3vCNGWjXrC2u:b-896fix) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/c3b78405eb98f89049835f2b5cd870aa9c1f5cad/game/templates/game/game.html#L190)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

This icon is no longer replaced with the "Slow" icon that normally shows up after pressing play (check staging to see how it normally works)
</blockquote></details>

Done.
___
*[`game/templates/game/game.html` line 206 at r2](https://reviewable.io/reviews/ocadotechnology/rapid-router/1359#-N8O2YmK7MSflIFFR1xa:-N8YONE9B4AoNgkxFL88:bkypkd5) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/c3b78405eb98f89049835f2b5cd870aa9c1f5cad/game/templates/game/game.html#L206)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

This icon is slightly different to the one Laura has on Miro, is that OK?
</blockquote></details>

Yea, couldn't find the exact icon :/ 
___
*[`game/templates/game/game.html` line 268 at r2](https://reviewable.io/reviews/ocadotechnology/rapid-router/1359#-N8O2g_CD0paDFhPrRfh:-N8YOQ7Z8EO5dIQafzfs:b-896fix) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/c3b78405eb98f89049835f2b5cd870aa9c1f5cad/game/templates/game/game.html#L268)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

I can't check it locally cos cookies aren't enabled but we'll need to check if that icon gets replaced with the "Unmute" one like it does on staging. Maybe deploy to dev to test it?
</blockquote></details>

Done.
___
*[`game/templates/game/game.html` line 341 at r2](https://reviewable.io/reviews/ocadotechnology/rapid-router/1359#-N8O3YzaELLPSgwfTGxa:-N8YPE2cDd0Gx9iHWE6J:b-896fix) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/c3b78405eb98f89049835f2b5cd870aa9c1f5cad/game/templates/game/game.html#L341)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

The icons in the Kurono-style buttons seem to be a bit too small compared to the designs, maybe you can increase their size?
</blockquote></details>

Done.
___
*[`game/templates/game/game.html` line 353 at r2](https://reviewable.io/reviews/ocadotechnology/rapid-router/1359#-N8O3MLq5Q3L-7-CuODt:-N8YPafh2PSixGAPgmaf:b-896fix) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/c3b78405eb98f89049835f2b5cd870aa9c1f5cad/game/templates/game/game.html#L353)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Empty div? (maybe it's necessary for the resizing, if so maybe leave a comment?)
</blockquote></details>

Done.
___
*[`.vscode/settings.json` line 1 at r2](https://reviewable.io/reviews/ocadotechnology/rapid-router/1359#-N8O-uVK7VOAh82S-rOo:-N8YOICC8sFbys1t8iVs:b-896fix) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/c3b78405eb98f89049835f2b5cd870aa9c1f5cad/.vscode/settings.json#L1)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Remove this file please, or add to gitignore :slightly_smiling_face: 
</blockquote></details>

Done.

**Review by KamilPawel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1359)* status: 18 of 20 files reviewed, 2 unresolved discussions (waiting on @faucomte97)

___
*[`game/static/game/js/game.js` line 508 at r1](https://reviewable.io/reviews/ocadotechnology/rapid-router/1359#-N8Z6_Bo9ZqowALjF_bn:-N8Z7r1lEtoCsTD_twxv:b-896fix) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/94e8e21724ce3aa22e90cd3b4cc08f9a487d01f0/game/static/game/js/game.js#L508)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Can you add this empty line back in please?
</blockquote></details>

Done.
___
*[`game/static/game/js/game.js` line 494 at r6](https://reviewable.io/reviews/ocadotechnology/rapid-router/1359#-N8Z6F2L50bMss_YdtaT:-N8Z7qjX8z6u8YIsKWrd:b-896fix) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/f686161e51094357f950d95bfcd5ab1b05b2f7dc/game/static/game/js/game.js#L494)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

console log :slightly_smiling_face: 
</blockquote></details>

Done.
___
*[`game/templates/game/game.html` line 341 at r2](https://reviewable.io/reviews/ocadotechnology/rapid-router/1359#-N8O3YzaELLPSgwfTGxa:-N8ZFCAn-ea9K74gM55s:b-msw091) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/c3b78405eb98f89049835f2b5cd870aa9c1f5cad/game/templates/game/game.html#L341)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

For some reason the icon in the clear console button still seems to small? The run code icon looks fine though.
</blockquote></details>

Would need a longer button :/

**Review by faucomte97 — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1359#-:-N8ZIRYr7UltuRv2snec:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @KamilPawel)

**Review by faucomte97 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1359)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @KamilPawel)

**Pull request merged**
