### PR TITLE
Improve startup instructions in README.md

### PR DESCRIPTION
**Pull request by mzywiol**
Issue #776

### CODE REVIEW

**Comment by CelineBoudier** [comment]
Thanks Maciej!
There seem to be conflicts. Can you please rebase it? :)
Also, might not be necessary to have an internal pr here? Usually we'd PR from mzywiol/linux-statrup-instructions to ocadotechnology:master
(Also, if you write Fixes #776 in the commit title it will update automatically.)

**Comment by CelineBoudier** [comment]
@PhydeauxLeChien I know you also have some feedbacks - can you check this is covering your experience and state the linux version you're using, it would be helpful. Thanks

**Comment by PhydeauxLeChien** [comment]
The instructions to install ruby and sass cover the main problems I had when setting up (on Ubuntu 16.04 LTS).

The other thing I needed to do was install 'libxml2-dev', 'libxslt1-dev', and 'zlib1g-dev' as recommended by: http://stackoverflow.com/questions/5178416/pip-install-lxml-error

**Comment by CelineBoudier** [comment]
@PhydeauxLeChien Can you update the readme @mzywiol  has written, and making sure it's rebased on master since the readme has changed since - thanks :)

**Pull request closed without merging**
