### PR TITLE
docs: Improve issue templates

### PR DESCRIPTION
**Pull request by faucomte97**
This change is [Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1342)

### CODE REVIEW

**Review by dionizh — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1342)* status: all files reviewed, 1 unresolved discussion (waiting on @faucomte97)

___
*[`.github/ISSUE_TEMPLATE/new_task.md` line 12 at r1](https://reviewable.io/reviews/ocadotechnology/rapid-router/1342#-N34kiUH9XwzK2r_eFyc:-N34kiUH9XwzK2r_eFyd:bxzxp89) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/69db00987e53cf6d4b57aae34d408a558ac76a52/.github/ISSUE_TEMPLATE/new_task.md#L12)):*
> ```Markdown
> 
> ## Acceptance Criteria
> - [ ] Criterion 1
> ```

Can you do `...` instead of Criterion x? So it's not too busy looking :)

**Review by faucomte97 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1342)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @dionizh)

___
*[`.github/ISSUE_TEMPLATE/new_task.md` line 12 at r1](https://reviewable.io/reviews/ocadotechnology/rapid-router/1342#-N34kiUH9XwzK2r_eFyc:-N34noyPBN_ecYeQTVAj:b-896fix) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/69db00987e53cf6d4b57aae34d408a558ac76a52/.github/ISSUE_TEMPLATE/new_task.md#L12)):*
<details><summary><i>Previously, dionizh (Dioni Zhong) wrote…</i></summary><blockquote>

Can you do `...` instead of Criterion x? So it's not too busy looking :)
</blockquote></details>

Done.

**Review by dionizh — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1342)* status: all files reviewed, 1 unresolved discussion (waiting on @dionizh)

**Review by dionizh — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1342#-:-N34phSJ1pNGG7BKTC8W:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @faucomte97)

**Pull request merged**
