### PR TITLE
GitHub actions publish

### PR DESCRIPTION
**Pull request by mrniket**
This change is [Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1137)

### CODE REVIEW

**Review by razvan-pro — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1137)* status: all files reviewed, 1 unresolved discussion (waiting on @mrniket)

___
*[.github/workflows/publish-python-package.yml, line 13 at r3](https://reviewable.io/reviews/ocadotechnology/rapid-router/1137#-MN8Bn3g896F1YsvmT0c:-MN8Bn3g896F1YsvmT0d:b-uiesyz) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/003bd919dbe7785c26bea1f7f090308dad239c01/.github/workflows/publish-python-package.yml#L13)):*
> ```YAML
>     name: Publish PyPi Packages
>     if: ${{ github.event.workflow_run.conclusion == 'success' }}
>     runs-on: ubuntu-latest
> ```

Static ubuntu version please `ubuntu-18.04` :slightly_smiling_face:

**Review by mrniket — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1137)* status: all files reviewed, 1 unresolved discussion (waiting on @razvan-pro)

___
*[.github/workflows/publish-python-package.yml, line 13 at r3](https://reviewable.io/reviews/ocadotechnology/rapid-router/1137#-MN8Bn3g896F1YsvmT0c:-MN8CQv19RH5TMV4tBkD:bjjdutj) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/003bd919dbe7785c26bea1f7f090308dad239c01/.github/workflows/publish-python-package.yml#L13)):*
<details><summary><i>Previously, razvan-pro (Razvan Mahu) wrote…</i></summary><blockquote>

Static ubuntu version please `ubuntu-18.04` :slightly_smiling_face: 
</blockquote></details>

fair 😊 would it be better to use a later version of ubuntu?

**Review by razvan-pro — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1137)* status: all files reviewed, 1 unresolved discussion (waiting on @mrniket)

___
*[.github/workflows/publish-python-package.yml, line 13 at r3](https://reviewable.io/reviews/ocadotechnology/rapid-router/1137#-MN8Bn3g896F1YsvmT0c:-MN8DDlABl2bef4PPvnV:bnm4nd8) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/003bd919dbe7785c26bea1f7f090308dad239c01/.github/workflows/publish-python-package.yml#L13)):*
<details><summary><i>Previously, mrniket (Niket Shah) wrote…</i></summary><blockquote>

fair 😊 would it be better to use a later version of ubuntu?
</blockquote></details>

maybe, it may be a test though :smile:  I'm not sure if it has all the features yet, but I see they're planning to switch `latest` to a later version soon, so maybe it's ready :shrug:

**Review by mrniket — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1137)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @razvan-pro)

___
*[.github/workflows/publish-python-package.yml, line 13 at r3](https://reviewable.io/reviews/ocadotechnology/rapid-router/1137#-MN8Bn3g896F1YsvmT0c:-MN8FWBX8uzLLvJOPZmy:b5idf9j) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/003bd919dbe7785c26bea1f7f090308dad239c01/.github/workflows/publish-python-package.yml#L13)):*
<details><summary><i>Previously, razvan-pro (Razvan Mahu) wrote…</i></summary><blockquote>

maybe, it may be a test though :smile:  I'm not sure if it has all the features yet, but I see they're planning to switch `latest` to a later version soon, so maybe it's ready :shrug: 
</blockquote></details>

Judging from https://github.com/actions/virtual-environments, I think it's ready, but I'll keep at as requested for now 😊

**Review by mrniket — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1137)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @razvan-pro)

___
*[.github/workflows/publish-python-package.yml, line 13 at r3](https://reviewable.io/reviews/ocadotechnology/rapid-router/1137#-MN8Bn3g896F1YsvmT0c:-MN8FhNz3c_ud3vZdQf4:b-896fix) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/003bd919dbe7785c26bea1f7f090308dad239c01/.github/workflows/publish-python-package.yml#L13)):*
<details><summary><i>Previously, mrniket (Niket Shah) wrote…</i></summary><blockquote>

Judging from https://github.com/actions/virtual-environments, I think it's ready, but I'll keep at as requested for now 😊 
</blockquote></details>

Done.

**Review by razvan-pro — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1137#-:-MN8Fm0E4S3dyg7dtJr7:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by razvan-pro — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1137)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[.github/workflows/publish-python-package.yml, line 13 at r3](https://reviewable.io/reviews/ocadotechnology/rapid-router/1137#-MN8Bn3g896F1YsvmT0c:-MN8Fys320WdBy920vNI:b7lrp3f) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/003bd919dbe7785c26bea1f7f090308dad239c01/.github/workflows/publish-python-package.yml#L13)):*
<details><summary><i>Previously, mrniket (Niket Shah) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

:+1: We can switch all versions (including CI) later :slightly_smiling_face:

**Pull request merged**
