### PR TITLE
feat: teacher level re-sharing

### PR DESCRIPTION
**Pull request by razvan-pro**
This change is [Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1343)

### CODE REVIEW

**Review by faucomte97 — CHANGES_REQUESTED** [review]
> Reviewed 4 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1343)* status: 4 of 11 files reviewed, 1 unresolved discussion (waiting on @razvan-pro)

___
*[`game/permissions.py` line 140 at r1](https://reviewable.io/reviews/ocadotechnology/rapid-router/1343#-N35mLlE6EHweKKSm_eb:-N35mLlE6EHweKKSm_ec:b-54egmn) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/5cfeebc0dd44f7987a116ffa82ef306802f97a7a/game/permissions.py#L140)):*
> ```Python
>             #         request.user.userprofile.teacher.school
>             #         == obj.owner.student.class_field.teacher.school
>             #     )
> ```

Delete this?



_Code quote:_
```Python
            # # if the user is a teacher, check if they're in the same school as the level owner
            # if hasattr(obj.owner, "teacher"):
            #     return (
            #         request.user.userprofile.teacher.school == obj.owner.teacher.school
            #     )
            # elif hasattr(obj.owner, "student"):
            #     return (
            #         request.user.userprofile.teacher.school
            #         == obj.owner.student.class_field.teacher.school
            #     )
```

**Review by razvan-pro — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1343)* status: 3 of 11 files reviewed, 1 unresolved discussion (waiting on @faucomte97 and @razvan-pro)

___
*[`game/permissions.py` line 140 at r1](https://reviewable.io/reviews/ocadotechnology/rapid-router/1343#-N35mLlE6EHweKKSm_eb:-N3JUo4lDVR02g4SsQOb:b-896fix) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/5cfeebc0dd44f7987a116ffa82ef306802f97a7a/game/permissions.py#L140)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Delete this?
</blockquote></details>

Done.

**Review by faucomte97 — CHANGES_REQUESTED** [review]
> Reviewed 5 of 11 files at r1, 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1343)* status: all files reviewed, 4 unresolved discussions (waiting on @razvan-pro)

___
*[`game/static/game/js/sharing.js` line 10 at r2](https://reviewable.io/reviews/ocadotechnology/rapid-router/1343#-N3uHnQyASKDA7TSVaEC:-N3uHnQyASKDA7TSVaED:bvbdfvh) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/c7292fe0ed59b0bf14368c0deed53c9d390070f1/game/static/game/js/sharing.js#L10)):*
> ```JavaScript
> ocargo.Sharing = function (getLevelId, validationFunction) {
>   this.text = [];
>   this.text.shared = gettext("Yes");
> ```

Not blocking, do we want to get rid of all the `gettext` since we said we were gonna phase localisation out?
___
*[`game/static/game/js/sharing.js` line 27 at r2](https://reviewable.io/reviews/ocadotechnology/rapid-router/1343#-N3uI0L21zgMXb32vX5Y:-N3uI0L21zgMXb32vX5Z:b-uahb9n) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/c7292fe0ed59b0bf14368c0deed53c9d390070f1/game/static/game/js/sharing.js#L27)):*
> ```JavaScript
>  */
> ocargo.Sharing.prototype.setupTeacherPanel = function () {
>   var sharing = this;
> ```

Replace `var`s with `let`s please :stuck_out_tongue_winking_eye: 
___
*[`game/templates/game/game.html` line 433 at r2](https://reviewable.io/reviews/ocadotechnology/rapid-router/1343#-N3uJzte2GvX19SecHPk:-N3uJzte2GvX19SecHPl:b-qq13z7) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/c7292fe0ed59b0bf14368c0deed53c9d390070f1/game/templates/game/game.html#L433)):*
> ```HTML
>               <thead>
>                 <tr>
>                   <th>{% trans "Name" %}</th>
> ```

Can we get rid of the localisation here too pls
___
*[`game/tests/test_level_editor.py` line 234 at r2](https://reviewable.io/reviews/ocadotechnology/rapid-router/1343#-N3uKCMe17XYxkMHl_xY:-N3uKCMe17XYxkMHl_xZ:bdb9haa) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/c7292fe0ed59b0bf14368c0deed53c9d390070f1/game/tests/test_level_editor.py#L234)):*
> ```Python
> 
>         # Now the second teacher should be able to share the level
>         print(student2.new_user.id)
> ```

rogue print

**Review by faucomte97 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1343)* status: all files reviewed, 5 unresolved discussions (waiting on @razvan-pro)

*[a discussion](https://reviewable.io/reviews/ocadotechnology/rapid-router/1343#-N3uRuP80VugG-uMBHeE:-N3uRuP80VugG-uMBHeF:b-gzm3ji) (no related file):*


So I logged in as portaladmin, shared it with Einstein and Planck and when I logged in as Einstein it didn't show as shared with Portaladmin. The owner of the level should also be shown as "Yes" in the shared with list no?

___

**Review by faucomte97 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1343)* status: all files reviewed, 6 unresolved discussions (waiting on @razvan-pro)

*[a discussion](https://reviewable.io/reviews/ocadotechnology/rapid-router/1343#-N3uSUhu8Rv0ODXd5VQS:-N3uSUhu8Rv0ODXd5VQT:b-ud3hzn) (no related file):*


Then, as Albert Einstein I shared with Leonardo (student), and then when I logged in as Leonardo and went to play the level it showed Portaladmin's name in brackets. Should that name be the level owner or the name of the person who shared it with you?

___

**Review by razvan-pro — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1343)* status: all files reviewed, 6 unresolved discussions (waiting on @faucomte97 and @razvan-pro)

*[a discussion](https://reviewable.io/reviews/ocadotechnology/rapid-router/1343#-N3uRuP80VugG-uMBHeE:-N3xpgkMEc_dnZwSYflh:b-6b7clh) (no related file):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>



So I logged in as portaladmin, shared it with Einstein and Planck and when I logged in as Einstein it didn't show as shared with Portaladmin. The owner of the level should also be shown as "Yes" in the shared with list no?
</blockquote></details>

Yes, will fix this :pray: 

___
*[a discussion](https://reviewable.io/reviews/ocadotechnology/rapid-router/1343#-N3uSUhu8Rv0ODXd5VQS:-N3xpm4Z9KuBnLL3ZTXn:bjhzo75) (no related file):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>



Then, as Albert Einstein I shared with Leonardo (student), and then when I logged in as Leonardo and went to play the level it showed Portaladmin's name in brackets. Should that name be the level owner or the name of the person who shared it with you?

</blockquote></details>

I think it should be the owner :thinking: we should check with Laura

___
___
*[`game/static/game/js/sharing.js` line 10 at r2](https://reviewable.io/reviews/ocadotechnology/rapid-router/1343#-N3uHnQyASKDA7TSVaEC:-N3xrBcjDGZUEG038zAN:b-tto4ct) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/c7292fe0ed59b0bf14368c0deed53c9d390070f1/game/static/game/js/sharing.js#L10)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Not blocking, do we want to get rid of all the `gettext` since we said we were gonna phase localisation out?
</blockquote></details>

Are we sure we're removing it?
___
*[`game/static/game/js/sharing.js` line 27 at r2](https://reviewable.io/reviews/ocadotechnology/rapid-router/1343#-N3uI0L21zgMXb32vX5Y:-N3xt7FM8RsHg9ppFMGf:b-896fix) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/c7292fe0ed59b0bf14368c0deed53c9d390070f1/game/static/game/js/sharing.js#L27)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Replace `var`s with `let`s please :stuck_out_tongue_winking_eye: 
</blockquote></details>

Done.
___
*[`game/tests/test_level_editor.py` line 234 at r2](https://reviewable.io/reviews/ocadotechnology/rapid-router/1343#-N3uKCMe17XYxkMHl_xY:-N3xr1EK0z9MCihDzKxM:bps6fud) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/c7292fe0ed59b0bf14368c0deed53c9d390070f1/game/tests/test_level_editor.py#L234)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

rogue print
</blockquote></details>

good catch :slightly_smiling_face:

**Review by faucomte97 — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1343#-:-N43S2WECtoYGZqfFgkU:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @razvan-pro)

**Pull request merged**
