### PR TITLE
Added caching of level decor

### PR DESCRIPTION
**Pull request by paulheideman**
This should hopefully cut out lots of trips to the DB.

I haven't explicitly tested all the scenarios in the the level editor, but it should be a like-for-life switch to the cached method. 

Clearing the cache is triggered when level decor is saved.

### CODE REVIEW

**Comment by mikebryant** [comment]
See #736, which eliminates all trips to the database of this type

**Comment by paulheideman** [comment]
@mikebryant: That can help too. Massive change though and the tests aren't passing. When you get the tests passing then the two changes can work together because this is caching LevelDecor as well. Although I don't really see why you would want to do that massive upheaval.

**Comment by mikebryant** [comment]
Only one test (the api, which isn't being used by anything, and it's being worked on)

The reasoning is the Decor table isn't even referenced from the code pulling in decor (That model stores a string reference) - so it being in the database is adding nothing but additional load for us.

**Comment by paulheideman** [comment]
We should probably continue the discussion on #736 because I don't think these changes are mutually exclusive.

**Pull request merged**
