### PR TITLE
feat: remove direct drive arrows

### PR DESCRIPTION
**Pull request by razvan-pro**
## Description

* Removed the `direct_drive` attribute from the `Level` model and all relations to it from the frontend. This will remove the direct drive arrows mentioned in #1662.
* Replaced the "Go" button references in the level descriptions with the "Play" button.
* Renamed CSS class `.direct_drive_button` to `.zoom_pan_button` as it's only used for the zoom buttons now.
* Removed `_setupDirectDriveListeners` JS functions as it's no longer used when the direct drive buttons are removed.
* Removed the "Go" button SVG. Note that the other assets are still in use by the code blocks, so they couldn't be removed.

## How Has This Been Tested?

* Ran locally and checked the buttons are not there anymore.
* Went through the levels 1-18 descriptions to check for references to the direct drive buttons.

## Screenshots
127 0 0 1_8000_rapidrouter_1_
_Direct drive buttons removed_

127 0 0 1_8000_rapidrouter_1_ (1)
_Go button replaced with Play icon and text in level description_

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have linked this PR to a ZenHub Issue.

- - -
This change is [Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1743)

### CODE REVIEW

**Comment by razvan-pro** [comment]
@faucomte97 Do I really need to make my email address public on a GitHub page to sign the agreement? 😬 I like the idea of validating this automatically, but I'm sure there is a better way that doesn't involve making personal information publicly available. E.g. adding the private GitHub email address should work technically; storing the usernames and email addresses in a database and making an API endpoint to check the GitHub username rather than the email address would also work.

**Comment by faucomte97** [comment]
@razvan-pro No worries about that atm, we are about to put in place a completely new system which won't require contributors to publicise their email address. We're essentially building a "contributor service" which will allow users to login via Github, and agree to the contributor agreement directly on there without needing to a) edit the contributor agreement file and b) respond to an email - so it'll be a lot smoother 🙂 
You can check the code for it [here](https://github.com/ocadotechnology/codeforlife-contributor-backend) 😄 

I can let you know once we've deployed this so you don't need to follow the old process

**Comment by faucomte97** [comment]
@razvan-pro thanks 😃 Unfortunately I don't think we'll have the service up and running by the end of the month...

We were thinking, would you be happy to use a "temporary" email address for this purpose? Like a new gmail address for example that you'd use only for contributing - you could have that be public and the we could then verify it, until we release the new service.

What this means though is that you'd need to close this PR and make a new one authored by that new email address, but hopefully it shouldn't take too long 😬 

Let us know what you think

**Comment by razvan-pro** [comment]
@faucomte97 I was about to do that, but it looks like if I remove the email address later from my account, the commits won't be associated with my account anymore 😬 so I'd have to keep the temporary email address. I think I'll wait for the new service (it's fine if it's outside hacktoberfest). I assume adding the private github email to the list won't work, right? From what I saw, there's an action that sends the agreement automatically, so I wouldn't want to break things 🙂

**Review by faucomte97 — APPROVED** [review]
:lgtm:

> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1743#-:-O9jIUYt-hh-YCk96yI-:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @razvan-pro)

**Pull request merged**
