### PR TITLE
feat: Level moderation

### PR DESCRIPTION
**Pull request by razvan-pro**
This change is [Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1282)

### CODE REVIEW

**Review by faucomte97 — CHANGES_REQUESTED** [review]
> Reviewed 17 of 17 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1282)* status: all files reviewed, 11 unresolved discussions (waiting on @razvan-pro)

___
*[game/static/game/js/level_moderation.js, line 27 at r1](https://reviewable.io/reviews/ocadotechnology/rapid-router/1282#-MtNQWgoBtvzS91yAo-T:-MtNQWgoBtvzS91yAo-U:b6rvbie) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/d97581da6b78b26c4e6e5fb28250b4885d9b0e0e/game/static/game/js/level_moderation.js#L27)):*
> ```JavaScript
> 
> function confirmDelete() {
>   console.log(levelID);
> ```

Do we need this `console.log`?
___
*[game/templates/game/level_moderation.html, line 3 at r1](https://reviewable.io/reviews/ocadotechnology/rapid-router/1282#-MtNRMDrD_I3msShzfGk:-MtNRMDrD_I3msShzfGl:bm2b87j) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/d97581da6b78b26c4e6e5fb28250b4885d9b0e0e/game/templates/game/level_moderation.html#L3)):*
> ```HTML
> {% extends 'game/base.html' %}
> {% load static %}
> {% load i18n %}
> ```

Please remove this and anything else in this file related to Crowdin and translations :pray: 
___
*[game/templates/game/level_moderation.html, line 31 at r1](https://reviewable.io/reviews/ocadotechnology/rapid-router/1282#-MtNRRib3kv8iZveC1LA:-MtNRRib3kv8iZveC1LB:bjon6j) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/d97581da6b78b26c4e6e5fb28250b4885d9b0e0e/game/templates/game/level_moderation.html#L31)):*
> ```HTML
> 
> {% block nav_ocargo_moderate %}
> <a class="button button--secondary button--secondary--light sub-nav--teacher-active" href="{% url 'level_moderation' %}">{% trans "Moderate" %}</a>
> ```

Like this `{% trans $}`
___
*[game/templates/game/level_moderation.html, line 68 at r1](https://reviewable.io/reviews/ocadotechnology/rapid-router/1282#-MtNRZID6Yq6aafyYDaf:-MtNRZID6Yq6aafyYDag:b7ss6dt) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/d97581da6b78b26c4e6e5fb28250b4885d9b0e0e/game/templates/game/level_moderation.html#L68)):*
> ```HTML
>                                     {% endfor %}
>                                 </ul>
>             
> ```

Whitespaces
___
*[game/templates/game/level_moderation.html, line 117 at r1](https://reviewable.io/reviews/ocadotechnology/rapid-router/1282#-MtNRmKTDXcKvTwTSGy1:-MtNRmKTDXcKvTwTSGy2:b-79jk8t) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/d97581da6b78b26c4e6e5fb28250b4885d9b0e0e/game/templates/game/level_moderation.html#L117)):*
> ```HTML
>                         <td><small>{{level.shared_with}}</small></td>
>                         <td class="text-center">
>                             <button class="button button--small button--primary play" value={{level.id}}>{% trans "Play" %}</button>
> ```

Remove `{% trans %}`
___
*[game/templates/game/level_moderation.html, line 121 at r1](https://reviewable.io/reviews/ocadotechnology/rapid-router/1282#-MtNRt6b1kcNosw4MV3b:-MtNRt6b1kcNosw4MV3c:b-79jk8t) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/d97581da6b78b26c4e6e5fb28250b4885d9b0e0e/game/templates/game/level_moderation.html#L121)):*
> ```HTML
>                         <td class="text-center">
>                             <button class="button button--small button--primary--danger button--icon delete" value={{level.id}}>
>                                 {% trans "Delete" %}<span class="iconify" data-icon="mdi:delete-outline"></span>
> ```

Remove `{% trans %}`
___
*[game/templates/game/level_moderation.html, line 132 at r1](https://reviewable.io/reviews/ocadotechnology/rapid-router/1282#-MtNRubE2gxn_CduG3RH:-MtNRubE2gxn_CduG3RI:b-79jk8t) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/d97581da6b78b26c4e6e5fb28250b4885d9b0e0e/game/templates/game/level_moderation.html#L132)):*
> ```HTML
>         {% else %}
>             {% if thead %}
>             <p>{% trans "No levels found." %}</p>
> ```

Remove `{% trans %}`
___
*[game/templates/game/level_moderation.html, line 134 at r1](https://reviewable.io/reviews/ocadotechnology/rapid-router/1282#-MtNRvFACX65H3FTNBxH:-MtNRvFACX65H3FTNBxI:b-79jk8t) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/d97581da6b78b26c4e6e5fb28250b4885d9b0e0e/game/templates/game/level_moderation.html#L134)):*
> ```HTML
>             <p>{% trans "No levels found." %}</p>
>             {% else %}
>             <p>{% trans "Select a class to view the levels created by students." %}</p>
> ```

Remove `{% trans %}`
___
*[game/tests/test_level_moderation.py, line 94 at r1](https://reviewable.io/reviews/ocadotechnology/rapid-router/1282#-MtNSMNTDtW6qOM1kxSM:-MtNSMNTDtW6qOM1kxSN:b58uptb) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/d97581da6b78b26c4e6e5fb28250b4885d9b0e0e/game/tests/test_level_moderation.py#L94)):*
> ```Python
>         )
> 
>     def create_custom_level(self, level_name):
> ```

Not blocking, but should this be in `test_utils` or whatever the folder is called maybe?
___
*[game/views/level_moderation.py, line 9 at r1](https://reviewable.io/reviews/ocadotechnology/rapid-router/1282#-MtNSu3VEVzduhM9FlBR:-MtNSu3VEVzduhM9FlBS:b-rtl9vg) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/d97581da6b78b26c4e6e5fb28250b4885d9b0e0e/game/views/level_moderation.py#L9)):*
> ```Python
> from django.http import Http404, HttpResponse
> from django.shortcuts import render, get_object_or_404
> from django.utils.translation import ugettext
> ```

Maybe see if you can remove this import if you can remove all `ugettext` from this file
___
*[game/views/level_moderation.py, line 84 at r1](https://reviewable.io/reviews/ocadotechnology/rapid-router/1282#-MtNSkZ01S7JSTv0Z9vJ:-MtNSkZ01S7JSTv0Z9vK:b3f0w48) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/d97581da6b78b26c4e6e5fb28250b4885d9b0e0e/game/views/level_moderation.py#L84)):*
> ```Python
> 
>     table_headers = [
>         ugettext("Student"),
> ```

Remove all `ugettext` and just use the string please :pray:

**Review by faucomte97 — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1282#-:-MtO6QvH5T_VwlBwZabq:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @razvan-pro)

**Review by razvan-pro — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1282)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @razvan-pro)

___
*[game/static/game/js/level_moderation.js, line 27 at r1](https://reviewable.io/reviews/ocadotechnology/rapid-router/1282#-MtNQWgoBtvzS91yAo-T:-MtO-AtxBTASyok7m1O8:b-3o35j1) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/d97581da6b78b26c4e6e5fb28250b4885d9b0e0e/game/static/game/js/level_moderation.js#L27)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Do we need this `console.log`?
</blockquote></details>

no :sweat_smile: 
___
*[game/templates/game/level_moderation.html, line 3 at r1](https://reviewable.io/reviews/ocadotechnology/rapid-router/1282#-MtNRMDrD_I3msShzfGk:-MtO-D509pmoLlSf5Un4:b4c9lyr) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/d97581da6b78b26c4e6e5fb28250b4885d9b0e0e/game/templates/game/level_moderation.html#L3)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Please remove this and anything else in this file related to Crowdin and translations :pray: 
</blockquote></details>

:thumbsup: 
___
*[game/templates/game/level_moderation.html, line 31 at r1](https://reviewable.io/reviews/ocadotechnology/rapid-router/1282#-MtNRRib3kv8iZveC1LA:-MtO-_CIAZKzIGOXoZ2I:b-896fix) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/d97581da6b78b26c4e6e5fb28250b4885d9b0e0e/game/templates/game/level_moderation.html#L31)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Like this `{% trans $}`
</blockquote></details>

Done.
___
*[game/templates/game/level_moderation.html, line 68 at r1](https://reviewable.io/reviews/ocadotechnology/rapid-router/1282#-MtNRZID6Yq6aafyYDaf:-MtO-caj0qJKdiVbYU8G:b-896fix) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/d97581da6b78b26c4e6e5fb28250b4885d9b0e0e/game/templates/game/level_moderation.html#L68)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Whitespaces
</blockquote></details>

Done.
___
*[game/templates/game/level_moderation.html, line 117 at r1](https://reviewable.io/reviews/ocadotechnology/rapid-router/1282#-MtNRmKTDXcKvTwTSGy1:-MtO-dUjEXtOtSTBK4RG:b-896fix) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/d97581da6b78b26c4e6e5fb28250b4885d9b0e0e/game/templates/game/level_moderation.html#L117)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Remove `{% trans %}`
</blockquote></details>

Done.
___
*[game/templates/game/level_moderation.html, line 121 at r1](https://reviewable.io/reviews/ocadotechnology/rapid-router/1282#-MtNRt6b1kcNosw4MV3b:-MtO-dlB5cBwgaCt2nIx:b-896fix) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/d97581da6b78b26c4e6e5fb28250b4885d9b0e0e/game/templates/game/level_moderation.html#L121)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Remove `{% trans %}`
</blockquote></details>

Done.
___
*[game/templates/game/level_moderation.html, line 132 at r1](https://reviewable.io/reviews/ocadotechnology/rapid-router/1282#-MtNRubE2gxn_CduG3RH:-MtO-e5dDPfiPbxf9Ptn:b-896fix) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/d97581da6b78b26c4e6e5fb28250b4885d9b0e0e/game/templates/game/level_moderation.html#L132)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Remove `{% trans %}`
</blockquote></details>

Done.
___
*[game/templates/game/level_moderation.html, line 134 at r1](https://reviewable.io/reviews/ocadotechnology/rapid-router/1282#-MtNRvFACX65H3FTNBxH:-MtO-eLW9JhNGTQCflqr:b-896fix) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/d97581da6b78b26c4e6e5fb28250b4885d9b0e0e/game/templates/game/level_moderation.html#L134)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Remove `{% trans %}`
</blockquote></details>

Done.
___
*[game/tests/test_level_moderation.py, line 94 at r1](https://reviewable.io/reviews/ocadotechnology/rapid-router/1282#-MtNSMNTDtW6qOM1kxSM:-MtO2Yjs56lGprzCgoEK:bg6iecr) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/d97581da6b78b26c4e6e5fb28250b4885d9b0e0e/game/tests/test_level_moderation.py#L94)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Not blocking, but should this be in `test_utils` or whatever the folder is called maybe?
</blockquote></details>

Good point, I didn't know there's one already there, thank you :pray: 
___
*[game/views/level_moderation.py, line 9 at r1](https://reviewable.io/reviews/ocadotechnology/rapid-router/1282#-MtNSu3VEVzduhM9FlBR:-MtO3DnS5VucDqpJZw6t:b-896fix) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/d97581da6b78b26c4e6e5fb28250b4885d9b0e0e/game/views/level_moderation.py#L9)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Maybe see if you can remove this import if you can remove all `ugettext` from this file
</blockquote></details>

Done.
___
*[game/views/level_moderation.py, line 84 at r1](https://reviewable.io/reviews/ocadotechnology/rapid-router/1282#-MtNSkZ01S7JSTv0Z9vJ:-MtO3DzgAvzdiURsBgRT:b4c9lyr) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/d97581da6b78b26c4e6e5fb28250b4885d9b0e0e/game/views/level_moderation.py#L84)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Remove all `ugettext` and just use the string please :pray: 
</blockquote></details>

:thumbsup:

**Review by faucomte97 — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1282)* status: all files reviewed, 3 unresolved discussions (waiting on @razvan-pro)

___
*[game/templates/game/level_moderation.html, line 25 at r5](https://reviewable.io/reviews/ocadotechnology/rapid-router/1282#-MtOZJJq7LjANuQA7Rn8:-MtOZJJq7LjANuQA7Rn9:bgcau0) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/069b12b555cdfd448998f84b5e82afd676973f61/game/templates/game/level_moderation.html#L25)):*
> ```HTML
> {% block header %}
> <section class="banner banner--rapid-router">
>     Rapid Router logo
> ```

This should really be moved to `common` yeah since it creates a new circular dependency :confused: 
___
*[game/templates/game/level_selection.html, line 54 at r5](https://reviewable.io/reviews/ocadotechnology/rapid-router/1282#-MtOZPGZ0j1XZem9nVv3:-MtOZPGZ0j1XZem9nVv4:buo9nmt) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/069b12b555cdfd448998f84b5e82afd676973f61/game/templates/game/level_selection.html#L54)):*
> ```HTML
> {% block header %}
> <section class="banner banner--rapid-router">
>     Rapid Router logo
> ```

Same here
___
*[game/templates/game/scoreboard.html, line 35 at r5](https://reviewable.io/reviews/ocadotechnology/rapid-router/1282#-MtOZQLC6b8vq9Gkh6vM:-MtOZQLC6b8vq9Gkh6vN:buo9nmt) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/069b12b555cdfd448998f84b5e82afd676973f61/game/templates/game/scoreboard.html#L35)):*
> ```HTML
> {% block header %}
> <section class="banner banner--rapid-router">
>     Rapid Router logo
> ```

Same here

**Review by faucomte97 — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1282)* status: all files reviewed, 1 unresolved discussion (waiting on @razvan-pro)

___
*[game/templates/game/level_moderation.html, line 25 at r5](https://reviewable.io/reviews/ocadotechnology/rapid-router/1282#-MtOZJJq7LjANuQA7Rn8:-MtbXFHC9KKqLK7zVErw:b-yd9zyz) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/069b12b555cdfd448998f84b5e82afd676973f61/game/templates/game/level_moderation.html#L25)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

This should really be moved to `common` yeah since it creates a new circular dependency :confused: 
</blockquote></details>

Looks good but I can't see the new image in common?

**Review by razvan-pro — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1282)* status: all files reviewed, 1 unresolved discussion (waiting on @faucomte97)

___
*[game/templates/game/level_moderation.html, line 25 at r5](https://reviewable.io/reviews/ocadotechnology/rapid-router/1282#-MtOZJJq7LjANuQA7Rn8:-MtbZabj7hE27z-_wkEp:b7km8wi) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/069b12b555cdfd448998f84b5e82afd676973f61/game/templates/game/level_moderation.html#L25)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Looks good but I can't see the new image in common?
</blockquote></details>

It's here: https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/1723#-
:slightly_smiling_face:

**Review by faucomte97 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1282)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @razvan-pro)

___
*[game/templates/game/level_moderation.html, line 25 at r5](https://reviewable.io/reviews/ocadotechnology/rapid-router/1282#-MtOZJJq7LjANuQA7Rn8:-Mtb_L3M8w-BZ-2QHRoF:b-vzmm38) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/069b12b555cdfd448998f84b5e82afd676973f61/game/templates/game/level_moderation.html#L25)):*
<details><summary><i>Previously, razvan-pro (Razvan Mahu) wrote…</i></summary><blockquote>

It's here: https://reviewable.io/reviews/ocadotechnology/codeforlife-portal/1723#-
:slightly_smiling_face: 
</blockquote></details>

Oh yeah I missed it :man_facepalming:

**Review by faucomte97 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1282#-:-Mtb_P232lMoDT_lRvaC:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @razvan-pro)

**Pull request merged**
