### PR TITLE
feat: Upgrade to Django 2.2

### PR DESCRIPTION
**Pull request by faucomte97**
This change is [Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1132)

### CODE REVIEW

**Review by mrniket — CHANGES_REQUESTED** [review]
> Reviewed 19 of 28 files at r1.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1132)* status: 19 of 28 files reviewed, 1 unresolved discussion (waiting on @faucomte97)

___
*[setup.py, line 24 at r1](https://reviewable.io/reviews/ocadotechnology/rapid-router/1132#-MLRw9_V0hwyrSXduY7O:-MLRw9_V0hwyrSXduY7P:b-9boy4c) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/85d14f37982a48c33fecbf50818971cb85cd8392/setup.py#L24)):*
> ```Python
>     include_package_data=True,
>     install_requires=[
>         "django>=1.11.24, <= 2.0.0",
> ```

we only need to support 2.0 if we are running a long-running feature branch

**Review by faucomte97 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1132)* status: 19 of 28 files reviewed, 1 unresolved discussion (waiting on @faucomte97 and @mrniket)

___
*[setup.py, line 24 at r1](https://reviewable.io/reviews/ocadotechnology/rapid-router/1132#-MLRw9_V0hwyrSXduY7O:-MLSLtI7A-_B8hfs3TDg:b-896fix) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/85d14f37982a48c33fecbf50818971cb85cd8392/setup.py#L24)):*
<details><summary><i>Previously, mrniket (Niket Shah) wrote…</i></summary><blockquote>

we only need to support 2.0 if we are running a long-running feature branch
</blockquote></details>

Done.

**Review by razvan-pro — CHANGES_REQUESTED** [review]
> Reviewed 27 of 28 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1132)* status: all files reviewed, 2 unresolved discussions (waiting on @faucomte97 and @mrniket)

___
*[example_project/example_project/urls.py, line 12 at r2](https://reviewable.io/reviews/ocadotechnology/rapid-router/1132#-MLhPa4VBZqsu3cB76Lr:-MLhPa4VBZqsu3cB76Ls:b73gwe9) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/e23ca5f47f7e8ae437b8c43e37102107572bea13/example_project/example_project/urls.py#L12)):*
> ```Python
> urlpatterns = [
>     url(r"^", include(portal_urls)),
>     url(r"^administration/", include((admin.site.urls[0], "admin"), namespace="admin")),
> ```

FYI: idea in portal PR.
___
*[game/migrations/0001_squashed_0025_levels_ordering_pt1.py, line 5081 at r2](https://reviewable.io/reviews/ocadotechnology/rapid-router/1132#-MLhVGJJ2DV7su4fSMWq:-MLhVGJKA_gIejAgL9CC:b9fo7av) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/e23ca5f47f7e8ae437b8c43e37102107572bea13/game/migrations/0001_squashed_0025_levels_ordering_pt1.py#L5081)):*
> ```Python
>                 (
>                     "first_level",
>                     models.ForeignKey(to="game.Level", on_delete=models.SET_NULL),
> ```

I think we also need `null=True` here if we use `SET_NULL`

**Review by mrniket — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1132)* status: all files reviewed, 1 unresolved discussion (waiting on @faucomte97)

**Review by faucomte97 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1132)* status: all files reviewed, 1 unresolved discussion (waiting on @razvan-pro)

___
*[example_project/example_project/urls.py, line 12 at r2](https://reviewable.io/reviews/ocadotechnology/rapid-router/1132#-MLhPa4VBZqsu3cB76Lr:-MLrUsrLDjkuPwdJIULM:bmfxgaw) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/e23ca5f47f7e8ae437b8c43e37102107572bea13/example_project/example_project/urls.py#L12)):*
<details><summary><i>Previously, razvan-pro (Razvan Mahu) wrote…</i></summary><blockquote>

FYI: idea in portal PR.
</blockquote></details>

Done :)
___
*[game/migrations/0001_squashed_0025_levels_ordering_pt1.py, line 5081 at r2](https://reviewable.io/reviews/ocadotechnology/rapid-router/1132#-MLhVGJJ2DV7su4fSMWq:-MLrVjZk3K6sjy4uSvIJ:b-b3z218) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/e23ca5f47f7e8ae437b8c43e37102107572bea13/game/migrations/0001_squashed_0025_levels_ordering_pt1.py#L5081)):*
<details><summary><i>Previously, razvan-pro (Razvan Mahu) wrote…</i></summary><blockquote>

I think we also need `null=True` here if we use `SET_NULL`
</blockquote></details>

Actually, this field was removed from the Episode model in migration 0043 so I believe there is no need to specify this.

**Review by razvan-pro — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1132)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @faucomte97)

___
*[game/migrations/0001_squashed_0025_levels_ordering_pt1.py, line 5081 at r2](https://reviewable.io/reviews/ocadotechnology/rapid-router/1132#-MLhVGJJ2DV7su4fSMWq:-MLs4QQ3D2KBhoht5bq3:bjucuep) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/e23ca5f47f7e8ae437b8c43e37102107572bea13/game/migrations/0001_squashed_0025_levels_ordering_pt1.py#L5081)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Actually, this field was removed from the Episode model in migration 0043 so I believe there is no need to specify this.
</blockquote></details>

oh ok :)

**Review by mrniket — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1132)* status: all files reviewed, 1 unresolved discussion (waiting on @faucomte97)

___
*[example_project/example_project/urls.py, line 12 at r2](https://reviewable.io/reviews/ocadotechnology/rapid-router/1132#-MLhPa4VBZqsu3cB76Lr:-MLvtbr-5xfdRHtOE6oV:bdpxpau) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/e23ca5f47f7e8ae437b8c43e37102107572bea13/example_project/example_project/urls.py#L12)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Done :)
</blockquote></details>

administration 😊

**Review by faucomte97 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1132)* status: 27 of 28 files reviewed, 1 unresolved discussion (waiting on @mrniket and @razvan-pro)

___
*[example_project/example_project/urls.py, line 12 at r2](https://reviewable.io/reviews/ocadotechnology/rapid-router/1132#-MLhPa4VBZqsu3cB76Lr:-MLvu6SW3D7RIkR9311y:b-9gwj7c) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/e23ca5f47f7e8ae437b8c43e37102107572bea13/example_project/example_project/urls.py#L12)):*
<details><summary><i>Previously, mrniket (Niket Shah) wrote…</i></summary><blockquote>

administration 😊 
</blockquote></details>

:upside_down_face:

**Review by mrniket — APPROVED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1132)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @faucomte97)

**Review by razvan-pro — APPROVED** [review]
> Reviewed 1 of 1 files at r4, 3 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1132)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @faucomte97)

**Review by razvan-pro — APPROVED** [review]
> Reviewed 1 of 33 files at r6, 32 of 33 files at r7, 5 of 5 files at r8.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1132)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @faucomte97)

**Pull request merged**
