### PR TITLE
feat: add python den game pages

### PR DESCRIPTION
**Pull request by evemartin**
This change is [Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1682)

### CODE REVIEW

**Review by faucomte97 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 7 files at r1, 2 of 3 files at r2, 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1682)* status: all files reviewed, 5 unresolved discussions (waiting on @evemartin)

___
*[`game/static/game/css/backgrounds.css` line 25 at r3](https://reviewable.io/reviews/ocadotechnology/rapid-router/1682#-O4LyTTO2AfnaIVN-BBE:-O4LyTTO2AfnaIVN-BBF:b2l22xq) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/d64e0ff96f5d30ed9116aa741c5a9e8bb3b0f3c3/game/static/game/css/backgrounds.css#L25)):*
> ```CSS
> .bg--advanced {
>     background-color: #754fc8;
> }
> ```

Remove these since it seems we don't need it anymore? Check for other instances of these keywords too please



_Code quote:_
```CSS
.bg--hard {
    background-color: #8967d3;
}

.bg--advanced {
    background-color: #754fc8;
}
```
___
*[`game/static/game/css/backgrounds.css` line 37 at r3](https://reviewable.io/reviews/ocadotechnology/rapid-router/1682#-O4LyYMvDiIfcrXOQskR:-O4LyYMvDiIfcrXOQskS:b2l22xq) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/d64e0ff96f5d30ed9116aa741c5a9e8bb3b0f3c3/game/static/game/css/backgrounds.css#L37)):*
> ```CSS
> .bg--loops-coming-soon {
>     background-color: #CBCBCB;
> }
> ```

Remove these since it seems we don't need it anymore? Check for other instances of these keywords too please



_Code quote:_
```CSS
.bg--loops {
    background-color: #3F3F3F;
}

.bg--loops-coming-soon {
    background-color: #CBCBCB;
}
```
___
*[`game/static/game/css/game.css` line 415 at r3](https://reviewable.io/reviews/ocadotechnology/rapid-router/1682#-O4M0tRm0gW7OHgSjqF4:-O4M0tRm0gW7OHgSjqF5:b-tptluu) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/d64e0ff96f5d30ed9116aa741c5a9e8bb3b0f3c3/game/static/game/css/game.css#L415)):*
> ```CSS
>     width: 120px;
>     opacity: 0;
> }
> ```

The Exit button gets too small when the screen sizes get smaller - maybe see if you can set a minimum size so it's still visible enough



_Code quote:_
```CSS
.header-exit-button {
    position: absolute;
    left: 0px;
    height: 50px;
    width: 120px;
    opacity: 0;
}
```
___
*[`game/static/game/css/game.css` line 423 at r3](https://reviewable.io/reviews/ocadotechnology/rapid-router/1682#-O4M16jP2cmgXpJQgNFq:-O4M16jQ6SuroqoPOq9k:bz26kpy) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/d64e0ff96f5d30ed9116aa741c5a9e8bb3b0f3c3/game/static/game/css/game.css#L423)):*
> ```CSS
> :root {
>     --rpf-button-primary-background-color: #ffd23b !important;
>     --rpf-button-primary-text-color: black !important;
> ```

What are these for? :thinking: 



_Code quote:_
```CSS
    --rpf-button-primary-background-color: #ffd23b !important;
    --rpf-button-primary-text-color: black !important;
```
___
*[`game/templates/game/game.html` line 165 at r3](https://reviewable.io/reviews/ocadotechnology/rapid-router/1682#-O4M1JLd1qtwSf1ueDkr:-O4M1JLe7xZy5ybBC0RO:bgs1iv6) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/d64e0ff96f5d30ed9116aa741c5a9e8bb3b0f3c3/game/templates/game/game.html#L165)):*
> ```HTML
>       <input type="radio" name="tabs" id="python_radio">
>       <label for="python_radio">
>         <span>{% trans "Python Den" %}</span>
> ```

Clicking this makes the workspace and console windows disappear? :exploding_head:

**Review by evemartin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1682)* status: all files reviewed, 5 unresolved discussions (waiting on @faucomte97)

___
*[`game/static/game/css/game.css` line 415 at r3](https://reviewable.io/reviews/ocadotechnology/rapid-router/1682#-O4M0tRm0gW7OHgSjqF4:-O4MKhFr1BTwWYAoidGc:bfu6rk2) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/d64e0ff96f5d30ed9116aa741c5a9e8bb3b0f3c3/game/static/game/css/game.css#L415)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

The Exit button gets too small when the screen sizes get smaller - maybe see if you can set a minimum size so it's still visible enough
</blockquote></details>

As we discussed during the handover call: the weird thing about this is that the exit button icon is actually also part of the header, I'm just using an invisible button placed over the header to actually function as the button - this makes it difficult to resize the exit button. However, this was originally added because the IDE levels won't have the exit tab button even though all the other levels do, so since we're pushing the IDE stuff back, we might be able to just crop the header for now
___
*[`game/static/game/css/game.css` line 423 at r3](https://reviewable.io/reviews/ocadotechnology/rapid-router/1682#-O4M16jP2cmgXpJQgNFq:-O4MFzl3DqPRuRcufWbp:b2spv5o) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/d64e0ff96f5d30ed9116aa741c5a9e8bb3b0f3c3/game/static/game/css/game.css#L423)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

What are these for? :thinking:
</blockquote></details>

These were to change the color of the IDE's run button but aren't needed anymore!

**Review by faucomte97 — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1682)* status: 7 of 8 files reviewed, 4 unresolved discussions (waiting on @evemartin)

**Review by faucomte97 — COMMENTED** [review]
> Reviewed 3 of 4 files at r5, 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1682)* status: 7 of 8 files reviewed, 1 unresolved discussion (waiting on @evemartin)

**Review by faucomte97 — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1682)* status: 7 of 8 files reviewed, 1 unresolved discussion (waiting on @evemartin)

**Review by faucomte97 — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1682#-:-O4jP18G7ip6pWnz0eqN:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @evemartin)

**Pull request merged**
