### PR TITLE
feat: Disable algorithm scoring for levels 1-12

### LINKED ISSUE #1286: Remove Algorithm score from lower levels in Rapid Router
## Task Description

This is not needed in the most simplistic levels as it is impossible to add inefficient code to such simple routes - it is also confusing for younger users.

When introduced - let's add in a bit of text explaining what it is about.

## Acceptance Criteria

Remove from first 12 levels

## Copywrite Requirements

Text for introduction to Algorithm score - add to existing and explain why important: _Often there is more than one way to get to the house. The route that needs the fewest directions is usually best. Help the van find the shortest route to the house._

## Analytics Requirements
Feedback survey

### PR DESCRIPTION
**Pull request by sebp999**
## Description

Fixes #1286. Adds a field `disable_algorithm_scoring` and sets it to True for Levels 1-12. If the algorithm scoring is disabled for a level, no coins or score will appear in the popup for a successful try
## How Has This Been Tested?
By adapting and running Selenium tests

## Checklist:
- [ x ] My change requires a change to the documentation.
- [ x ] I have updated the documentation accordingly.
- [ ✅ ] I have linked this PR to a ZenHub Issue.

- - -
This change is [Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1409)

### CODE REVIEW

**Comment by sebp999** [comment]
*[`game/models.py` line 137 at r1](https://reviewable.io/reviews/ocadotechnology/rapid-router/1409#-NMoEyPA6dvPsA1a1Ypc:-NMoKGjJ27xGadk8z8F7:bhv2c2n) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/dbe471c58803e4a350293a741509143005b01709/game/models.py#L137)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

I'm surprised we needed to add this field, some levels already have no algorithm score (like the Python levels). I'm confused as to how that was done then if the field didn't already exist?
</blockquote></details>

I think it's because the Python levels don't have a model solution and pathFinder.js l 46 uses the length of the model solution to see if it should get an algorithm score



_Code snippet (i):_
```Python
In [7]: Level.objects.get(name="1").model_solution
Out[7]: '[1]'

In [8]: Level.objects.get(name="96").model_solution
Out[8]: '[]'
```



_Code snippet (ii):_
```Python
    if (this.modelSolution.length > 0) {
```

**Comment by sebp999** [comment]
*[`game/migrations/0081_first_12_levels_no_algo_score.py` line 11 at r1](https://reviewable.io/reviews/ocadotechnology/rapid-router/1409#-NMoFbOZ3SJabPSPQGUq:-NMoNbi--r5kR49Jdt2f:b-xqjzm8) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/dbe471c58803e4a350293a741509143005b01709/game/migrations/0081_first_12_levels_no_algo_score.py#L11)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

What happens to the users who have already completed levels 1-13? Does their score get updated to reflect these changes or will they end up having something like 20/10?
</blockquote></details>

Yes I think you're right.  I forgot about the scoreboard.  What would we like to happen?

**Comment by sebp999** [comment]
*[`game/migrations/0081_first_12_levels_no_algo_score.py` line 11 at r1](https://reviewable.io/reviews/ocadotechnology/rapid-router/1409#-NMoFbOZ3SJabPSPQGUq:-NMoNp0s6v321zAc2Xvo:b9m0wne) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/dbe471c58803e4a350293a741509143005b01709/game/migrations/0081_first_12_levels_no_algo_score.py#L11)):*
<details><summary><i>Previously, sebp999 wrote…</i></summary><blockquote>

Yes I think you're right.  I forgot about the scoreboard.  What would we like to happen?
</blockquote></details>

Convert the 20s into 10s?  Is it possible to get less than 10 for the algorithm in any of the levels 1-12?  If all the users lose 120 points from their scoreboards, how does that affect their use?  Or do we keep 240 for those who have done it already but the ones who start it tomorrow have a lower baseline? Or should we give 20 coins for the correct route, instead of 10?

**Review by sebp999 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1409)* status: all files reviewed, 2 unresolved discussions (waiting on @faucomte97 and @KamilPawel)

___
*[`game/migrations/0081_first_12_levels_no_algo_score.py` line 11 at r1](https://reviewable.io/reviews/ocadotechnology/rapid-router/1409#-NMoFbOZ3SJabPSPQGUq:-NMoWwQFE4q1lxAtTgWB:b-hvb3xx) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/dbe471c58803e4a350293a741509143005b01709/game/migrations/0081_first_12_levels_no_algo_score.py#L11)):*
<details><summary><i>Previously, sebp999 wrote…</i></summary><blockquote>

Convert the 20s into 10s?  Is it possible to get less than 10 for the algorithm in any of the levels 1-12?  If all the users lose 120 points from their scoreboards, how does that affect their use?  Or do we keep 240 for those who have done it already but the ones who start it tomorrow have a lower baseline? Or should we give 20 coins for the correct route, instead of 10?
</blockquote></details>

I think the only way to do it is give 20 for route score, otherwise the scoreboard is unfair on those who did the level later than others, and the users are mainly children so unfair doesn't work.  Therefore I'm going to make routes 1-12 have route score 20.

**Comment by faucomte97** [comment]
Superseded by #1414

**Pull request closed without merging**
