### PR TITLE
feat: loop level links

### PR DESCRIPTION
**Pull request by SKairinos**
This change is [Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1507)

### CODE REVIEW

**Review by faucomte97 — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1507)* status: all files reviewed, 3 unresolved discussions (waiting on @SKairinos)

___
*[`game/messages.py` line 2435 at r1](https://reviewable.io/reviews/ocadotechnology/rapid-router/1507#-Ni0HgylBj5XcvtQKdPS:-Ni0HgylBj5XcvtQKdPT:b-6r40ay) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/9c7b0a91bef907da2bc4d8b4f8748208cc7c0522/game/messages.py#L2435)):*
> ```Python
>     lambda: "Which way to turn? This way or that way?",
>     lambda: build_description(title_level115(), "Try to find the shortest route using Python code only. You are getting really good at this!"),
>     lambda: "If you are stuck on this one, check that the you are using the Python commands accurately. Click the Py Commands button to help you.",
> ```

please remove the unnecessary "the" after "check that"
___
*[`game/migrations/0084_loop_levels.py` line 229 at r1](https://reviewable.io/reviews/ocadotechnology/rapid-router/1507#-Ni0KwG94pcseDvUl60x:-Ni0KwG94pcseDvUl60y:b-tmqs7i) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/9c7b0a91bef907da2bc4d8b4f8748208cc7c0522/game/migrations/0084_loop_levels.py#L229)):*
> ```Python
>         episode=episode_12,
>         path="",
>         # next_level=level_123, TODO: connect them when the next levels are enabled.
> ```

If we do this it stops the user from loading the next level from the UI but the users _could_ technically still load levels 122 onwards by putting the level number in the URL. Do we want to add something in to prevent this?
___
*[`game/migrations/0084_loop_levels.py` line 310 at r1](https://reviewable.io/reviews/ocadotechnology/rapid-router/1507#-Ni0LEWVCFk9r-NiueOp:-Ni0LEWVCFk9r-NiueOq:bbc488a) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/9c7b0a91bef907da2bc4d8b4f8748208cc7c0522/game/migrations/0084_loop_levels.py#L310)):*
> ```Python
> 
> class Migration(migrations.Migration):
>     dependencies = [("game", "0083_add_cows_to_existing_levels")]
> ```

You haven't merged in master - the latest PR brings in migrations 84 and 85 so you'll need to rename this one 86 and make it dependent on 85 instead.

**Review by SKairinos — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1507)* status: 4 of 7 files reviewed, 3 unresolved discussions (waiting on @faucomte97)

___
*[`game/messages.py` line 2435 at r1](https://reviewable.io/reviews/ocadotechnology/rapid-router/1507#-Ni0HgylBj5XcvtQKdPS:-Ni0pqNT2mEJRiC8V3Ze:b-896fix) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/9c7b0a91bef907da2bc4d8b4f8748208cc7c0522/game/messages.py#L2435)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

please remove the unnecessary "the" after "check that"
</blockquote></details>

Done.
___
*[`game/migrations/0084_loop_levels.py` line 229 at r1](https://reviewable.io/reviews/ocadotechnology/rapid-router/1507#-Ni0KwG94pcseDvUl60x:-Ni0pvxj7YAWMjJRv2Jg:b-kstywv) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/9c7b0a91bef907da2bc4d8b4f8748208cc7c0522/game/migrations/0084_loop_levels.py#L229)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

If we do this it stops the user from loading the next level from the UI but the users _could_ technically still load levels 122 onwards by putting the level number in the URL. Do we want to add something in to prevent this?
</blockquote></details>

I think it's fine because it will fail to load the level anyways, letting them know they shouldn't be doing that
___
*[`game/migrations/0084_loop_levels.py` line 310 at r1](https://reviewable.io/reviews/ocadotechnology/rapid-router/1507#-Ni0LEWVCFk9r-NiueOp:-Ni0qxz3Ce-D7o4g5Y1F:b-896fix) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/9c7b0a91bef907da2bc4d8b4f8748208cc7c0522/game/migrations/0084_loop_levels.py#L310)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

You haven't merged in master - the latest PR brings in migrations 84 and 85 so you'll need to rename this one 86 and make it dependent on 85 instead.
</blockquote></details>

Done.

**Review by faucomte97 — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1507)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SKairinos)

**Review by faucomte97 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1507#-:-Ni0uAde1WDu4ZdBdsCO:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SKairinos)

**Pull request merged**
