### PR TITLE
fix: rename v to my_van

### PR DESCRIPTION
**Pull request by KamilPawel**
## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have linked this PR to a Zenhub Issue.

---
This change is [Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1327)

### CODE REVIEW

**Review by razvan-pro — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1327)* status: all files reviewed, 3 unresolved discussions (waiting on @KamilPawel)

___
*[game/static/game/js/blocklyCustomBlocks.js, line 434 at r1](https://reviewable.io/reviews/ocadotechnology/rapid-router/1327#-Mzzc8Cr16ElQCHa4NUG:-Mzzc8Cs0fDZabjAygyS:b-9jr7e) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/eb9a92547005beb150ad2a00ea2dd6499cfec19b/game/static/game/js/blocklyCustomBlocks.js#L434)):*
> ```JavaScript
> 
>     Blockly.Python['cow_crossing'] = function(block) {
>         return ['v.cow_crossing()', Blockly.Python.ORDER_NONE];
> ```

Not sure if used, but we can rename this too :slightly_smiling_face: 
___
*[game/views/level_solutions.py, line 283 at r1](https://reviewable.io/reviews/ocadotechnology/rapid-router/1327#-MzzcdhFEZDJPr8-bm6N:-MzzcdhFEZDJPr8-bm6O:bhh4y1x) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/eb9a92547005beb150ad2a00ea2dd6499cfec19b/game/views/level_solutions.py#L283)):*
> ```Python
>     "python_default": python_default,
>     "blockly_default": blockly_default,
>     "1": '<xml xmlns="http://www.w3.org/1999/xhtml"><block type="start" deletable="false" x="230" y="30"><next><block type="turn_left"></block></next></block></xml>',
> ```

lol :laughing: 
___
*[game/views/scoreboard_csv.py, line 47 at r1](https://reviewable.io/reviews/ocadotechnology/rapid-router/1327#-MzzchIn47fvUcY3FIBQ:-MzzchIn47fvUcY3FIBR:b-p14v8v) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/eb9a92547005beb150ad2a00ea2dd6499cfec19b/game/views/scoreboard_csv.py#L47)):*
> ```Python
>         rows.append(row)
> 
>     writer = csmy_van.writer(response)
> ```

Search&Replace fail :smile:

**Review by KamilPawel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1327)* status: all files reviewed, 2 unresolved discussions (waiting on @razvan-pro)

___
*[game/static/game/js/blocklyCustomBlocks.js, line 434 at r1](https://reviewable.io/reviews/ocadotechnology/rapid-router/1327#-Mzzc8Cr16ElQCHa4NUG:-N-2dcdlD5cVzYiaA-Zo:b-896fix) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/eb9a92547005beb150ad2a00ea2dd6499cfec19b/game/static/game/js/blocklyCustomBlocks.js#L434)):*
<details><summary><i>Previously, razvan-pro (Razvan Mahu) wrote…</i></summary><blockquote>

Not sure if used, but we can rename this too :slightly_smiling_face: 
</blockquote></details>

Done.
___
*[game/views/scoreboard_csv.py, line 47 at r1](https://reviewable.io/reviews/ocadotechnology/rapid-router/1327#-MzzchIn47fvUcY3FIBQ:-N-2e1zF7-GdRdcQwder:b-896fix) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/eb9a92547005beb150ad2a00ea2dd6499cfec19b/game/views/scoreboard_csv.py#L47)):*
<details><summary><i>Previously, razvan-pro (Razvan Mahu) wrote…</i></summary><blockquote>

Search&Replace fail :smile: 
</blockquote></details>

Done.

**Review by razvan-pro — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1327#-:-N-2h8kt9UcoLQz6UwtH:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @KamilPawel)

**Review by faucomte97 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1327)* status: all files reviewed, 1 unresolved discussion (waiting on @KamilPawel)

___
*[game/static/game/js/game.js, line 142 at r4](https://reviewable.io/reviews/ocadotechnology/rapid-router/1327#-N-3VnJ-AFg2v39CQOfi:-N-3VnJ-AFg2v39CQOfj:bmmy2a6) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/fdee17dc300572539756229c1535f7f5956177fe/game/static/game/js/game.js#L142)):*
> ```JavaScript
> 
>   let code = ocargo.pythonControl.getCode()
>   console.log(code)
> ```

Console log :stuck_out_tongue:

**Review by faucomte97 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1327#-:-N-7UQnDA56hangu_DjD:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @KamilPawel)

**Review by razvan-pro — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1327)* status: all files reviewed, 1 unresolved discussion (waiting on @KamilPawel)

___
*[game/static/game/js/game.js, line 153 at r5](https://reviewable.io/reviews/ocadotechnology/rapid-router/1327#-N-7ZBoOE3KTeAAQVcIA:-N-7ZBoOE3KTeAAQVcIB:b2ujhf) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/012e5cfd3b63b80c711f8904988ae7253c5a7669/game/static/game/js/game.js#L153)):*
> ```JavaScript
>     ocargo.Drawing.startPopup(
>       gettext('Oh dear!'),
>       "You can only import 'van' from 'Van'",
> ```

'Van' from 'van' :slightly_smiling_face:

**Review by KamilPawel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1327)* status: 5 of 7 files reviewed, 1 unresolved discussion (waiting on @faucomte97 and @razvan-pro)

___
*[game/static/game/js/game.js, line 153 at r5](https://reviewable.io/reviews/ocadotechnology/rapid-router/1327#-N-7ZBoOE3KTeAAQVcIA:-N-8NPUo5TuthohE-EWD:b-896fix) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/af6843e8ccac6d2dbbc685a98a4afcb54739e295/game/static/game/js/game.js#L153)):*
<details><summary><i>Previously, razvan-pro (Razvan Mahu) wrote…</i></summary><blockquote>

'Van' from 'van' :slightly_smiling_face: 
</blockquote></details>

Done.

**Review by razvan-pro — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1327#-:-N-90C-s62IRg0UPrtEs:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @KamilPawel)

**Pull request merged**
