### PR TITLE
fix: Remove six

### PR DESCRIPTION
**Pull request by faucomte97**
This change is [Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1121)

### CODE REVIEW

**Review by mrniket — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1121)* status: all files reviewed, 1 unresolved discussion (waiting on @faucomte97)

___
*[setup.py, line 30 at r1](https://reviewable.io/reviews/ocadotechnology/rapid-router/1121#-MHu1_qs1TfDig2h9gJI:-MHu1_qtEcERXz5susqV:b-upapyx) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/30a591d2b3a5209534758c5fbf0f9f59a67e7d5c/setup.py#L30)):*
> ```Python
>         "django-pipeline==1.6.14",
>         "djangorestframework>=3.8.2, <3.9.0",
>         "six==1.*",
> ```

is it possible to get rid of six instead? It's a python 2 and 3 compatibility library so we don't really need it anymore

**Review by faucomte97 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1121)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @faucomte97 and @mrniket)

___
*[Pipfile.lock, line 294 at r2](https://reviewable.io/reviews/ocadotechnology/rapid-router/1121#-MHu8p1D0RUcX5qZ0Tp9:-MHu8p1D0RUcX5qZ0TpA:b-8gby61) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/cb1eca4a1d839eb9be1fe4b37b570453b563f62c/Pipfile.lock#L294)):*
> ```
>             "version": "==3.14.0"
>         },
>         "six": {
> ```

Still there :(

**Review by faucomte97 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1121)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @faucomte97 and @mrniket)

___
*[Pipfile.lock, line 221 at r2](https://reviewable.io/reviews/ocadotechnology/rapid-router/1121#-MHuAZvA1R8t6ONOhXDa:-MHuAZvB2o5FDkmcxqVD:b-vb3z1t) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/cb1eca4a1d839eb9be1fe4b37b570453b563f62c/Pipfile.lock#L221)):*
> ```
>             ],
>             "markers": "python_version < '3.8'",
>             "version": "==2.0.0"
> ```

Also this is a breaking change :/ is that OK?

**Review by faucomte97 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1121)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @faucomte97 and @mrniket)

___
*[Pipfile.lock, line 221 at r2](https://reviewable.io/reviews/ocadotechnology/rapid-router/1121#-MHuAZvA1R8t6ONOhXDa:-MHuAdQo-SmTugYtMGQ9:bgem4pk) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/cb1eca4a1d839eb9be1fe4b37b570453b563f62c/Pipfile.lock#L221)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Also this is a breaking change :/ is that OK?
</blockquote></details>

Should we fix the version major version instead?

**Review by mrniket — APPROVED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1121)* status: all files reviewed, 2 unresolved discussions (waiting on @faucomte97)

___
*[Pipfile.lock, line 221 at r2](https://reviewable.io/reviews/ocadotechnology/rapid-router/1121#-MHuAZvA1R8t6ONOhXDa:-MHuHLV38N0ji32kEPEZ:b9hcf39) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/cb1eca4a1d839eb9be1fe4b37b570453b563f62c/Pipfile.lock#L221)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Should we fix the version major version instead?
</blockquote></details>

I think this might not be a breaking change for us, the tests pass which indicate so as well
___
*[Pipfile.lock, line 294 at r2](https://reviewable.io/reviews/ocadotechnology/rapid-router/1121#-MHu8p1D0RUcX5qZ0Tp9:-MHuGx0z5FSzUN8h1M1D:b-1g3536) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/cb1eca4a1d839eb9be1fe4b37b570453b563f62c/Pipfile.lock#L294)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Still there :(
</blockquote></details>

it might be a sub dep of something else we have (or portal for example). which is out of our control (all we can do is upgrade the dep that uses six if that helps). But it's not in RR
___
*[setup.py, line 30 at r1](https://reviewable.io/reviews/ocadotechnology/rapid-router/1121#-MHu1_qs1TfDig2h9gJI:-MHuHHxy4ZLSPOesyVzn:bb6un1j) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/30a591d2b3a5209534758c5fbf0f9f59a67e7d5c/setup.py#L30)):*
<details><summary><i>Previously, mrniket (Niket Shah) wrote…</i></summary><blockquote>

is it possible to get rid of six instead? It's a python 2 and 3 compatibility library so we don't really need it anymore
</blockquote></details>

Done

**Review by mrniket — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1121)* status: all files reviewed, 2 unresolved discussions (waiting on @faucomte97)

**Review by faucomte97 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1121#-:-MHuLCX76t_rVE8UdIrE:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
