### PR TITLE
feat: Implement CSP header

### PR DESCRIPTION
**Pull request by faucomte97**
This change is [Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1239)

### CODE REVIEW

**Review by razvan-pro — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1239)* status: all files reviewed, 1 unresolved discussion (waiting on @faucomte97)

___
*[game/autoconfig.py, line 72 at r1](https://reviewable.io/reviews/ocadotechnology/rapid-router/1239#-Mp7kE7H7JJkjLf6unIN:-Mp7kE7J6wD5VNi8AM9O:b-aa65b2) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/7a33b2a64d0c499093a1c397e6d7a1079d6aa199/game/autoconfig.py#L72)):*
> ```Python
>     "CSP_FRAME_SRC": (
>         f"{domain()}/static/game/image/",
>         "http://www.youtube-nocookie.com/",
> ```

`http`, not `s`? :open_mouth:

**Review by razvan-pro — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1239)* status: all files reviewed, 2 unresolved discussions (waiting on @faucomte97)

___
*[game/autoconfig.py, line 57 at r1](https://reviewable.io/reviews/ocadotechnology/rapid-router/1239#-MpCdtrRCSwaW4lWLoO_:-MpCdtrRCSwaW4lWLoOa:b-8jcof9) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/7a33b2a64d0c499093a1c397e6d7a1079d6aa199/game/autoconfig.py#L57)):*
> ```Python
>     ],
>     "USE_TZ": True,
>     # ----------------------------------------------------------------------------------
> ```

Should this be separate as well to be consistent? :slightly_smiling_face:

**Review by faucomte97 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1239)* status: all files reviewed, 2 unresolved discussions (waiting on @razvan-pro)

___
*[game/autoconfig.py, line 57 at r1](https://reviewable.io/reviews/ocadotechnology/rapid-router/1239#-MpCdtrRCSwaW4lWLoO_:-MpD1pfu8RZ5MUHv8xpV:b-896fix) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/7a33b2a64d0c499093a1c397e6d7a1079d6aa199/game/autoconfig.py#L57)):*
<details><summary><i>Previously, razvan-pro (Razvan Mahu) wrote…</i></summary><blockquote>

Should this be separate as well to be consistent? :slightly_smiling_face: 
</blockquote></details>

Done.
___
*[game/autoconfig.py, line 72 at r1](https://reviewable.io/reviews/ocadotechnology/rapid-router/1239#-Mp7kE7H7JJkjLf6unIN:-MpD1s-P7BKEJRVIJKIB:b-896fix) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/7a33b2a64d0c499093a1c397e6d7a1079d6aa199/game/autoconfig.py#L72)):*
<details><summary><i>Previously, razvan-pro (Razvan Mahu) wrote…</i></summary><blockquote>

`http`, not `s`? :open_mouth: 
</blockquote></details>

Done.

**Review by razvan-pro — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1239#-:-MpD3uJx2swdG8_kFMHY:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @faucomte97)

**Review by razvan-pro — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1239)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @faucomte97)

**Pull request merged**
